---
title: Empirical Strategy
subtitle: Preview
author: Hiroki Kato
output:
  html_document:
    toc: true
    toc_float: true
params:
  preview: true
  appendix: true
  alide: no
---

```{r eval = FALSE, include = FALSE, echo = FALSE}
library(here)
rmarkdown::render(
  input = here("Rmd/3-estimation.rmd"),
  output_format = "all",
  output_dir = here("docs", "html-preview")
)
```

```{r include = FALSE, echo = FALSE}
library(here)
if (params$preview) source(here("R", "_html_header.r"))
source(here("R", "_library.r"))
```

```{asis, echo = output_type() %in% c("body", "preview")}
@Scharf2020 に従い、我々は二種類の弾力性を推定する。
第一に、intensive-margin price elasiticityであり、
1%の価格上昇で寄付者の寄付額が何%増えるかを示している。
第二に、extensive-margin price elasiticityであり、
1%の価格上昇で寄付者比率が何%増えるかを示している。
第\@ref(nastab)節で説明したように、
我々は2014年の税制改革による税インセンティブの変化を用いたDIDと
申告コストによる寄付控除の申請の有無を捉えた操作変数法の二つを組み合わせた識別戦略を用いる。

intensive-margin price elasticityは、
寄付者に限定して以下のtwo-way fixed effect modelを推定する。
\begin{align}
  \ln g_{it} = \theta_i + \gamma (R_{it} \times \ln (1 - s_{it}))
    + \beta X_{it} + \lambda_t + u_{it}, (\#eq:intensive)
\end{align}
ここで、$X_{it}$は課税前所得（$y_{it}$）を含んだ共変量ベクトル、
$\theta_i$と$\lambda_t$はそれぞれ個人固定効果と時間固定効果である。
$u_{it}$はidiosyncratic errorである。
アウトカム変数$\ln g_{it}$は$t$年に寄付した人$i$の寄付額の対数値である。
寄付価格は$R_{it} \times \ln (1 - s_{it})$であり、
ここで、$R_{it}$は控除申請のダミー変数、$s_{it}$は税インセンティブである[^alternative]。
したがって、関心のあるパラメータは$\gamma$であり、
これがintensive-margin price elasticityを示す。

[^alternative]: 寄付価格は$\ln(1 - R_{it}s_{it})$とも書ける。
これは$R_{it} \times \ln (1 - s_{it})$と一致する。
なぜなら、$R_{it} = 0$のとき、$\ln(1) = 0$となり、
$R_{it} = 1$のとき、$\ln(1 - s_{it})$となる。

extensive-margin price elasticityの推定式は
two-way fixed effect付きの線形確率モデルである。
すなわち、
\begin{align}
  D_{it} = \theta_i + \delta (R_{it} \times \ln (1 - s_{it}))
    + \beta X_{it} + \lambda_t + \eta_{it}, (\#eq:extensive)
\end{align}
である。
アウトカム変数$D_{it}$は正の寄付額が観測されたら1を取るダミー変数である：$D_{it} = 1[g_{it} > 0]$。
ここで関心のあるパラメータは$\delta$である。
アウトカム変数は二値なので、このパラメータを弾力性として直接解釈できない。
extensive-margin price elasticityは$\hat{\delta} / \bar{D}$で得られる
（$\bar{D}$は$D_{it}$の標本平均）。

この推定式における二つの内生性に対する対処法について議論する。
第一に、
2014年の税制改革による税インセンティブの変化を寄付価格の外生的な変動要因として用いるが、
寄付価格の内生性は完全に排除できない。
寄付控除を申請した場合の寄付価格を以下のようになる。
\begin{align}
  1 - s_{it} =
  \begin{cases}
    1 - T'_t(y_{it} - g_{it})  \quad\text{if}\quad t < 2014  \\
    1 - m \quad\text{if}\quad t \ge 2014
  \end{cases},
\end{align}
ここで、$T'_t(\cdot)$は$t$年の限界所得税率、$m$は税額控除率($m = 0.15$)である。
寄付価格は2014年の税制改革だけではなく、
所得控除が適用される期間において、寄付額（$g_{it}$）にも依存する。
これは*last*-unit priceと呼ばれるものであり、この寄付価格は寄付額について内生的である[^manipulate]。

[^manipulate]: 寄付額によるインセンティブの操作について、次の二つの可能性が考えられる。
第一に、納税者は寄付額を減らすことで、所得税率を高められる（寄付価格を高められる）。
第二に、納税者は寄付額を増やすことで、所得税率を下げられる（節税の額を増やせる）。

本研究は、過去の研究にならい、
last-unit priceの代わり（もしくはその操作変数）として*first*-unit priceを用いる。
last-unit priceは最終的な寄付額で寄付価格を計算する一方で、
first-unit priceは寄付額をゼロとして寄付価格を計算する[^interpret]。
すなわち、
\begin{align}
  1 - s^f_{it} =
  \begin{cases}
    1 - T'_t(y_{it} - 0)  \quad\text{if}\quad t < 2014  \\
    1 - m \quad\text{if}\quad t \ge 2014
  \end{cases}.
\end{align}
ただし、税額控除が適用される期間においては、
寄付価格が寄付額に依存しないので、last-unit priceとfirst-unit priceは一致する。

[^interpret]: first-unit priceは
最初の1単位を寄付するかどうかの意思決定時に直面する価格として解釈できる。

第二に、寄付控除申告の自己選択による内生性である。
申告コストがないとき、節税による便益を得られるので、
寄付者は全員寄付控除を申請するべきである。
しかしながら、我々のデータでは、寄付者の割合は24%であるにも関わらず、
控除を申告した人の割合は10%である（表\@ref(tab:SummaryCovariate)）。
また、補論\@ref(addtab)の図\@ref(fig:SummaryGivingIntensiveDist)に示しているように、
寄付控除の申告の有無によって、寄付者に限定した寄付額の分布は大きく変化しない。
これは寄付控除の申告行動において、申告コストは大きな障害となっている可能性が高いことを示唆している。

本研究はレコードキーピングの制度が給与所得者と自営業者で異なることを利用して、
給与所得者ダミー（$WE_{it}$）をレコードキーピングのコストの代理変数として操作変数に用いる[^exclusion]。
自営業者は寄付控除を申請するまで寄付の領収書（証明書）を保持しておく必要がある一方で、
給与所得者は会社を通じてその証明書をいつでも提出できるので、
給与所得者は自営業者よりも申告コストが低いことが予想される。

[^exclusion]: 給与所得者ダミーを操作変数として用いるためには、
共変量で条件づけたとき、この変数が$u_{it}$と$\eta_{it}$と独立していることを仮定する必要がある。
ただし、給与所得者ダミーと固定効果の相関は許容できる。
我々は、所得や業種をコントロールすれば、
給与所得者であるかどうかは寄付行動に直接的な影響を持たないと考えている。

@Wooldridge2010 に従い、
我々は給与所得者ダミーを操作変数とした三つのアプローチを用いる[^extensive]。
第一に、給与所得者ダミーとfirst-unit priceの交差項を
$R_{it} \times \ln (1 - s^f_{it})$の操作変数として用いる。
すなわち、intensive-margin price elasiticityの推定式は
\begin{align}
  \ln g_{it} = \theta_i + \gamma (R_{it} \times \ln (1 - s^f_{it}))
    + \beta X_{it} + \lambda_t + u_{it}, (\#eq:intensive2)
\end{align}
であり、
$R_{it} \times \ln (1 - s^f_{it})$の操作変数を$WE_{it} \times \ln(1 - s^f_{it})$とする[^last]。

[^extensive]: 以降ではintensive-margin price elasticityの推定式を用いて説明するが、
extensive-margin price elasticityの推定についても同じ方法が適用できる。

[^last]: last-unit priceを用いて弾力性を推定する場合、
\@ref(eq:intensive)もしくは\@ref(eq:extensive)の説明変数
$R_{it} \times \ln (1 - s_{it})$の操作変数として
$WE_{it} \times \ln(1 - s^f_{it})$を用いる。

残りの二つのアプローチは寄付申告の傾向スコアを用いるものである。
傾向スコアは以下のモデルをプロビット推定した予測確率で得られる。
\begin{align}
  R_{it} = 1[
    \alpha_0 + \alpha_1 WE_{it} + \alpha_2 \ln(1 - s^f_{it})
    + \alpha_3 X_{it} + u_{it0} > 0
  ] (\#eq:selection)
\end{align}

我々は全期間のサンプルを用いた推定（pooled model）と
年で分割したサブサンプルを用いた推定（separeted model）で傾向スコア$\hat{P}_{it}$を得た。
前者のモデルは式\@ref(eq:selection)の係数が時間に対して一定であると仮定している一方で、
後者のモデルは推定される係数が時間に依存することを許容したモデルである。

傾向スコアを用いた第二のアプローチは
式\@ref(eq:intensive2)の説明変数$R_{it} \times \ln (1 - s^f_{it})$の操作変数として
$\hat{P}_{it} \times \ln (1 - s^f_{it})$を用いる。
第三のアプローチは式\@ref(eq:intensive2)の説明変数$R_{it} \times \ln (1 - s^f_{it})$
の代わりに$\hat{P}_{it} \times \ln (1 - s^f_{it})$を用いる。すなわち、
我々は以下のモデルを推定する。
\begin{align}
  \ln g_{it} = \theta_i + \gamma (\hat{P}_{it} \times \ln (1 - s^f_{it}))
    + \beta X_{it} + \lambda_t + u_{it}, (\#eq:intensive3)
\end{align}
```

```{asis, echo = output_type() == "slide"}
## Two Types of Price Elasticity

Following Almunia et al. (2020),

1. Intensive-margin price elasticity: What percentage increase in donor contributions would result from a 1% price increase?
1. Extensive-margin price elasticity: What percentage increase in the donor ratio would result from a 1% price increase?

We use an identification strategy that combines two methods:
(1) DID using changes in tax incentives due to the 2014 tax reform and
(2) IV that captures whether or not a donation deduction is claimed due to filing costs.

## Intensive-Margin Price Elasticity

Two-way FE model:

\begin{align}
  \ln g_{it} = \theta_i + \gamma (R_{it} \times \ln (1 - q_{it}))
    + \beta X_{it} + \lambda_t + u_{it}, (\#eq:intensive)
\end{align}

- $X_{it}$ is a vector of covariate including pre-tax income $y_{it}$
- $\theta_i$ and $\lambda_t$ are individual and time FE, respectively
- $u_{it}$ is idiosyncratic error
- $\ln g_{it}$ is log-valued of amount of donations
- $R_{it}$ is a dummy of application for tax relief
- $q_{it}$ is tax incentive

## Extensive-Margin Price Elasticity

\begin{align}
  D_{it} = \theta_i + \delta (R_{it} \times \ln (1 - q_{it}))
    + \beta X_{it} + \lambda_t + \eta_{it}, (\#eq:extensive)
\end{align}

- $D_{it}$ is a dummy indicating a donor
- The parameter of interest is $\delta$. Since the outcome variable is binary, this parameter cannot be directly interpreted as elasticity.
- Extensive-margin price elasticity is obtained by $\hat{\delta} / \bar{D}$. ($\bar{D}$ is the sample mean of $D_{it}$)

## Two Endogenous Problem

We will discuss how to resolve following two endogenous problems:

1. price depends on giving amount when income deduction is applied
1. self-selection of application for tax incentive

## Endogenous Applicable Giving Price

- We use changes in tax incentives due to the 2014 tax reform as an exogenous variation of price
- Endogeneity of prices cannot be completely ruled out because we use data when income deduction was applied.
- The donation price when the tax relief is applied would be as follows:
\begin{align}
  1 - q_{it} =
  \begin{cases}
    1 - T'_t(y_{it} - g_{it})  \quad\text{if}\quad t < 2014  \\
    1 - m \quad\text{if}\quad t \ge 2014
  \end{cases},
\end{align}

- Price also depends on the amount of the donation ($g_{it}$) during the period when the income deduction is applied. 
  - This is called *last*-unit price

## Resolve Endogenous Applicable Giving Price

- Following previous studies, we use *first*-unit price as an alternative to (or as IV for) last-unit price.
- First-unit price is giving price with the donation amount as zero.
\begin{align}
  1 - q^f_{it} =
  \begin{cases}
    1 - T'_t(y_{it} - 0)  \quad\text{if}\quad t < 2014  \\
    1 - m \quad\text{if}\quad t \ge 2014
  \end{cases}.
\end{align}
- the last-unit price and first-unit price coincide during the period when the tax credit is applied,
since the donation price is independent of the donation amount.

## Self-Selection of Tax Incentive

- All donors should claim income deduction/tax credit if there is no compliance cost
because they can obtain benefit of tax savings
- Our data suggests that compliance cost is likely a major obstacle in application for tax relief.
  - 24% donor, but 10% donors claimed income deduction/tax credit
  - The distribution of donations conditional on donors does not change significantly depending on
  whether or not the tax relief is applied.

## Resolve Self-Selection of Tax Incentive

- We exploit the fact tax system differs between wage earners and self-employed workers,
and use a wage earner dummy ($\text{WE}_{it}$) as a proxy for the compliance cost.
  - Self-employed workers have to understand tax system to precisely populate tax return and retain the certificate until they submit tax return
  - Wage earners need not to understand tax system and can submit the certificate at any time.
- It is necessary to assume that this variable is independent of $u_{it}$ and $\eta_{it}$ conditional on covariates. 
  - the correlation between the salaried worker dummy and fixed effects is acceptable.
- We believe that being a salaried employee or not has no direct effect on donation behavior if we control for income and industry.

## Three Estimation Methods to Resolve Two Endogenous Problem (1)

1. FE-2SLS with $\text{WE}_{it} \times \ln(1 - q^f_{it})$ as an IV

\begin{align}
  \ln g_{it} = \theta_i + \gamma (R_{it} \times \ln (1 - q^f_{it}))
    + \beta X_{it} + \lambda_t + u_{it}, (\#eq:intensive2)
\end{align}

where $\text{WE}_{it} \times \ln(1 - q^f_{it})$ is an insturument of
$R_{it} \times \ln (1 - q^f_{it})$

## Three Estimation Methods to Resolve Two Endogenous Problem (2)

- Remaining two methods are based on propensity socre.
- Propensity score is obtained by the predicted probability of probit estimation of the following model:
\begin{align}
  R_{it} = 1[
    \alpha_0 + \alpha_1 WE_{it} + \alpha_2 \ln(1 - q^f_{it})
    + \alpha_3 X_{it} + u_{it0} > 0
  ] (\#eq:selection)
\end{align}

- The propensity score $\hat{P}_{it}$ is obtained by estimation using (1) full sample (pooled model)
and (2) a subsample divided by years (separated model)
  - The former assumes coefficients are constant with rispect to year
  - The latter allows coefficients to depend on year

## Three Estimation Methods to Resolve Two Endogenous Problem (3)

Again,

\begin{align*}
  \ln g_{it} = \theta_i + \gamma (R_{it} \times \ln (1 - q^f_{it}))
    + \beta X_{it} + \lambda_t + u_{it},
\end{align*}

Remaining two estimation methods:

2. We use $\hat{P}_{it} \times \ln (1 - q^f_{it})$ as an instrument of $R_{it} \times \ln (1 - q^f_{it})$
3. We use $\hat{P}_{it} \times \ln (1 - q^f_{it})$ instead of $R_{it} \times \ln (1 - q^f_{it})$ as the explanatory variable.
```