---
title: |
  Charitable Giving, Tax Reform, and Self-selection of Tax Relief: Evidence from South Korea
author: 
  - name: Hiroki Kato
    inst: Graduate School of Economics, Osaka University, Japan
    email: vge008kh\@stundent.econ.osaka-u.ac.jp
  - name: Tsuyoshi Goto
    inst: Graduate School of Social Sciences, Chiba University, Japan
    email: t.goto\@chiba-u.jp
  - name: Youngrok Kim
    inst: Graduate School of Economics, Kobe University, Japan
date: "`r format(Sys.time(), '%Y/%m/%d')`"
bibliography_main: [Rmarkdown/ref_main.bib]
bibliography_appx: [Rmarkdown/ref_appx.bib]
csl: template/csl/elsevier-harvard.csl
abstract: |
  This paper investigates the price elasticity of charitable giving utilizing South Korean tax reform in 2014, when the tax relief on charitable giving changed from tax deduction to tax credit. Although many research on the price elasticity of charitable giving use tax return data or ignore declaration cost for charitable giving to receive tax relief, this paper uses a survey panel data and considers the existence of declaration cost for tax reliefs on charitable giving.
  By considering the declaration of charitable giving and exploiting the different declaration cost between wage earners and self-employed workers as instrument variable (IV), we estimate the giving price elasticity on the donation. As a result, we find that the estimation about the price elasticity is -1.5 $\sim$ -1.8 in terms of intensive margins. 
  Moreover, our estimation suggest that the price elasticity for the extensive margins is less than -1.8, which is much less than the estimates of extant research. 
keyword:
  words: Charitable giving, Giving price, Tax reform, South Korea
  JEL: D91, I10, I18
documentclass: article
papersize: a4
fontsize: 11pt
geometry: "left=3cm,right=3cm,top=3cm,bottom=3cm"
graphics: yes
indent: yes
linespace: 1.5
output:
  bookdown::pdf_document2:
    latex_engine: xelatex
    number_sections: yes
    keep_tex: yes
    fig_caption: yes
    toc: false
    dev: cairo_pdf
    template: template/tex/plain.tex
    pandoc_args: --lua-filter=luafilters/multiple-bibliographies/multiple-bibliographies.lua
params:
  preview: false
---

```{r knit_command, eval = FALSE, include = FALSE, echo = FALSE}
# If you want to knit draft, please run following command manually!!
rmarkdown::render(
  "draft.Rmd",
  output_file = "draft.pdf",
  output_dir = "paper"
)
```

```{r setup, include = FALSE, echo = FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo = FALSE,
  cache = FALSE,
  include = TRUE,
  fig.width = 10, fig.height = 6,
  fig.align = "center", fig.pos = "t"
)

library(here); knitr::opts_knit$set(root.dir = here())
xfun::pkg_attach2(c("tidyverse", "kableExtra"))
options(
  knitr.kable.NA = " ",
  knitr.table.format = "latex"
)

doctype <- "draft"
```

```{r function, include = FALSE, echo = FALSE}
library(xfun)
xfun::pkg_attach2(c(
  "tidyverse", "rlist", "modelsummary", "kableExtra",
  "estimatr", "fixest"
))

lapply(Sys.glob(file.path("script/R/functions", "*.r")), source)
```

```{r child = "Rmarkdown/introduction.Rmd"}
```

```{r}
knitr::spin_child("script/R/1-summary.R")
```

```{r child = "Rmarkdown/estimation.Rmd"}
```

```{r}
knitr::spin_child("script/R/2-pooled2sls.R")
```

```{r child="Rmarkdown/conclusion.Rmd"}
```

\newpage

# References {-}

::: {#refs_main}
:::

\newpage

# (APPENDIX) Appendix {-}
# Appendix {-}
# Additional Figures and Tables

```{r stage1, ref.label="stage1"}
```

```{r rob1intensive, ref.label="rob1intensive"}
```

```{r rob2intensive, ref.label="rob2intensive"}
```

```{r robextensive, ref.label="robextensive"}
```

\clearpage

```{r}
knitr::spin_child("script/R/3-subsample.R")
```

\clearpage

```{r child = "Rmarkdown/appendix.Rmd", eval = FALSE}
```