---
title: |
  Charitable Giving, Tax Reform, and Government Efficiency
#thanks: 
#  - code: 1
#    content: |
#      This research is base on
author: 
  - name: Hiroki Kato
    affiliation: Osaka University
    e-mail: vge008kh\@stundent.econ.osaka-u.ac.jp
    code: 1
    footnote: \*
  - name: Tsuyoshi Goto
    affiliation: Chiba University
    code: 2
  - name: Yong-Rok Kim
    affiliation: Kobe University
    code: 3
address:
  - code: Osaka University
    address: Graduate School of Economics, Osaka University, Japan
  - code: Chiba University
    address: Graduate School of Social Sciences, Chiba University, Japan
  - code: Kobe University
    address: Graduate School of Economics, Kobe University, Japan
footnote:
  - code: \*
    text: "Corresponding Author."
date: "`r format(Sys.time(), '%Y/%m/%d')`"
bibliography: manuscript/Ref.bib
csl: template/elsevier-harvard.csl
review: yes  #Elsevier Template
classoption: 3p  #Elsevier Template
abstract: |
  This paper investigates the price elasticity of charitable giving utilizing South Korean tax reform in 2014, when the tax relief on charitable giving changed from tax deduction to tax credit. Although the extant research ignores whether tax payers really declare their tax relief on charitable givieng, this paper considers it by focusing on the difference of declaration cost between wage earners and self-employed workers in Korea. By utilizing this difference as an instrument variable (IV), we estimate an "effective" giving price, which is calculated by the existence of declaration and tax rate, and compare the estimation using it with the baseline estimation using the "applicable" giving price, which the extant papers have been used. As a result, we find that the estimation using the "effective" price is almost the same for the baseline one in terms of intensive margins while the estimated price elasticity using the "effective" price is much smaller than the baseline one in terms of extensive margins. This implies that the declaration cost of tax relief is larger than the literature assumed. 
keyword:
  text: "Charitable giving, Giving price, Tax reform, Governement efficiency, South Korea"
  JEL: D91, I10, I18
---

```{r setup, include = FALSE, echo = FALSE}
library(here)
knitr::opts_chunk$set(
  message = FALSE, 
  warning = FALSE, 
  echo = FALSE, 
  cache = FALSE,
  include = FALSE,
  fig.width = 10, fig.height = 6,
  fig.align = "center",
  fig.pos = "t"
)
knitr::opts_knit$set(root.dir = here())
```

```{r library}
library(xfun)
xfun::pkg_attach2(c("readstata13", "tidyverse", "rlist"))
xfun::pkg_attach2(c("plm", "lmtest", "sandwich", "lfe", "Formula"))
xfun::pkg_attach2(c("kableExtra"))
source("script/R/00-analysis_functions.r")
options(knitr.kable.NA = "")
```

```{r GGTemp}
my_theme <- theme_minimal() +
  theme(
    # setting: background
    plot.background = element_rect(
      #fill="#87CEEB50", 
      color = "transparent"
    ),
    
    # setting: plot
    panel.border = element_rect(color = "white", fill = NA),
    panel.background = element_rect(fill = "white"),   
    panel.grid = element_line(color = "grey80"),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.minor.y = element_blank(),
    
    # setting: text
    plot.title = element_text(hjust=0.5,size=20),       
    plot.caption = element_text(size=11),       
    
    # setting: axis
    axis.text = element_text(color="black",size=13),    
    axis.title = element_text(size=13),
    axis.ticks.length = unit(0.25, "cm"),
    axis.ticks.x = element_line(),
    axis.ticks.y = element_line(),
    axis.line = element_line(),
    
    # setting: legend
    legend.title = element_text(size=12),               
    legend.text = element_text(size=12),                
    legend.key.size = unit(0.5,"cm"),
    #legend.background = element_rect(color = "black"), 
    legend.position = "bottom"
  )
```