---
title: |
  Estimating Effect of Tax Incentives on Donations Considering Self-Selection of Tax Incentives in South Korea
author: 
  - name: Hiroki Kato
    inst: Graduate School of Economics, Osaka University, Japan
    email: h-kato\@econ.osaka-u.ac.jp
  - name: Tsuyoshi Goto
    inst: Graduate School of Social Sciences, Chiba University, Japan
    email: t.goto\@chiba-u.jp
  - name: Youngrok Kim
    inst: Graduate School of Economics, Kobe University, Japan
date: "`r format(Sys.time(), '%Y/%m/%d')`"
bibliography: Rmd/NaSTaB.bib
csl: template/csl/elsevier-harvard.csl
documentclass: article
papersize: a4
fontsize: 11pt
geometry: "left=3cm,right=3cm,top=3cm,bottom=3cm"
graphics: yes
indent: yes
linespace: 1.5
output:
  bookdown::pdf_document2:
    latex_engine: xelatex
    number_sections: yes
    keep_tex: yes
    fig_caption: yes
    toc: false
    dev: cairo_pdf
    template: template/tex/plain.tex
params:
  preview: no
  appendix: no
  slide: no
---


```{r knit_command, eval = FALSE, include = FALSE, echo = FALSE}
# If you want to knit draft, please run following command manually!!
library(here)
rmarkdown::render(
  here("root-body.Rmd"),
  output_file = "body.pdf",
  output_dir = here("docs", "paper")
)
```

```{r setup, include = FALSE, echo = FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo = FALSE,
  cache = FALSE,
  include = TRUE,
  fig.width = 10, fig.height = 6,
  fig.align = "center", fig.pos = "t"
)

options(
  knitr.kable.NA = " ",
  knitr.table.format = "latex"
)
```

# Introduction {#intro}

```{r child = "Rmd/1-introduction.rmd"}
```

## Institutional background and Sources of endogeneity {#background}

```{r child = "Rmd/2-background.rmd"}
```


# Data: National Survey of Tax and Benefit (NaSTaB) {#nastab}

```{r}
library(here)
knitr::spin_child(here("R/1-summary.R"))
```

# Empirical Strategy {#estimation}

```{r child = "Rmd/3-estimation.rmd"}
```

# Estimation Results {#result}

```{r eval = FALSE}
library(here)
knitr::spin_child(here("R/3-main-estimation.R"))
knitr::spin_child(here("R/4-conventional-estimation.R"))
knitr::spin_child(here("R/5-subsample-R1.R"))
```

<!-- ## Interpretation

サンプルを3つのタイプに分割する。

1. Always declarer：給与所得者かどうかによる申告コストの水準に関わらず、寄付控除を申告する人
  - 2014年の税制改革によって価格のwitin-variationは存在するが、常に寄付をする
  - したがって、このグループのextensive-marginの価格弾力性は（絶対値の意味で）0
1. Start declarer：申告コストの水準が自営業者から給与所得者の水準まで下がることで、寄付控除を申告する人
1. Never declarer：給与所得者かどうかによる申告コストの水準に関わらず、寄付控除を申告しない人
  - 常に価格が1であるにも関わらず、寄付額や寄付の意思決定が変化する
  - intensive-margin・extensive-marginの価格弾力性は無限大に発散する

したがって、3タイプの価格弾力性の大きさは絶対値の意味で以下のような関係になっているのではないだろうか？

- Intensive-margin：Always < Start < Never
  - ただし、これは後藤さんのロジックである「申告で常に得するような人は多少の価格変動に動じない」を借りている
- Extensive-margin：Always < Start < Never 

Intensive-marginのFEはAlwaysとStartに過重を置いて推定している（というか、Neverタイプが多くない）。
Extensive-marginのFEはNeverに過重を置いて推定している。
しかしながら、FE-2SLSはStartの弾力性を捉えているはずなので、

- Intensive-margin：FE < FE-2SLS
- Extensive-margin：FE-2SLS < FE

となった。 -->

# References {-}