---
title: |
  Estimating Effect of Tax Incentives on Charitable Giving Considering Self-Selection of Tax Relief in South Korea
author: 
  - name: Hiroki Kato
    number: 1
  - name: Tsuyoshi Goto
    number: 2
  - name: Yong-Rok Kim
    number: 3
institute:
  - number: 1
    name: Osaka University
  - number: 2
    name: Chiba University
  - number: 3
    name: Kansai University
date: "`r format(Sys.time(), '%Y/%m/%d')`"
csl: template/csl/elsevier-harvard.csl
aspectratio: 169
graphics: yes
output:
  bookdown::pdf_book:
    base_format: "function(..., number_sections) rmarkdown::beamer_presentation(...)"
    number_sections: false
    latex_engine: xelatex
    keep_tex: true
    toc: false
    slide_level: 2
    template: template/tex/plain.tex
params:
  preview: no
  appendix: no
  slide: yes
header-includes:
  - \usepackage{siunitx}
---

```{r knit_command, eval = FALSE, include = FALSE, echo = FALSE}
# If you want to knit draft, please run following command manually!!
library(here)
rmarkdown::render(
  here("root-slide.Rmd"),
  output_file = "slide.pdf",
  output_dir = here("docs", "slide")
)
```

```{r setup, include = FALSE, echo = FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo = FALSE,
  cache = FALSE,
  include = TRUE,
  fig.width = 10, fig.height = 6,
  fig.align = "center", fig.pos = "t",
  out.width = "70%"
)

options(
  knitr.kable.NA = " ",
  knitr.table.format = "latex",
  modelsummary_stars_note = FALSE
)
```

```{r child = "Rmd/1-introduction.rmd"}
```

# Institutional background and Sources of Endogeneity {#background}

```{r child = "Rmd/2-background.rmd"}
```

# Data: National Survey of Tax and Benefit (NaSTaB) {#nastab}

```{r}
library(here)
knitr::spin_child(here("R/2-summary.R"))
```

# Empirical Strategy {#estimation}

```{r child = "Rmd/3-estimation.rmd"}
```

# Estimation Results {#result}

```{r}
library(here)
knitr::spin_child(here("R/7-abadie.R"))
knitr::spin_child(here("R/3-main-estimation.R"))
# knitr::spin_child(here("R/4-conventional-estimation.R"))
knitr::spin_child(here("R/5-subsample-R1.R"))
```

# Appendix

```{r}
options(knitr.duplicate.label = "allow")
unlockBinding("params", env = .GlobalEnv)
params$appendix <- TRUE
library(here)
knitr::spin_child(here("R/3-main-estimation.R"))
knitr::spin_child(here("R/5-subsample-R1.R"))
```