---
title: |
  Appendix
  "Estimating Effect of Tax Incentives on Donations Considering Self-Selection of Tax Incentives in South Korea"
author: 
  - name: Hiroki Kato
    inst: Graduate School of Economics, Osaka University, Japan
    email: vge008kh\@stundent.econ.osaka-u.ac.jp
  - name: Tsuyoshi Goto
    inst: Graduate School of Social Sciences, Chiba University, Japan
    email: t.goto\@chiba-u.jp
  - name: Youngrok Kim
    inst: Graduate School of Economics, Kobe University, Japan
date: "`r format(Sys.time(), '%Y/%m/%d')`"
csl: template/csl/elsevier-harvard.csl
documentclass: article
papersize: a4
fontsize: 11pt
geometry: "left=3cm,right=3cm,top=3cm,bottom=3cm"
graphics: yes
indent: yes
linespace: 1.5
output:
  bookdown::pdf_document2:
    latex_engine: xelatex
    number_sections: yes
    keep_tex: yes
    fig_caption: yes
    toc: yes
    dev: cairo_pdf
    template: template/tex/plain.tex
params:
  preview: no
  appendix: yes
  slide: no
---


```{r knit_command, eval = FALSE, include = FALSE, echo = FALSE}
# If you want to knit draft, please run following command manually!!
library(here)
rmarkdown::render(
  here("root-appendix.Rmd"),
  output_file = "appendix.pdf",
  output_dir = here("docs", "paper")
)
```

```{r setup, include = FALSE, echo = FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo = FALSE,
  cache = FALSE,
  include = TRUE,
  fig.width = 10, fig.height = 6,
  fig.align = "center", fig.pos = "t"
)

options(
  knitr.kable.NA = " ",
  knitr.table.format = "latex"
)
```

# (APPENDIX) Appendix {-}
# Additional Tables and Figures {#addtab}

```{r}
library(here)
knitr::spin_child(here("R/1-summary.R"))
```