
```{r setup, include = FALSE, echo = FALSE}
library(here)
knitr::opts_chunk$set(
  message = FALSE, 
  warning = FALSE, 
  echo = FALSE, 
  cache = FALSE,
  include = FALSE,
  fig.width = 10, fig.height = 6,
  fig.align = "center"
)
knitr::opts_knit$set(root.dir = here())

library(tidyverse)
library(readstata13)
library(kableExtra)
options(knitr.kable.NA = "")
```

# Introduction

<!--- Slides 
## Charitable Giving and Taxiation
In many countries, governments set a tax relief for charitable giving.

To evaluate the effect of tax relief, many papers investigate the elasticity of charitable donations with respect to their tax price [@Randolph1995; @Auten2002; @Fack2010; @Bakija2011; @Almunia2020].

Focusing on the tax deduction or tax credit on the charity, they show that the price elasticity of giving is about -1 or more in terms of absolute value.

## Charitable Giving and Taxiation

In addition to the tax price charitable donations, the donations may be affected by people's perception towards the government. 

This is because the works and missions of private charity often mirror or overlap with one of governments, and the charity is not needed if the government adequately satisfies the needs of society.

Thus, the different perception towards the government may make the different behavior for charitable giving.

We investigate the relation between tax price elasticity of charitable donations and the different perception towards the government using the South Korean dataset.


## Summary in short

Our result classifies that:

- the price elasticity of giving in Korea is -1.07 ~ -1.26, which is within the range of the extant research.
- the amount of donation is not different between those who regard government as inefficient and the others.
- the giving price elasticity of those who regard government as inefficient is more elastic than the others. This means that those who think of government as inefficient have more willingness to donate for 1\% reduction of giving price. 

## South Korean tax reform

We can utilize the effect of the 2014 tax reform in the South Korea.

- Before 2014, tax deduction was adopted to subsidize charitable donation behavior.
- After 2014, tax credit have been adopted.

The main difference is that tax credits reduce taxes directly, while tax deductions indirectly lower the tax burden by decreasing the marginal tax rate, which increases with gross income.

In addition, the dataset contains the information about perception towards the government.


## Related Literature

This study mainly relates to the two strands of studies.

 1. Research about tax price elasticity of charitable donations
 2. Research about perception towards the government and donation/tax payment.
  

## Research about tax price elasticity of charitable donations

Papers in this strand examines the price and income elasticity of charitable donations using the tax deduction applied for donation.
The estimated price elasticities vary, but the typical one is said as -1 (Andreoni and Payne, 2013).
  
  - Auten et al.(2002): -0.79~-1.26 (the U.S.)
  - Fack and Landais(2010): -0.15~-0.57 (France)
  - Bakija and Heim (2011): -0.61~-1.1 (the U.S.)
  - Duquette (2016): -2.15~-5.01 (the U.S.)
  - Almunia et al.(2020): -0.24~--1.5 (the U.K.)
  
The study in non-Western country, where the culture of donation may be different, is few.
Thus, we firstly examine the elasticity of giving in Korea.

## Research about perception towards the government and donation/tax payment.

Experimental studies show that the giving behavior may be affected by perception towards the government.

 - Li et al.(2011) suggest that governmental organizations collect less donation than private charities though they have the same mission and work.
 - Sheremeta and Uler(2020) show that individuals provide public good reacting the wasteful spending of government.

This may be because people with distrust in government think that

 1. the direct donation is more efficient than public service provision or
 2. people can directly allocate and control their funds by donation, unlike public service provision. 

Thus, people having the different trust in the government would have different elasticities of giving.

--->


In many countries, governments set a tax relief for charitable giving. This is because, if subsidizing charitable giving induces a large increase in donations, it is desirable for public good provision. To evaluate the effect of tax relief, many papers investigate the elasticity of charitable donations with respect to their tax price [@Randolph1995; @Auten2002; @Fack2010; @Bakija2011; @Almunia2020]. Focusing on the tax deduction or tax credit on the charity, they show that the price elasticity of giving is about -1 or more in terms of absolute value, which means that the tax relief for the charitable giving is good in the sense that 1\% tax relief derives more than 1\% donation.

However, if the government can provide public good more efficiently than the direct donation, the donation may not be preferable because the public good provision via donation would be costly then.
Moreover, when the government is much more efficient than charities, people may not donate so much even if they have a warm-glow preference. @Saez2004 suggests that the change of the relative price between public good provision by donation and government will change the behavior of people and the price elasticity of donation. 
However, the evaluation about the efficiency of the government is usually subjective and different for people. If someone regard the government as efficient, the perceived relative price of giving would be high for them. Thus, the giving behavior would be affected by the subjective perception towards the government.

Considering these points, this paper investigates (1) the price elasticity of giving and (2) whether the different perception towards the government cause the different giving behavior using South Korean panel data. 
Our first main concern is the price elasticity of charity. South Korea (Korea hereafter) experienced the tax reform in 2014, from when the tax relief on charitable giving was conducted by tax credit, though tax deduction had been used before 2014. Thus, we exploit this tax reform as an exogenous policy change to derive the price elasticity of giving. Since the extant research focus on the tax reform within the scheme of tax deduction or tax credit, this paper firstly deals with the tax reform from tax deduction system to tax credit system.
Our result classifies that the price elasticity of giving in Korea is -1.07 ~ -1.26, which is within the range of the extant research. 

Our second concern is the relationship between the giving behavior and the perception towards the government. As we explained, people feeling administrative inefficiency would consider the direct donation is more efficient and would have more willingness to donate. Using the Korean field data, we investigate this and show that the amount of donation is not different between those who regard government as inefficient and the others, though the giving price elasticity of the former is more elastic than the latter. This means that those who think of government as inefficient have more willingness to donate for 1\% reduction of giving price. 

This paper contributes two strands of charitable giving literature: the elasticity of charitable donations with respect to their tax price and the perception of government's inefficiency. The examples of papers in the first strand are @Randolph1995, @Auten2002, @Fack2010, @Bakija2011, and @Almunia2020. They typically use the tax return data, the main part of which is the data about wealthy people. Since our data is based on survey, which reflects the income distribution of population, we believe that we can estimate the giving price elasticity of population more precisely. Using the data with low-income households may be difficult to estimate the giving price elasticity in terms of intensive margin since they are expected to donate less than high-income households. To address this issue, we estimate not only the elasticity of intensive margin, as most of papers do, but also the elasticity of extensive margin following @Almunia2020. 
Moreover, we use the data of Korea, a non-Western country, which the extant research did not examine\footnote{This point may be important since Kim (2021) reports that the giving behavior is strongly affected by the cultural matter such as the religious belief.}.

In the second strand, there are some experimental studies and papers considering the tax evasion. Using an experiment, @Li2011 compare people's willingness to give money for private charities and government agencies whose missions are the same. They show that people tend to donate for private charities more than government agency though they do not directly investigate the relationship between people's perception toward the government and giving behavior. @Sheremeta2020 show that people increase the voluntary public good provision when they face the wasteful government spending in the experimental setting. Although the government in their setting does not provide public good, they suggest that the willingness for donation may increase if people perceive the inefficiency of government. In the tax evasion literature, several paper suggests the perceived inefficiency of government reduce tax morale [@Frey2007; @Hammar2009; @Anderson2017]. We contribute on this literature by showing the relation between the perception of government efficiency and the giving behavior. 

This paper consist of XXX sections. Section 2 and 3 respectively explain the institutional background and data. Section 4 deals with the analysis of giving price elasticity and section 5 shows the analysis of perceptions toward the government. We discuss the result in section 6 and section 7 concludes.
