# Institutional background

In this section, we describe the income tax relief for charitable giving in Korea and used dataset.

## Tax relief for charitable giving by tax deduction and tax credit

<!-- For Slides
In the South Korea, the tax policy about charitable giving drastically changed in 2014. Before then, tax relief of charitable giving was provided by tax deduction while, from 2014, tax relief by tax credit was introduced instead of tax deduction. 

The tax deduction and tax credit may have different effects on giving behavior. 
This section summarize the difference of tax deduction and tax credit.

## Budget Set

Consider that a household has a choice between private consumptions ($x_i$) and charitable giving ($g_i$). Let $y_i$ be pre-tax total income.
Then, the budget constraint is 

$$
    x_i + g_i = y_i - T_i(y_i, g_i).
$$
$T_i$ is tax amount which depends on the pre-tax income and charitable giving.

## Tax Deduction

Tax deduction reduces taxable income by giving, that is,

$$
    T_i = \tau(y_i - g_i) \cdot (y_i - g_i),
$$

where $\tau(\cdot)$ is the marginal income tax rate which is determined by $y_i - g_i$. The budget constraint will be 

$$
    x_i + [1 - \tau(y_i - g_i)]g_i = [1 - \tau(y_i - g_i)] y_i.
$$

The relative price of giving is $p_i^{d} \equiv 1 - \tau(y_i - g_i)$.
Since the giving price in tax deduction scheme varies depending on (1) the income level and (2) the amount of charitable giving, it is endogenous to them.

## Tax Credit

Tax credit reduces tax amount directly, that is,

$$
    T_i = \tau(y_i)\cdot y_i - m g_i,
$$

where $m \in [0, 1]$ is the tax credit rate. Under the tax credit system, the budget constraint is 

$$
    x_i + (1 - m) g_i = [1 - \tau(y_i)] y_i.
$$

The relative price of giving is $p_i^c = 1 - m$, 
which is only dependent on the tax credit rate $m$, which is exogenously determined by the government.

-->


In the South Korea, the tax policy about charitable giving drastically changed in 2014. Before then, tax relief of charitable giving was provided by tax deduction while, from 2014, tax relief by tax credit was introduced instead of tax deduction. 

The tax deduction and tax credit may have different effects on giving behavior. This subsection summarize the difference of tax deduction and tax credit.
Consider that a household has a choice between private consumptions ($x_i$) and charitable giving ($g_i$). Let $y_i$ be pre-tax total income.
Then, the budget constraint is 

$$
    x_i + g_i = y_i - D_iT_i(y_i, g_i) - (1-D_i)T_i(y_i).
$$
$T_i$ is tax amount which depends on the pre-tax income and charitable giving.
$D_i$ is the dummy which takes 1 if $i$ declares the tax relief and 0 otherwise. 
On one hand, tax deduction reduces taxable income by giving. The amount of tax is

$$
    T_i(y_i, g_i) &= \tau(y_i - g_i) \cdot (y_i - g_i)
    T_i(y_i) &= \tau(y_i) \cdot (y_i - g_i),
$$

where $\tau(\cdot)$ is the income tax rate which is determined by $y_i - g_i$ or $y_i$.[^ATR] The budget constraint will be 

[^ATR]: $\tau(\cdot)$ here is a function which shows the average tax rate, which is determined progressively. Since the price elasticity of giving shows the marginal and additional increment for one unit of price reduction increase, we use not average but marginal tax rate to construct the giving price following the literature. Usage of the function of the average tax rate here is for explanatory simplicity.

$$
    x_i + [1 - D_i\tau(y_i - g_i)-(1-D_i)\tau(y_i)]g_i = [1 - D_i\tau(y_i - g_i)-(1-D_i)\tau(y_i)] y_i.
$$

Thus, the giving price compared to the price of private consumption is $p_i^{d} \equiv 1 - D_i\tau(y_i - g_i)-(1-D_i)\tau(y_i)$ in tax deduction system. Since the giving price in tax deduction scheme varies depending on (1) the income level, (2) the amount of charitable giving, and (3) declaration of tax relief, it is endogenous to them, i.e. (1), (2), and (3).

On the other hand, tax credit reduces tax amount directly, that is,

$$
    T_i = \tau(y_i)\cdot y_i - D_im g_i,
$$

where $m \in [0, 1]$ is the tax credit rate. Under the tax credit system, the budget constraint is 

$$
    x_i + (1 - D_im) g_i = [1 - \tau(y_i)] y_i.
$$

Thus, the giving price of tax credit system will be $p_i^c = 1 - D_im$, which is only dependent on the tax credit rate $m$, which is exogenously determined by the government, and declaration $D_i$.
Therefore, the giving price in the tax credit system would not be manipulated by donors except the declaration.

In the literature of giving tax relief, many papers implicitly assume that all tax payers automatically enjoy tax relief for charitable giving, i.e. $D_i=1$ for all $i$\footnote{As an exception, @Almunia2020 considers the declaration by using the stractural estimation.}. This means that the estimated price elasticity in the extant papers usually shows ITT since the tax relief is intended to be applied, although researchers do not know whether it is really applied or not. In section 5, we assume $D_i=1$ for all $i$ following the extant research and estimate ITT as a baseline result. In section 6, we remove this assumption and $D_i$ can be 0 or 1 depending on each $i$.

## Korean tax system and tax reform in 2014

<!--- For Slides

- The tax incentives for charitable giving in Korea stared in 2000 and the market of charitable giving in Korea totaled 10.9 trillion KRW (approximately 1.09 bilion USD, 0.761% of GDP) in 2012 according to the national tax statistics.
- Since the income tax deduction was initially used as a tax incentive and the marginal income tax rate was determined as Table \@ref(tab:tabTaxRate), the minimum giving price before 2014 was 0.62. 
--->

The tax incentives for charitable giving in Korea stared in 1967 and the market of charitable giving in Korea totaled 10.9 trillion KRW (approximately 1.09 bilion USD, 0.761% of GDP) in 2012 according to the national tax statistics.
Since the income tax deduction was initially used as a tax incentive and the marginal income tax rate was determined as Table \@ref(tab:tabTaxRate), the minimum giving price before 2014 was 0.62.

<!---In addition, the government set the limit of charitable giving deduction, which was initially the 5\% of income. The government gradually expanded the limit and it finally became 30\% in 2012 and this rate continues until now.
--->

<!--- For Slides 

## Marginal income tax rate

--->

```{r tabTaxRate, include=TRUE}
tab <- data.frame(
    inc = c(
        "(A) ~ 1200", "(B) 1200 ~ 4600", "(C) 4600 ~ 8800", "(D) 8800 ~ 15000", 
        "(E) 15000 ~ 30000", "(F) 30000 ~ 50000", "(G) 50000 ~"),
    Y08 = c("8%", "17%", "26%", rep("35%", 4)),
    Y09 = c("6%", "16%", "25%", rep("35%", 4)),
    Y1011 = c("6%", "15%", "24%", rep("35%", 4)),
    Y1213 = c("6%", "15%", "24%", rep("35%", 2), rep("38%", 2)),
    Y1416 = c("6%", "15%", "24%", "35%", rep("38%", 3)),
    Y17 = c("6%", "15%", "24%", rep("35%", 2), "38%", "40%"),
    Y18 = c("6%", "15%", "24%", "35%", "38%", "40%", "42%")
)

knitr::kable(
    tab,
    format = "latex",
    caption = "Marginal Income Tax Rate",
    col.names = c("Income/Year", "2008", "2009", "2010 ~ 2011", "2012 ~ 2013", "2014 ~ 2016", "2017", "2018"),
    row.names = FALSE,
    align = "lccccccc", 
    booktabs = TRUE, escape = TRUE, linesep = ""
) %>% 
kable_styling(font_size = 7) %>% 
collapse_rows(columns = 2:8, valign = "middle", latex_hline = "full") %>%
footnote(general_title = "", general = "Notes: Marginal income tax rates applied from 2008 to 2018 are summarized. The income level is shown in terms of 10,000 KRW, which is approximately 10 United States dollars (USD) at an exchange rate of 1,000 KRW to one USD.", threeparttable = TRUE, escape = FALSE)
```

<!--- For Slides 

## Our Identification Strategy

-->

Korean tax system offers a tax relief for charitable giving in income tax. All tax payers have to declare their donation and submit the certificate of charitable giving to receive tax relief, while the taxiation method and the way of tax declaration are different for wage earners and self-employed workers. Wage earners pay income tax by withholding tax and declare tax relief for charitable giving via their company. Self-employed workers pay income tax by tax-return and declare tax relief when they submit tax return to the National Tax Service. Therefore, there is a difference of declaration cost of tax relief since self-employed workers have to retain the certificate until they submit tax return although wage earners can submit the certificate at any time.   

In 2014, aiming at the relaxation of regressivity of giving price, the Korean government reformed tax system again, where the tax credit was introduced instead of tax deduction. Since then, 15\% of the total amount of charitable giving has been allowed as a tax credit, which means that the giving price from 2014 is 0.85 irrelevant to the income level.

Summarizing this, compared to tax credit system, the high income household, whose (average) income tax rate is more than 15\%, get benefit from charitable giving under the tax deduction system. However, middle or low income households would enjoy tax relief in tax credit system more than tax deduction system. We exploit this policy change as an identification strategy.
