# Main Results

## Price and Income Elasticity

```{stata EstimateElasticity, results = "hide", eval = FALSE}
label variable log_price "ln(giving price)"

* baseline
xtreg log_total_g log_price log_pinc_all i.year, fe vce(cluster pid)
mat coef = r(table)["b".."pvalue", "log_price"]
mat colnames coef = model0
mat stat = e(N) \ e(r2_a)
mat colnames stat = model0
mat rownames stat = N r2a
mat_rapp model0 : coef stat
mat tabular = model0'

* with covariates
local cov sqage i.year##i.educ i.year##i.gender i.living_area
local xvars 
local k = 1
foreach v of local cov {
	di "model `k'"
    
	*make set of covariates
	local xvars `xvars' `v'
	
	*estimate fixed effect model
	xtreg log_total_g log_price log_pinc_all i.year age `xvars', fe vce(cluster pid)
	
	*matrix of regression result
	mat coef = r(table)["b".."pvalue","log_price"]
	mat colnames coef = model`k'
	mat stat = e(N) \ e(r2_a)
	mat colnames stat = model`k'
	mat rownames stat = N r2a
	mat_rapp model`k' : coef stat
	mat model`k' = model`k''
	
	*combined with previous results
	mat_rapp tabular : tabular model`k'

	local k = `++k'
}

xsvmat tabular, saving(_assets/EstimateElasticity.dta, replace) rownames(xvar) names(col)
```

```{stata EstimateElasticityIntensive, results = "hide", eval = FALSE}
label variable log_price "ln(giving price)"

* baseline
xtreg log_total_g log_price log_pinc_all i.year if i_ext_giving == 1, fe vce(cluster pid)
mat coef = r(table)["b".."pvalue", "log_price"]
mat colnames coef = model0
mat stat = e(N) \ e(r2_a)
mat colnames stat = model0
mat rownames stat = N r2a
mat_rapp model0 : coef stat
mat tabular = model0'

* with covariates
local cov sqage i.year##i.educ i.year##i.gender i.living_area
local xvars 
local k = 1
foreach v of local cov {
	di "model `k'"
    
	*make set of covariates
	local xvars `xvars' `v'
	
	*estimate fixed effect model
	xtreg log_total_g log_price log_pinc_all i.year age `xvars' if i_ext_giving == 1, /// 
		fe vce(cluster pid)
	
	*matrix of regression result
	mat coef = r(table)["b".."pvalue","log_price"]
	mat colnames coef = model`k'
	mat stat = e(N) \ e(r2_a)
	mat colnames stat = model`k'
	mat rownames stat = N r2a
	mat_rapp model`k' : coef stat
	mat model`k' = model`k''
	
	*combined with previous results
	mat_rapp tabular : tabular model`k'

	local k = `++k'
}


xsvmat tabular, saving(_assets/EstimateElasticityIntensive.dta, replace) rownames(xvar) names(col)
```

```{stata EstimateElasticityExtensive, results = "hide", eval = FALSE}
label variable log_price "ln(giving price)"

* baseline
xtreg i_ext_giving log_price log_pinc_all i.year, fe vce(cluster pid)
mat coef = r(table)["b".."pvalue", "log_price"]
mat colnames coef = model0
mat stat = e(N) \ e(r2_a)
mat colnames stat = model0
mat rownames stat = N r2a

* proportion of donors
summarize i_ext_giving
local mu = r(mean)

* implied elasticity
lincom log_price*(1/`mu')
mat elas = r(estimate) \ r(se) \ ttail(r(df), abs(r(estimate)/r(se)))*2
mat colnames elas = model0
mat rownames elas = e_b e_se e_pval

* baseline result
mat_rapp model0 : coef stat
mat_rapp model0 : model0 elas
mat tabular = model0'

* with covariates
local cov sqage i.year##i.educ i.year##i.gender i.living_area
local xvars 
local k = 1
foreach v of local cov {
	di "model `k'"
    
	*make set of covariates
	local xvars `xvars' `v'
	
	*estimate fixed effect model
	xtreg i_ext_giving log_price log_pinc_all i.year age `xvars', fe vce(cluster pid)
	
	*matrix of regression result
	mat coef = r(table)["b".."pvalue","log_price"]
	mat colnames coef = model`k'
	mat stat = e(N) \ e(r2_a)
	mat colnames stat = model`k'
	mat rownames stat = N r2a
	
	*proportion of donors
	summarize i_ext_giving
	local mu = r(mean)
	
	*implied elasticity
	lincom log_price*(1/`mu')
	mat elas = r(estimate) \ r(se) \ ttail(r(df), abs(r(estimate)/r(se)))*2
	mat colnames elas = model`k'
	mat rownames elas = e_b e_se e_pval
	
	*regression result
	mat_rapp model`k' : coef stat
	mat_rapp model`k' : model`k' elas
	mat model`k' = model`k''
	
	*combined with previous results
	mat_rapp tabular : tabular model`k'

	local k = `++k'
}

xsvmat tabular, saving(_assets/EstimateElasticityExtensive.dta, replace) rownames(xvar) names(col)
```


```{r shapeEstimateElasticity}
orgtab <- list(
	overall = read.dta13("_assets/EstimateElasticity.dta") %>% data.frame(),
	intensive = read.dta13("_assets/EstimateElasticityIntensive.dta") %>% data.frame(),
	extensive = read.dta13("_assets/EstimateElasticityExtensive.dta") %>% data.frame()
)

coeftab <- orgtab %>% 
	purrr::map(function(x)
		x %>% 
		mutate(
			b = case_when(
				pvalue <= 0.01 ~ sprintf("%1.3f***", b),
				pvalue <= 0.05 ~ sprintf("%1.3f**", b),
				pvalue <= 0.1 ~ sprintf("%1.3f*", b),
				TRUE ~ sprintf("%1.3f", b)
			),
			se = sprintf("(%1.3f)", se),
			N = sprintf("%1d", N)
		) %>% 
		select(xvar, b, se, N) %>% 
		pivot_longer(-xvar, values_to = "value", names_to = "stat") %>% 
		pivot_wider(values_from = "value", names_from = "xvar") %>% 
		select(-stat) %>% 
		cbind(xvar = c("ln(giving price)", "", "N"), .)
	) %>% 
	reduce(rbind)

elastab <- orgtab$extensive %>% 
	mutate(
		e_b = case_when(
			e_pval <= 0.01 ~ sprintf("%1.3f***", e_b),
			e_pval <= 0.05 ~ sprintf("%1.3f**", e_b),
			e_pval <= 0.1 ~ sprintf("%1.3f*", e_b),
			TRUE ~ sprintf("%1.3f", e_b)
		),
		e_se = sprintf("(%1.3f)", e_se)
	) %>% 
	select(xvar, e_b, e_se) %>% 
	pivot_longer(-xvar, values_to = "value", names_to = "stat") %>% 
	pivot_wider(values_from = "value", names_from = "xvar") %>% 
	select(-stat) %>% 
	cbind(xvar = c("Price elasticity at mean", ""), .)

result.tab <- rbind(coeftab[-9,], elastab) %>% rbind(coeftab[9,])

addline <- cbind(
	xvar = c("Time FE", "Age", "Year X Education", "Year X Gender", "Resident Area"),
	model0 = c("Y", rep("N", 4)),
	model1 = c(rep("Y", 2), rep("N", 3)),
	model2 = c(rep("Y", 3), rep("N", 2)),
	model3 = c(rep("Y", 4), rep("N", 1)),
	model4 = rep("Y", 5)
)

tab1 <- rbind(result.tab[1:2,], addline) %>% rbind(result.tab[3,])
tab2 <- rbind(result.tab[4:10,], addline) %>% rbind(result.tab[11,])
```

<!--- Slide
## Baseline Regressions: Result
We found the **price effect** of giving (1\% price increase leads to about 1.1\% giving decrease)
-->

```{r kableEstimateElasticityPart1, include = TRUE}
knitr::kable(
    tab1,
    format = "latex",
    caption = "Main Results",
    col.names = c("", "(1)", "(2)", "(3)", "(4)", "(5)"),
    row.names = FALSE,
    align = "lccccc", 
    booktabs = TRUE, escape = TRUE, linesep = ""
) %>% 
kable_styling() %>% 
footnote(general_title = "", general = "Notes: $^{*}$ $p < 0.1$, $^{**}$ $p < 0.05$, $^{***}$ $p < 0.01$. Standard errors are clustered at individual level. When controlling age, we alson include its squared term.", threeparttable = TRUE, escape = FALSE)
```


<!--- Slide
## Intensive Margin and Extensive Margin: Result
--->

```{r kableEstimateElasticityPart2, include = TRUE}
knitr::kable(
    tab2,
    format = "latex",
    caption = "Main Results: Intensive- and Extensive-Margin Elasticity",
    col.names = c("", "(1)", "(2)", "(3)", "(4)", "(5)"),
    row.names = FALSE,
    align = "lccccc", 
    booktabs = TRUE, escape = TRUE, linesep = ""
) %>% 
kable_styling() %>% 
pack_rows("Intensive-Margin Elasticity", 1, 3) %>% 
pack_rows("Extensive-Margin Elasticity", 4, 13) %>% 
footnote(general_title = "", general = "Notes: $^{*}$ $p < 0.1$, $^{**}$ $p < 0.05$, $^{***}$ $p < 0.01$. Standard errors are clustered at individual level. When controlling age, we alson include its squared term. The implied extensive-marign price elasticity is evaluated at the sample mean of $D_{ijt}$.", threeparttable = TRUE, escape = FALSE)
```


## Robustness Check

<!--- Slide
1. Income and donations are determined simultaneously
1. Effect of presidential transition on donation behavior
1. Last price elasticity
1. Self-selection of receiving tax benefit
1. Transitory and permanent elasticity
--->

<!--- Slide
## Robustness Check 1

First potential concern: Income and donations are determined simultaneously
    
- This causes both a change of giving price and a change of an amount of donations
- Gruber and Saez (2002) provided that we should use $\log(\text{Price}_{ijt}/\text{Price}_{ij(t-k)})$ as an insturment.
- We estimated the model (5) in the previous slide, using the panel IV model for $k = 1, 2, 3$.
	- Note that Alumnia (2020) took a strategy of $k$-difference model.
--->

```{stata PanelIVEstimateElasticity, results = "hide", eval = FALSE}
forvalues k = 1(1)3 {
    
	di "lag = `k'"
	
	* first stage 
    xtreg log_price diff`k'p log_pinc_all age i.living_area i.year##i.gender i.year##i.educ, ///
		fe vce(cluster pid)
	
	* result of first stage
	mat fstage = r(table)["b".."pvalue","diff`k'p"]
	mat fstage = fstage[1,1] \ fstage[3,1]^2
	mat colnames fstage = model`k'
	mat rownames fstage = ivcoef ivf
	
	* second stage
	xtivreg log_total_g log_pinc_all age i.living_area i.year##i.gender i.year##i.educ ///
		(log_price = diff`k'p), fe vce(cluster pid)
	
	* result of second stage
	mat coef = r(table)["b".."pvalue","log_price"]
	mat colnames coef = model`k'
	mat stat = e(N) \ e(r2_w)
	mat colnames stat = model`k'
	mat rownames stat = N r2w
	mat_rapp model`k' : coef stat
	
	* combined with first stage result
	mat_rapp model`k' : model`k' fstage
	mat model`k' = model`k''
}

mat_rapp tabular : model1 model2
mat_rapp tabular : tabular model3

xsvmat tabular, saving(_assets/PanelIVEstimateElasticity.dta, replace) rownames(xvar) names(col)
```

```{stata PanelIVEstimateElasticityExtensive, results = "hide", eval = FALSE}
forvalues k = 1(1)3 {
    
	di "lag = `k'"
	
	* first stage 
    xtreg log_price diff`k'p log_pinc_all age i.living_area i.year##i.gender i.year##i.educ, ///
		fe vce(cluster pid)
	
	* result of first stage
	mat fstage = r(table)["b".."pvalue","diff`k'p"]
	mat fstage = fstage[1,1] \ fstage[3,1]^2
	mat colnames fstage = model`k'
	mat rownames fstage = ivcoef ivf
	
	* second stage
	xtivreg i_ext_giving log_pinc_all age i.living_area i.year##i.gender i.year##i.educ ///
		(log_price = diff`k'p), fe vce(cluster pid)
	
	* result of second stage
	mat coef = r(table)["b".."pvalue","log_price"]
	mat colnames coef = model`k'
	mat stat = e(N) \ e(r2_w)
	mat colnames stat = model`k'
	mat rownames stat = N r2w
	
	*proportion of donors
	summarize i_ext_giving
	local mu = r(mean)
	
	*implied elasticity
	lincom log_price*(1/`mu')
	mat elas = r(estimate) \ r(se) \ (1 - normal(abs(r(estimate)/r(se))))*2
	mat colnames elas = model`k'
	mat rownames elas = e_b e_se e_pval
	
	* combined with results
	mat_rapp model`k' : coef stat
	mat_rapp model`k' : model`k' elas
	mat_rapp model`k' : model`k' fstage
	mat model`k' = model`k''

}

mat_rapp tabular : model1 model2
mat_rapp tabular : tabular model3

xsvmat tabular, saving(_assets/PanelIVEstimateElasticityExtensive.dta, replace) rownames(xvar) names(col)
```

```{stata PanelIVEstimateElasticityIntensive, results = "hide", eval = FALSE}
forvalues k = 1(1)3 {
    
	di "lag = `k'"
	
	* first stage 
    xtreg log_price diff`k'p log_pinc_all age i.living_area i.year##i.gender i.year##i.educ ///
		if i_ext_giving == 1, fe vce(cluster pid)
	
	* result of first stage
	mat fstage = r(table)["b".."pvalue","diff`k'p"]
	mat fstage = fstage[1,1] \ fstage[3,1]^2
	mat colnames fstage = model`k'
	mat rownames fstage = ivcoef ivf
	
	* second stage
	xtivreg log_total_g log_pinc_all age i.living_area i.year##i.gender i.year##i.educ ///
		(log_price = diff`k'p) if i_ext_giving == 1, fe vce(cluster pid)
	
	* result of second stage
	mat coef = r(table)["b".."pvalue","log_price"]
	mat colnames coef = model`k'
	mat stat = e(N) \ e(r2_w)
	mat colnames stat = model`k'
	mat rownames stat = N r2w
	mat_rapp model`k' : coef stat
	
	* combined with first stage result
	mat_rapp model`k' : model`k' fstage
	mat model`k' = model`k''
}

mat_rapp tabular : model1 model2
mat_rapp tabular : tabular model3

xsvmat tabular, saving(_assets/PanelIVEstimateElasticityIntensive.dta, replace) rownames(xvar) names(col)
```

<!--- Slide
## Robustness Check 1: Result
---> 

```{r shapePanelIVEstimateElasticity}
org.pivreg <- read.dta13("_assets/PanelIVEstimateElasticity.dta") %>% data.frame()

coef.pivreg <- org.pivreg %>% 
	select(xvar, b, se, pvalue) %>% 
	mutate(
		b = case_when(
			pvalue <= 0.01 ~ sprintf("%1.3f***", b),
			pvalue <= 0.05 ~ sprintf("%1.3f**", b),
			pvalue <= 0.1 ~ sprintf("%1.3f*", b),
			TRUE ~ sprintf("%1.3f", b)
		),
		se = sprintf("(%1.3f)", se)
	) %>% 
	select(xvar, b, se) %>% 
	pivot_longer(-xvar, values_to = "value", names_to = "stat") %>% 
	pivot_wider(values_from = "value", names_from = "xvar") %>% 
	select(-stat) %>% 
	cbind(xvar = c("ln(giving price)", ""), .)

stat.pivreg <- org.pivreg %>% 
	select(xvar, ivf, N) %>% 
	mutate(ivf = sprintf("%1.2f", ivf), N = sprintf("%1d", as.integer(N))) %>%
	pivot_longer(-xvar, values_to = "value", names_to = "stat") %>% 
	pivot_wider(values_from = "value", names_from = "xvar") %>% 
	select(-stat) %>% 
	cbind(xvar = c("F-stat of IV", "N"), .)

addline <- cbind(
	xvar = c("Individual FE", "Time FE", "Other Controls"),
	model1 = rep("Y", 3),
	model2 = rep("Y", 3),
	model3 = rep("Y", 3)
)

tab.pivreg <- rbind(coef.pivreg, addline) %>% rbind(stat.pivreg)
```

```{r kablePanelIVEstimateElasticity, include = TRUE}
knitr::kable(
    tab.pivreg,
    format = "latex",
    caption = "Panel IV Results",
    col.names = c("", "(1)", "(2)", "(3)"),
    row.names = FALSE,
    align = "lccc", 
    booktabs = TRUE, escape = TRUE, linesep = ""
) %>% 
kable_styling() %>% 
add_header_above(c("Lag $k$" = 1, "$k = 1$" = 1, "$k = 2$" = 1, "$k = 3$" = 1), escape = FALSE) %>%
footnote(general_title = "", general = "Notes: $^{*}$ $p < 0.1$, $^{**}$ $p < 0.05$, $^{***}$ $p < 0.01$. Standard errors are clustered at individual level. Other controls are age (its squared value), the interaction between year dummies and education dummies, the interaction between year dummies and gender dummies, and resident area. The instumental variable is $\\\\log(\\\\text{Price}_{ijt}/\\\\text{Price}_{ij(t-k)})$.", threeparttable = TRUE, escape = FALSE)
```

<!--- Slide
## Robustness Check 1: Intensive and Extensive Margin
--->

```{r shapePanelIVEstimateElasticityIntExt}
org.pivreg <- list(
	intensive = read.dta13("_assets/PanelIVEstimateElasticityIntensive.dta") %>% data.frame(),
	extensive = read.dta13("_assets/PanelIVEstimateElasticityExtensive.dta") %>% data.frame()
)

coef.pivreg <- org.pivreg %>% 
	purrr::map(function(x)
		x %>% 
		select(xvar, b, se, pvalue, ivf, N) %>% 
		mutate(
			b = case_when(
				pvalue <= 0.01 ~ sprintf("%1.4f***", b),
				pvalue <= 0.05 ~ sprintf("%1.4f**", b),
				pvalue <= 0.1 ~ sprintf("%1.4f*", b),
				TRUE ~ sprintf("%1.4f", b)
			),
			se = sprintf("(%1.4f)", se),
			ivf = sprintf("%1.2f", ivf), N = sprintf("%1d", as.integer(N))
		) %>% 
		select(xvar, b, se, ivf, N) %>% 
		pivot_longer(-xvar, values_to = "value", names_to = "stat") %>% 
		pivot_wider(values_from = "value", names_from = "xvar") %>% 
		select(-stat) %>% 
		cbind(xvar = c("ln(giving price)", "", "F-stat of IV", "N"), .)
	) %>% 
	reduce(rbind)

elas.pivreg <- org.pivreg$extensive %>% 
	mutate(
		e_b = case_when(
			e_pval <= 0.01 ~ sprintf("%1.3f***", e_b),
			e_pval <= 0.05 ~ sprintf("%1.3f**", e_b),
			e_pval <= 0.1 ~ sprintf("%1.3f*", e_b),
			TRUE ~ sprintf("%1.3f", e_b)
		),
		e_se = sprintf("(%1.3f)", e_se)
	) %>% 
	select(xvar, e_b, e_se) %>% 
	pivot_longer(-xvar, values_to = "value", names_to = "stat") %>% 
	pivot_wider(values_from = "value", names_from = "xvar") %>% 
	select(-stat) %>% 
	cbind(xvar = c("Price elasticity at mean", ""), .)

addline <- cbind(
	xvar = c("Individual FE", "Time FE", "Other Controls"),
	model1 = rep("Y", 3),
	model2 = rep("Y", 3),
	model3 = rep("Y", 3)
)

tab.pivreg <- rbind(coef.pivreg[1:6,], elas.pivreg) %>% 
	rbind(addline) %>% 
	rbind(coef.pivreg[7:8,])
```

```{r kablePanelIVEstimateElasticityIntExt, include = TRUE}
knitr::kable(
    tab.pivreg,
    format = "latex",
    caption = "Panel IV Results: Intensive- and Extensive-Margin Elasticity",
    col.names = c("", "(1)", "(2)", "(3)"),
    row.names = FALSE,
    align = "lccc", 
    booktabs = TRUE, escape = TRUE, linesep = ""
) %>% 
kable_styling() %>% 
add_header_above(c("Lag $k$" = 1, "$k = 1$" = 1, "$k = 2$" = 1, "$k = 3$" = 1), escape = FALSE) %>%
pack_rows("Intensive Margin", 1, 4) %>% 
pack_rows("Extensive Margin", 5, 13) %>% 
footnote(general_title = "", general = "Notes: $^{*}$ $p < 0.1$, $^{**}$ $p < 0.05$, $^{***}$ $p < 0.01$. Standard errors are clustered at individual level. Other controls are age (its squared value), the interaction between year dummies and education dummies, the interaction between year dummies and gender dummies, and resident area. The instumental variable is $\\\\log(\\\\text{Price}_{ijt}/\\\\text{Price}_{ij(t-k)})$. The implied extensive-marign price elasticity is evaluated at the sample mean of $D_{ijt}$.", threeparttable = TRUE, escape = FALSE)
```

<!--- Slide
## Robust Check 2

Second potential concern: The effect of presidential transition on donations 
    
- The presidential transition is one of our major ommited factor to charitable giving.
	- In May 2017, South Korea president changed from Park Geun-hye to Moon Jae-in. This presidential transition was due to the impeachment charge against Park Geun-hye. People became distrustful of her due to the shinking of MV Sewol (April 2014).
- To shed light on this concern, we used data in 2013 and 2014 (President was Park Geun-hye in both years), and estimated the model (5) in the previous slide, using the fixed effect model and the panel IV model for $k = 1, 2, 3$.
--->


```{stata ShortEstimateElasticity, results = "hide", eval = FALSE}
xtreg log_total_g log_price log_pinc_all age i.living_area i.year##i.gender i.year##i.educ ///
	if year == 2013 | year == 2014, fe vce(cluster pid)

mat coef = r(table)["b".."pvalue","log_price"]
mat colnames coef = model0
mat stat = e(N) \ e(r2_w)
mat colnames stat = model0
mat rownames stat = N r2w
mat_rapp model : coef stat
mat tabular = model'

forvalues k = 1(1)3 {
    
	di "lag = `k'"
	
	* first stage 
    xtreg log_price diff`k'p log_pinc_all age i.living_area i.year##i.gender i.year##i.educ ///
		if year == 2013 | year == 2014, fe vce(cluster pid)
	
	* result of first stage
	mat fstage = r(table)["b".."pvalue","diff`k'p"]
	mat fstage = fstage[1,1] \ fstage[3,1]^2
	mat colnames fstage = model`k'
	mat rownames fstage = ivcoef ivf
	
	* second stage
	xtivreg log_total_g log_pinc_all age i.living_area i.year##i.gender i.year##i.educ ///
		(log_price = diff`k'p) if year == 2013 | year == 2014, fe vce(cluster pid)
	
	* result of second stage
	mat coef = r(table)["b".."pvalue","log_price"]
	mat colnames coef = model`k'
	mat stat = e(N) \ e(r2_w)
	mat colnames stat = model`k'
	mat rownames stat = N r2w
	mat_rapp model`k' : coef stat
	
	* combined with first stage result
	mat_rapp model`k' : model`k' fstage
	mat model`k' = model`k''
	mat_rapp tabular : tabular model`k', miss(.)
}


mat list tabular

xsvmat tabular, saving(_assets/ShortEstimateElasticity.dta, replace) rownames(xvar) names(col)
```

```{stata ShortEstimateElasticityExtensive, results = "hide", eval = FALSE}
* baseline
xtreg i_ext_giving log_price log_pinc_all age i.living_area i.year##i.gender i.year##i.educ ///
	if year == 2013 | year == 2014, fe vce(cluster pid)

mat coef = r(table)["b".."pvalue","log_price"]
mat colnames coef = model0
mat stat = e(N) \ e(r2_w)
mat colnames stat = model0
mat rownames stat = N r2w

* proportion of donors
summarize i_ext_giving
local mu = r(mean)

* implied elasticity
lincom log_price*(1/`mu')
mat elas = r(estimate) \ r(se) \ ttail(r(df), abs(r(estimate)/r(se)))*2
mat colnames elas = model0
mat rownames elas = e_b e_se e_pval

mat_rapp model : coef elas
mat_rapp model : model stat
mat tabular = model'

forvalues k = 1(1)3 {
    
	di "lag = `k'"
	
	* first stage 
    xtreg log_price diff`k'p log_pinc_all age i.living_area i.year##i.gender i.year##i.educ ///
		if year == 2013 | year == 2014, fe vce(cluster pid)
	
	* result of first stage
	mat fstage = r(table)["b".."pvalue","diff`k'p"]
	mat fstage = fstage[1,1] \ fstage[3,1]^2
	mat colnames fstage = model`k'
	mat rownames fstage = ivcoef ivf
	
	* second stage
	xtivreg i_ext_giving log_pinc_all age i.living_area i.year##i.gender i.year##i.educ ///
		(log_price = diff`k'p) if year == 2013 | year == 2014, fe vce(cluster pid)
	
	* result of second stage
	mat coef = r(table)["b".."pvalue","log_price"]
	mat colnames coef = model`k'
	mat stat = e(N) \ e(r2_w)
	mat colnames stat = model`k'
	mat rownames stat = N r2w
	
	*proportion of donors
	summarize i_ext_giving
	local mu = r(mean)
	
	*implied elasticity
	lincom log_price*(1/`mu')
	mat elas = r(estimate) \ r(se) \ (1 - normal(abs(r(estimate)/r(se))))*2
	mat colnames elas = model`k'
	mat rownames elas = e_b e_se e_pval
	
	* combined with first stage result
	mat_rapp model`k' : coef elas
	mat_rapp model`k' : model`k' stat
	mat_rapp model`k' : model`k' fstage
	mat model`k' = model`k''
	mat_rapp tabular : tabular model`k', miss(.)
}


mat list tabular

xsvmat tabular, saving(_assets/ShortEstimateElasticityExtensive.dta, replace) rownames(xvar) names(col)
```

```{stata ShortEstimateElasticityIntensive, results = "hide", eval = FALSE}
* baseline
xtreg log_total_g log_price log_pinc_all age i.living_area i.year##i.gender i.year##i.educ ///
	if (year == 2013 | year == 2014) & i_ext_giving == 1, fe vce(cluster pid)

mat coef = r(table)["b".."pvalue","log_price"]
mat colnames coef = model0
mat stat = e(N) \ e(r2_w)
mat colnames stat = model0
mat rownames stat = N r2w
mat_rapp model : coef stat
mat tabular = model'

forvalues k = 1(1)3 {
    
	di "lag = `k'"
	
	* first stage 
    xtreg log_price diff`k'p log_pinc_all age i.living_area i.year##i.gender i.year##i.educ ///
		if (year == 2013 | year == 2014) & i_ext_giving == 1, fe vce(cluster pid)
	
	* result of first stage
	mat fstage = r(table)["b".."pvalue","diff`k'p"]
	mat fstage = fstage[1,1] \ fstage[3,1]^2
	mat colnames fstage = model`k'
	mat rownames fstage = ivcoef ivf
	
	* second stage
	xtivreg log_total_g log_pinc_all age i.living_area i.year##i.gender i.year##i.educ ///
		(log_price = diff`k'p) if (year == 2013 | year == 2014) & i_ext_giving == 1, fe vce(cluster pid)
	
	* result of second stage
	mat coef = r(table)["b".."pvalue","log_price"]
	mat colnames coef = model`k'
	mat stat = e(N) \ e(r2_w)
	mat colnames stat = model`k'
	mat rownames stat = N r2w
	mat_rapp model`k' : coef stat
	
	* combined with first stage result
	mat_rapp model`k' : model`k' fstage
	mat model`k' = model`k''
	mat_rapp tabular : tabular model`k', miss(.)
}


mat list tabular


xsvmat tabular, saving(_assets/ShortEstimateElasticityIntensive.dta, replace) rownames(xvar) names(col)
```

<!--- Slide
## Robustness Check 2: Result
--->

```{r shapeShortEstimateElasticity}
org.tab <- read.dta13("_assets/ShortEstimateElasticity.dta") %>% data.frame()

shape.tab <- org.tab %>% 
	select(xvar, b, se, pvalue, ivf, N) %>% 
	mutate(
		b = case_when(
			pvalue <= 0.01 ~ sprintf("%1.3f***", b),
			pvalue <= 0.05 ~ sprintf("%1.3f**", b),
			pvalue <= 0.1 ~ sprintf("%1.3f*", b),
			TRUE ~ sprintf("%1.3f", b)
		),
		se = sprintf("(%1.3f)", se),
		ivf = if_else(is.na(ivf), "", sprintf("%1.2f", ivf)), 
		N = sprintf("%1d", as.integer(N))
	) %>% 
	select(xvar, b, se, ivf, N) %>% 
	pivot_longer(-xvar, values_to = "value", names_to = "stat") %>% 
	pivot_wider(values_from = "value", names_from = "xvar") %>% 
	select(-stat) %>% 
	cbind(xvar = c("ln(giving price)", "", "F-stat of IV", "N"), .)

addline <- cbind(
	xvar = c("Individual FE", "Time FE", "Other Controls"),
	model0 = rep("Y", 3),
	model1 = rep("Y", 3),
	model2 = rep("Y", 3),
	model3 = rep("Y", 3)
)

tab <- rbind(shape.tab[1:2,], addline) %>% rbind(shape.tab[3:4,])
```

```{r kableShortEstimateElasticity, include=TRUE}
knitr::kable(
    tab,
    format = "latex",
    caption = "Results with 2013 and 2014 Data",
    col.names = c("", "(1)", "(2)", "(3)", "(4)"),
    row.names = FALSE,
    align = "lcccc", 
    booktabs = TRUE, escape = TRUE, linesep = ""
) %>% 
kable_styling() %>% 
add_header_above(c("Lag $k$" = 1, " " = 1, "$k = 1$" = 1, "$k = 2$" = 1, "$k = 3$" = 1), escape = FALSE) %>%
add_header_above(c("Model" = 1, "FE" = 1, "Panel IV" = 3)) %>% 
footnote(general_title = "", general = "Notes: $^{*}$ $p < 0.1$, $^{**}$ $p < 0.05$, $^{***}$ $p < 0.01$. Standard errors are clustered at individual level. Other controls are age (its squared value), the interaction between year dummies and education dummies, the interaction between year dummies and gender dummies, and resident area. The instumental variable is $\\\\log(\\\\text{Price}_{ijt}/\\\\text{Price}_{ij(t-k)})$.", threeparttable = TRUE, escape = FALSE)
```

<!--- Slide
## Robustness Check 2: Intensive and Extensive Margin
--->

```{r shapeShortEstimateElasticityIntExt}
org.tab <- list(
	intensive = read.dta13("_assets/ShortEstimateElasticityIntensive.dta") %>% data.frame(),
	extensive = read.dta13("_assets/ShortEstimateElasticityExtensive.dta") %>% data.frame()
)

coef.tab <- org.tab %>% 
	purrr::map(function(x)
		x %>% 
		select(xvar, b, se, pvalue, ivf, N) %>% 
		mutate(
			b = case_when(
				pvalue <= 0.01 ~ sprintf("%1.3f***", b),
				pvalue <= 0.05 ~ sprintf("%1.3f**", b),
				pvalue <= 0.1 ~ sprintf("%1.3f*", b),
				TRUE ~ sprintf("%1.3f", b)
			),
			se = sprintf("(%1.3f)", se),
			ivf = if_else(is.na(ivf), "", sprintf("%1.2f", ivf)), 
			N = sprintf("%1d", as.integer(N))
		) %>% 
		select(xvar, b, se, ivf, N) %>% 
		pivot_longer(-xvar, values_to = "value", names_to = "stat") %>% 
		pivot_wider(values_from = "value", names_from = "xvar") %>% 
		select(-stat) %>% 
		cbind(xvar = c("ln(giving price)", "", "F-stat of IV", "N"), .)
	) %>% 
	reduce(rbind)

elas.tab <- org.tab$extensive %>% 
	mutate(
		e_b = case_when(
			e_pval <= 0.01 ~ sprintf("%1.3f***", e_b),
			e_pval <= 0.05 ~ sprintf("%1.3f**", e_b),
			e_pval <= 0.1 ~ sprintf("%1.3f*", e_b),
			TRUE ~ sprintf("%1.3f", e_b)
		),
		e_se = sprintf("(%1.3f)", e_se)
	) %>% 
	select(xvar, e_b, e_se) %>% 
	pivot_longer(-xvar, values_to = "value", names_to = "stat") %>% 
	pivot_wider(values_from = "value", names_from = "xvar") %>% 
	select(-stat) %>% 
	cbind(xvar = c("Elasticity", ""), .)

result.tab <- rbind(coef.tab[1:6,], elas.tab) %>% rbind(coef.tab[7:8,])

addline <- cbind(
	xvar = c("Individual FE", "Time FE", "Other Controls"),
	model0 = rep("Y", 3),
	model1 = rep("Y", 3),
	model2 = rep("Y", 3),
	model3 = rep("Y", 3)
)

tab <- rbind(result.tab[1:8,], addline) %>% rbind(result.tab[9:10,])
```

```{r kableShortEstimateElasticityIntExt, include=TRUE}
knitr::kable(
    tab,
    format = "latex",
    caption = "Intensive- and Extensive-Margin Elasticity with 2013 and 2014 Data",
    col.names = c("", "(1)", "(2)", "(3)", "(4)"),
    row.names = FALSE,
    align = "lcccc", 
    booktabs = TRUE, escape = TRUE, linesep = ""
) %>% 
kable_styling() %>% 
pack_rows("Intensive Margin", 1, 4) %>% 
pack_rows("Extensive Margin", 5, 13) %>% 
add_header_above(c("Lag $k$" = 1, " " = 1, "$k = 1$" = 1, "$k = 2$" = 1, "$k = 3$" = 1), escape = FALSE) %>%
add_header_above(c("Model" = 1, "FE" = 1, "Panel IV with FE" = 3)) %>% 
footnote(general_title = "", general = "Notes: $^{*}$ $p < 0.1$, $^{**}$ $p < 0.05$, $^{***}$ $p < 0.01$. Standard errors are clustered at individual level. Other controls are age (its squared value), the interaction between year dummies and education dummies, the interaction between year dummies and gender dummies, and resident area. The instumental variable is $\\\\log(\\\\text{Price}_{ijt}/\\\\text{Price}_{ij(t-k)})$. The implied extensive-marign price elasticity is evaluated at the sample mean of $D_{ijt}$.", threeparttable = TRUE, escape = FALSE)
```

