```{r eval = FALSE}
# if you want to preview this file,
# 1. specify doctype: "draft" or "slide"
# 2. replace knitr format = "html"
library(here); knitr::opts_knit$set(root.dir = here())
doctype <- "draft"
options(knitr.kable.NA = " ", knitr.table.format = "html")
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo = FALSE,
  cache = FALSE,
  include = TRUE
)
```

```{asis, echo = doctype == "slide"}
## Introduction

- In many countries, tax relief for charitable giving are implemented.
- The elasticity of giving tax relief is known as a key parameter to evaluate the welfare implication (e.g. Saez, 2004).
    - Intuitively, if the elasticity is more than 1 in absolute value, $1 of tax relief make more than $1 of charitable giving.

- Many papers investigate the elasticity based on tax return data (e.g. Almunia et al., 2020, Auten et al., 2002, and so on).

## Introduction

- However, the tax return data record only the declared charitable giving.
  - First issue: Actual donations is different from declared donations.(Fack and Landais (2016); Gillitzer and Skov (2018))
  - We use panel survey data in South Korea to deal with this issue.
- Tax payers decide the amount of donation and whether to declare tax relief based on the size of tax incentive and declaration cost.
  - Second issue: Neglect of this declaration cost may bias the estimations of elasticity.
  - We use instrumental variable (IV) and control function approach for this issue.
- Based on DID as an identification strategy, we investigate the giving price elasticity of South Korea.

## Introduction

Result

1. Baseline results show that the giving price elasticity is less than -1.4 in terms of intensive margins and less than -1.7 in terms of extensive margins in Korea.
2. The estimated giving price elasticity for those who declare charitable giving is around -1.2$\sim$-1.6.

These estimates are more elastic than the estimates in the extant research, many of which show around -1. 

3. (Not in the paper) The estimated declaration cost of giving is KRW (\$).
4. (Not in the paper) Given our estimates, increasing the subsidy on charitable giving will be desirable in Korea.

```

```{asis, echo = doctype == "draft"}
# Introduction

In many countries, governments set a tax relief for charitable giving. This is because, if subsidizing charitable giving induces a large increase in donations, it is desirable for public good provision. As @Saez2004 shows, it is known that the price elasticity of charitable donations is a key parameter to evaluate the welfare implication. To evaluate the effect of tax relief, many empirical papers investigate the elasticity of charitable donations with respect to their tax price and find that the price elasticity is around -1 in terms of intensive margin, using the data from tax record [@Randolph1995; @Auten2002; @Fack2010; @Bakija2011; @Almunia2020].

However, there are two issues of the estimation as for the declaration of tax and charitable giving.
First issue is about the sample selection. Most of the analysis based on tax record only captures the effect for tax filers, while charitable donation may also be conducted by those who do not declare their tax. Thus, as some papers such as @Rehavi2013 and @Backus2019 point out, the estimation based on the tax return data will contain the sample selection bias.

Second issue is that the declaration for charitable giving (not the declaration of tax) is endogenous to the price of charitable giving. This is because the declaration for charitable giving is required to apply for the tax relief on charitable giving, and the effect of giving price on the amount of giving may represent the difference of declaration costs for charitable giving. Since this issue does not resolved even if the data of non tax filers are available, few studies take this issue into account on the estimation.[^struct_approach]

[^struct_approach]: @Almunia2020 considers the existence of declaration cost by using structual estimation, but they use tax return data, the usage of which will cause the sample selection bias.

Considering these issues, this paper investigates the price elasticity of giving. To derive the elasticity, this paper utilizes the South Korean (Korea hereafter) tax reform in 2014, from when the tax relief on charitable giving was conducted by tax credit, though tax deduction had been used before 2014.
The Korean tax reform in 2014 started to allow 15\% of the total amount of charitable giving as a tax credit for all taxpayers, which means that the giving price for 1 KRW donation is 0.85 KRW.[^dollar] Since the giving price was determined according to the marginal tax rate of progressive income tax before 2014, this tax reform reduced the giving price for low income taxpayers while it increased the price for high income tax payers. Since the variation of giving price can be considered to be exogenous for taxpayers, we exploit this reform and conduct the difference-in-difference (DID) analysis for identification. 

[^dollar]: 1 KRW is approximately 0.001 USD. In other words, 1 USD is about 1,000 KRW.

This paper contributes the literature about the charitable giving tax system for the following points. Firstly, to overcome the issue of tax declaration, this paper use the Korean survey panel data called the National Survey of Tax and Benefit (NaSTaB). Since NaSTaB data contains the data of charitable giving irrespective of declarations, the estimation should be free from the sample selection bias. Moreover, by using the survey data, we could consider the sample of low-income household, since the main part of tax return data is the data about wealthy people. This is particularly important for the estimation of the price elasticity in terms of the extensive margin since the propensity of donation by low-income households would be be less than high-income households.

Secondly, for the issue of charitable giving declaration, we focus on the fact that wage earners can easily declare tax relief in their company while self-employed workers have to declare tax relief via tax agency in Korea. By utilizing this difference of declaration costs between wage earners and self-employed workers as an instrument variable (IV), we estimate the price elasticity eliminating endogeneity between declaration for charitable giving and price of charitable giving. 

Thirdly, this paper examines the giving price elasticity in a non-Western country, where few papers deal with. While the giving behavior may be affected by the cultural matter such as the religious belief, the estimated price elasticities in this paper are less than the estimates in the extant research.

In addition, our paper considers several endogeneity issues which have been pointed out in the literature. As a result, we find that the estimated giving price elasticity is less than -1.4 in terms of intensive margins and less than -1.7 in terms of extensive margins. Since these estimates are much less than the estimates of extant research, this implies that the consideration of declaration cost may make a difference.

This paper consistsof six sections. Section 2 and 3 respectively explain the institutional background and data. Section 4 explains the estimation method. Section 5 deals with the analysis of price elasticity. Section 6 concludes.
```

```{asis, echo = doctype == "slide"}
## 2014 tax reform in South Korea

In Korea, income tax payers can receive tax relief for their charitable giving. 

- For the application of tax relief, tax payers have to submit a certificate for charitable giving.
- Wage earners pay their income tax by withholding tax and declare their charitable giving via their company.
    - Wage earners can submit the certificate at any time.
- Non wage earners, such as the self-employed, pay their income tax by tax-return and declare their charitable giving via the National Tax Service.
    - Non wage earners have to retain the certificate until they submit tax return.

## 2014 tax reform in South Korea

Our major price variation comes from the 2014 tax reform.

- Before 2014, tax deduction (所得控除) was used for tax relief on charitable giving.
    - I.e. the giving price depended on income level.
- After 2014, tax credit (税額控除) started to be used for tax relief on charitable giving.
    - The tax credit rate was determined as 15\%.
    - Giving price is 0.85, irrespective of income level.

## 2014 tax reform in South Korea

Model

- Consider private consumption ($x_{i}$) and charitable giving ($g_{i}$). 
- The budget constraint is 

$$x_{i} + g_{i} = y_{i} - R_iK- R_iT(y_{i}, g_{i})-(1-R_i)T(y_i)$$

where $y_{i}$ is pre-tax total income, $R_{i}$ is a dummy of declaration of tax relief and $T(y_i)$ and $T(y_{i}, g_{i})$ are respectively the amount of tax when $i$ does not declare tax relief and when $i$ declares tax relief.

- Tax payers declare their charitable giving if its benefit exceeds its cost.
\begin{align}
R_i=\begin{cases}
1 \text{ if }T(y_i, g_i) - T(y_i)>K\\
0 \text{ if }T(y_i, g_i) - T(y_i)\le K.\notag
\end{cases}
\end{align}

## 2014 tax reform in South Korea


**Tax deduction system (until 2013)** 
$$T(y_{i}, g_{i}) = T(y_{i} - g_{i})$$

- In 2012 and 2013, the marginal tax rate was the same, though it was different from ones before 2011.
- The logged relative giving price is $R_{i}\ln(1 - T'(y_{i} - g_{i}))$.

**Tax credit system (from 2014)**
$$T(y_{i}, g_{i}) = T(y_{i}) - R_{i} m g_{i}$$

- $m$ is tax credit rate and is $m = 0.15$.
- The logged relative giving price is $R_{i}\ln(1 - 0.15) = R_{i}\ln 0.85$.

Note: The logged relative giving price for the non-declared is $\ln1 =0$.
```

```{asis, echo = doctype == "draft"}
# Institutional background and Sources of endogeneity

In this section, we describe the endogeneity issue and the income tax relief for charitable giving in Korea and used dataset.

## Declaration of tax relief and giving price

In the South Korea, the tax policy about charitable giving drastically changed in 2014. Before then, tax relief of charitable giving was provided by tax deduction while, from 2014, tax relief by tax credit was introduced instead of tax deduction. 

Consider that a household has a choice between private consumption ($x_i$) and charitable giving ($g_i$). Let $y_i$ be pre-tax total income.
Then, the budget constraint can be shown as
\begin{align}
    x_i + g_i = y_i − R_iK - R_iT(y_i, g_i) - (1-R_i)T(y_i)\notag.
\end{align}
$T$ is tax amount which depends on the pre-tax income and charitable giving.
$R_i$ is the dummy which takes 1 if $i$ declares the tax relief and 0 otherwise. $K$ is a cost for the declaration of charitable giving, which may not be monetary cost but is converted to pecuniary terms. 

Tax payers declare their charitable giving if its benefit exceeds its cost, which means
\begin{align}
R_i=\begin{cases}
1 \text{ if }T(y_i, g_i) - T(y_i)>K\\
0 \text{ if }T(y_i, g_i) - T(y_i)\le K.\label{R}
\end{cases}
\end{align}

This means that the decision of declaration depends on $y_i$, $g_i$ and $K$.

Under the tax deduction, the amount of tax is
\begin{align}
    T(y_i, g_i) = T(y_i-g_i),\text{ where }T_i'(\cdot)>0, T_i''(\cdot)>0
\end{align}
while the amount of tax under the tax credit system is
\begin{align}
  T(y_i,g_i)=T(y_i)-mg_i,\text{ where }T_i'(\cdot)>0, T_i''(\cdot)>0.
\end{align}

Using the total differentiation of the budget constraint by $x_i$ and $g_i$ (i.e. $dx_i=(1-R_iT_g(y_i,g_i))dg_i$), the marginal giving price compared to private consumption is $1-R_iT'(y_i-g_i)$ in the tax deduction regime and is $1-R_im$ in the tax credit regime. Hereafter, we use $p$ and $q$ to show the giving price compared to private consumption and the amount of tax relief for each charitable giving, respectively (i.e. $p=1-R_iq$ and $q=T_g(y_i, g_i)$.). The government can change $q$ in the tax reform as the next subsection explains.


```

```{r tabTaxRate, include=TRUE, eval = doctype == "draft"}
tab <- data.frame(
    inc = c(
        "(A) ~ 1200", "(B) 1200 ~ 4600", "(C) 4600 ~ 8800", "(D) 8800 ~ 15000",
        "(E) 15000 ~ 30000", "(F) 30000 ~ 50000", "(G) 50000 ~"),
    Y08 = c("8%", "17%", "26%", rep("35%", 4)),
    Y09 = c("6%", "16%", "25%", rep("35%", 4)),
    Y1011 = c("6%", "15%", "24%", rep("35%", 4)),
    Y1213 = c("6%", "15%", "24%", rep("35%", 2), rep("38%", 2)),
    Y1416 = c("6%", "15%", "24%", "35%", rep("38%", 3)),
    Y17 = c("6%", "15%", "24%", rep("35%", 2), "38%", "40%"),
    Y18 = c("6%", "15%", "24%", "35%", "38%", "40%", "42%")
)

knitr::kable(
    tab,
    caption = "Marginal Income Tax Rate",
    col.names = c(
      "Income/Year", "2008", "2009", "2010 ~ 2011",
      "2012 ~ 2013", "2014 ~ 2016", "2017", "2018"
    ),
    row.names = FALSE,
    align = "lccccccc",
    booktabs = TRUE, escape = TRUE, linesep = ""
) %>%
kable_styling(font_size = 9) %>%
collapse_rows(columns = 2:8, valign = "middle", latex_hline = "full") %>%
footnote(general_title = "", general = "Notes: Marginal income tax rates applied from 2008 to 2018 are summarized. The income level is shown in terms of 10,000 KRW, which is approximately 10 United States dollars (USD) at an exchange rate of 1,000 KRW to one USD.", threeparttable = TRUE, escape = FALSE)
```

```{asis, echo = doctype == "draft"}
## Korean tax reform in 2014 {#taxreform}

Korean tax system offers a tax relief for charitable giving in income tax. All tax payers have to declare their donation and submit the certificate of charitable giving to receive tax relief, while the taxation method and the way of tax declaration are different for wage earners and self-employed workers. Wage earners pay income tax by withholding tax and declare tax relief for charitable giving via their company. Self-employed workers pay income tax by tax-return and declare tax relief when they submit tax return to the National Tax Service. Therefore, there is a difference of declaration cost of tax relief since self-employed workers have to retain the certificate until they submit tax return although wage earners can submit the certificate at any time.   

Before 2014, tax reilef on charitable giving is conducted by tax deduction on income tax in Korea. since marginal income tax rate was determined as Table 1, tax payer facing the highest marginal income tax rate, 38\%, can enjoy the giving price 0.62 KRW for each 1 KRW of donation. In 2014, aiming at the relaxation of regressivity of giving price, the Korean government reformed tax system, where the tax credit was introduced instead of tax deduction. Since then, 15\% of the total amount of charitable giving has been allowed as a tax credit, which means that the giving price from 2014 is 0.85 KRW for each 1 KRW of donation irrelevant to the income level.

Summarizing this, compared to tax credit system, the high income household, whose (average) income tax rate is more than 15\%, get benefit from charitable giving under the tax deduction system. However, middle or low income households would enjoy tax relief in tax credit system more than tax deduction system. We exploit this policy change as an identification strategy.

```


```{asis, echo = doctype == "draft"}
## Source of endogeneity

In the literature of giving tax relief, many papers care various issues on the estimation. Most of papers care the endogeneity issues which happens to the tax deduction system. For example, most of them utilize the marginal tax rate when the first dollar of charitable giving is conducted, called "first giving price", to deal with the endogenous giving price.

However, compared to the issues about the tax system, the treatment for the other issues varies in each paper. In particular, many paper do not consider the existence of declaration cost of charitable giving.

From (\ref{R}), we can see that the giving price does not changed by tax relief without the declaration for charitable giving (i.e. $\partial g/\partial q=0$ for non-declared charitable giving.). Therefore, we have to distinguish between declared and non-declared charitable giving.[^tax_recode]

[^tax_recode]: Note that this is impossible when tax return data is used since it only records declared charitable giving.

In addition, considering that those who face lower declaration cost are likely to declare their giving and enjoy tax relief, the difference of giving behavior may come not from the difference of the amount of tax relief $q$, which is the main identification source, but from the difference of declaration cost $K_i$, via $R_i$.
This problem is not resolved even if survey data is used instead of tax return data.[^declare_cost]

[^declare_cost]: This is because the usage of survey data does not mean that it considers the existence of the declaration cost of each observation.

The usage of tax return data will amplify this problem. If charitable giving is declared, the marginal income tax rate is $T'(y_i-g_i)$ under the tax deduction system and $T'(y_i)$ under the tax credit system, while, if charitable giving is not declared, the marginal income tax rate is $T'(y_i)$ under the both system. Therefore, for given $g_i$, the difference of the marginal income tax rate between whether the declared or not is
\begin{align}
T'(y_i)-T_y(y_i,g_i)=\begin{cases}
	T'(y_i)-T'(y_i-g_i)\ge0 &\text{ if tax deduction}.\\
	mg_i>0 &\text{ if tax credit}.
\end{cases}
\end{align}

Considering $T''(\cdot)>0$, this implies that, when the higher marginal tax rate is applied (i.e. the higher $y_i$ is), the declaration of tax relief mitigate tax payment and $R_i=1$ is likely to be hold for given $x_i$ and $g_i$ under the tax deduction system. Thus, the high income earners tend to declare charitable giving. Since the tax return data tend to represent the data of high income earners, the issue of declaration may be serious. Moreover, because the tax return data does not contain the information of non-declared charitable giving, the estimated elasticity should be different from the population elasticity, which @Saez2004 shows as a key parameter to obtain implications for welfare.

To overcome the issue about the existence of declaration cost, we use the different declaration cost for charitable giving between self-employed workers and wage earners as an identification source. Since the declaration cost for the self-employed is higher than wage earners in Korea, we use it as an IV in the estimation. 
```

```{asis, echo = doctype == "slide"}
## Source of endogeneity

1. Usage of tax return data only captures declared charitable giving.
    - If the charitable giving is not declared, tax relief has a little effect.
    - Some papers use survey data to deal with this problem (e.g. Rehavi and Shack, 2013).
    - \textbf{Following them, we use survey panel data of Korea.}
2. If the declaration cost is ignored, the estimation should be biased.
    - The giving price depends not only on marginal tax rate and tax credit rate, but also on the declaration behavior.
    - As far as we know, only Almunia et al. (2020) deal with this problem, though they used tax return data.
    - \textbf{We use the different declaration cost btw wage earners and the others as an instrumental variable (IV).}
    
```