```{r eval = FALSE}
# if you want to preview this file,
# 1. specify doctype: "draft" or "slide"
# 2. replace knitr format = "html"
library(here); knitr::opts_knit$set(root.dir = here())
doctype <- "draft"
options(knitr.kable.NA = " ", knitr.table.format = "html")
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo = FALSE,
  cache = FALSE,
  include = TRUE
)
```

# Data

```{r library, include = FALSE}
library(xfun)
xfun::pkg_attach2(c("readstata13", "tidyverse", "rlist"))
xfun::pkg_attach2(c("plm", "lmtest", "sandwich"))
xfun::pkg_attach2("kableExtra")

lapply(Sys.glob(file.path("script/R/functions", "*.r")), source)

```
```{r ReadData, include =FALSE}
df <- readr::read_csv(
  "data/shaped2.csv",
  col_types = cols(
    ext_credit_giving = col_double(),
    krw_credit_giving = col_double(),
    trust_politician = col_double(),
    political_pref = col_double(),
    addtax = col_double(),
    avg_welfare_tax = col_double(),
    opt_welfare_tax = col_double(),
    now_balance = col_double(),
    ideal_balance = col_double()
  )
)
```

```{asis, echo = doctype == "slide"}
## National Survey of Tax and Benefit (NaSTaB)

- An annual financial panel survey implemented by The Korea Institute of Taxation and Finance implements to study the tax burden of households and the benefits that households receive from government.
- The subjects of this survey are general household and household members living in 15 cities and provinces nationwide.
- This survey is based on a face-to-face interview. If it is difficult for investigators to meet subjects, another family member answers on behalf of him.
- We use data from 2012 to 2018 **since the items of the value survey which we focused is not available before 2012 (ここは違いま???)**. In addition, we exclude the subject of the sample, whose age is under 23, since they are not likely to have income or asset.

## Summary Statistics

```

```{asis, echo = doctype == "draft"}
The National Survey of Tax and Benefit (hereafter, NaSTab) is an annual financial panel survey 
implemented by The Korea Institute of Taxation and Finance 
to study the tax burden of households and the benefits that households receive from the government. 
The subjects of this survey are general households and household members living in 15 cities and provinces nationwide. 
This survey is based on a face-to-face interview. [^interview]
The NaSTaB data is constructed as the subjects represent the population of Korean society.
This enables us to derive giving price elasticity of population without re-weighting samples, which is used in the extant research. 
Moreover, note that subjects are not limited to the taxpayer or income earner reflecting the population.

In the analysis, we use data from 2013 to 2017 since we focus on the 2014 tax reform. This is because, as Table \@ref(tab:tabTaxRate) shows, the giving price before 2014 was changed frequently and incorporating the data before 2012 captures the effects of another tax reform than the reform in 2014. Note that, since tax credit was introduced after 2014 and the credit rate was unchanged since 2014, the giving price does not depend on the income tax rate after 2014.
In addition, we exclude the subject of the sample, whose age is under 23, since they are not likely to have income or assets.

[^interview]: If it is difficult for investigators to meet subjects, another family member answers on behalf of him.
```

```{r SummaryCovariate}
x <- c(
  "i_total_giving", "i_ext_giving",
  "lincome", "price", "ext_benefit_tl",
  # "now_balance", "ideal_balance",
  "age", "gender", "employee",
  "univ", "highschool", "juniorhigh"
)

df %>%
  sumvars(x, stat = c("N", "mean", "sd", "min", "median", "max")) %>%
  mutate(
    vars = recode(
      vars,
      "lincome" = "Annual taxable labor income (unit: 10,000KRW)",
      "price" = "First giving price",
      "ext_benefit_tl" = "Dummy of declaration of a tax relief",
      "i_total_giving" = "Annual charitable giving (unit: 10,000KRW)",
      "i_ext_giving" = "Dummy of Donation > 0",
      "age" = "Age",
      "gender" = "Female dummy",
      "employee" = "Employee dummy",
      "univ" = "University graduate",
      "highschool" = "High school graduate dummy",
      "juniorhigh" = "Junior high school graduate dummy"
    )
  ) %>%
  kable(
    caption = "Descriptive Statistics",
    col.names = c("", "N", "Mean", "Std.Dev.", "Min", "Median", "Max"),
    align = "lcccccc", digits = 2,
    booktabs = TRUE, escape = TRUE, linesep = ""
  ) %>%
  kable_styling(font_size = 9) %>%
  pack_rows("Charitable Donations", 1, 2) %>%
  pack_rows("Income, giving price, and tax report", 3, 5) %>%
  pack_rows("Individual Characteristics", 6, 11)
```

```{asis, echo = doctype == "slide"}

## Charitable Giving

```

```{asis, echo = doctype == "draft"}
Table \@ref(tab:SummaryCovariate) shows summary statistics of our data.[^Question]
The first panel of this table shows variables about charitable giving.
The NaSTaB asks respondents to answer the amount of donation last year.
This is the first outcome variables.
Using this, we make a dummy taking 1 if respondent donated last year.
This is the second outcome variables to estimate the price effect on the decision of donations.
Table \@ref(tab:SummaryCovariate) shows that 
the average amount of donation is almost 300,000 KRW (300 USD),
and the proportion of donors is roughly 20\%.
Figure \@ref(fig:SummaryOutcome) shows the time-series of two variables.
The blue line shows the average amount of donation among donors.
In each year, its value is nearly 1.5 million KRW (1,500 USD),
which is 7\% of average annual taxable income.
The gray bar shows the proportion of donors.
After the tax reform, the proportion of donors decreases by 2 percentage points.
After that, the proportion of donors is greter than 20\%.

[^Question]: Respondents answer the amount of donation for seven specific purposes last year. Seven specific purposes are policitical parties, educational organizations, social welfare organizations, organizations for culutre and art, religious groups, charity activies organaized by religious group, other purposes. We sum up the amount of donations, and consider it as the annual charitable giving.
```

```{r SummaryOutcome, out.width="100%", fig.cap="Proportion of Donors and Average Donations among Donors. Notes: The left and right axises respectively mesure proportion of donors and the average amount donations among donors. Authors made this graph based on NasTaB data."}
avgext <- df %>%
  group_by(year) %>%
  summarize_at(vars(i_ext_giving), list(mu = ~mean(., na.rm = TRUE)))

avgint <- df %>%
  filter(i_ext_giving == 1) %>%
  group_by(year) %>%
  summarize_at(vars(i_total_giving), list(mu = ~mean(., na.rm = TRUE)))

ggplot(avgext, aes(x = year, y = mu)) +
  geom_bar(aes(fill = "Proportion of Donors"), stat = "identity", color = "black") +
  geom_point(
    data = avgint, aes(x = year, y = mu / 1000, color = "Average amount of Donations among Donors"),
    size = 2
  ) +
  geom_line(
    data = avgint, aes(x = year, y = mu / 1000, color = "Average amount of Donations among Donors"),
    size = 1

  ) +
  geom_hline(aes(yintercept = 0)) +
  geom_vline(aes(xintercept = 2013.5), color = "red", linetype = 2, size = 1) +
  scale_fill_manual(NULL, values = "grey80") +
  scale_color_manual(NULL, values = "blue") +
  scale_y_continuous(sec.axis = sec_axis(
    ~. * 1000,
    name = "Average amount of Donations among Donors"
  )) +
  scale_x_continuous(breaks = seq(2012, 2018, 1)) +
  labs(x = "Year", y = "Proportion of Donors") +
  ggtemp()
```

```{asis, echo = doctype == "slide"}
## Income and Giving Price

- Figure \@ref(fig:SummaryPriceChange) shows the giving price after 2012 and income distribution in 2013.
	- Blue line shows the giving price in 2012 and 2013, which depends on income
	- Red dashed line shows the giving price after 2014, which is not a function of income.
- We can make three groups in terms of the benefit from the 2014 tax reform.
	- Benefit group: Final taxable income is less than $1200 \times 10^4$KRW.
	- Neutral group: Final taxable income lies between $(1200 \times 10^4, 4600 \times 10^4)$.
	- Loss group: Final taxable income is more than $4600 \times 10^4$KRW.

## Giving Price and Income Distribution (Cont'd)
```

```{asis, echo = doctype == "draft"}
The second panel of Table \@ref(tab:SummaryCovariate) shows variables about income, tax report, and the giving price.
NaSTaB asks respondents to answer the annual labor income last year.
In our sample, the average annual taxable income is 18.76 million KRW (18,760 USD).
According to the National Tax Statistical Yearbook published by Korean National Tax Service,
the average annual taxable income is 32.77 million (32,770 USD) from 2012 to 2018
for employees who submitted the tax return.
Since our sample includes subjects with no labor income, such as housewives,
our sample mean of income is lower than the average income calculated by the public organizations.
In Figure \@ref(fig:SummaryPriceChange),
the gray bars show the distribution of annual taxable income in 2013.
The income distribution is right-skewed.

Using this variable, we construct the giving price under the tax deduction system (2012 and 2013).[^fprice]
After the tax reform (after 2014), the giving price is 0.85 regardless of labor income. 
as we explained in the section \@ref(institutional-background).
In Figure \@ref(fig:SummaryPriceChange),
the blue line shows the giving price in 2012 and 2013,
while the red dashed line shows the giving price after 2014.
From this figure, 
those whose annual income is less than 120,000,000 KRW (120,000 USD) in 2013 could receive benefit from the 2014 tax reform
because the tax reform decreases the giving price.
On the other hand,
those whose annual income is greater than 460,000,000 KRW (460,000 USD) in 2013 had a loss by the 2014 tax reform 
since the tax reform increases the giving price.

[^fprice]: The giving price shown in Table \@ref(tab:SummaryCovariate) is the *first* giving price. The giving price can be manipulated by an amount of donation. To avoid this endogeneity, we use the giving price where the amount of donation is zero. We will discuss this issue in the next section.

The NaSTaB also asks respondents to answer whether they declared a tax relief of giving.
Although this variable is unique, the sample size is relatively small due to unanswering.
This survey investigates separately for the case of *total* income (for example, business income, dividend income, rental income) 
and the case of *labor* income.
We make a dummy taking one if respondents applied for a total income deduction of giving
or a labor income deduction of giving.
Table \@ref(tab:SummaryCovariate) shows the proportion of declaration is about 48\%.
```

```{r SummaryPriceChange, out.width="90%", fig.cap="Income Distribution and Giving Price in 2013"}
df %>%
  filter(year == 2013) %>%
  dplyr::select(lincome, price) %>%
  ggplot(aes(x = lincome)) +
  geom_histogram(
    aes(y = ..count.. / sum(..count..), fill = "Relative frequency"),
    color = "black"
  ) +
  geom_step(
    aes(y = price * 0.5, color = "Giving Price in 2013"),
    size = 1
  ) +
  geom_hline(
    aes(yintercept = (1 - 0.15) * 0.5),
    color = "red", linetype = 2, size = 1
  ) +
  scale_color_manual(NULL, values = "blue") +
  scale_fill_manual(NULL, values = "grey80") +
  scale_y_continuous(
    breaks = seq(0, 0.5, 0.125),
    sec.axis = sec_axis(~ . / 0.5, name = "Giving price")
  ) +
  scale_x_continuous(breaks = c(1200, 4600, 8800, 30000)) +
  labs(x = "Annual taxable income (10,000KRW)", y = "Relative frequency") +
  ggtemp()
```

