```{r eval = FALSE}
# if you want to preview this file,
# 1. specify doctype: "draft" or "slide"
# 2. replace knitr format = "html"
doctype <- "draft"
options(
  knitr.kable.NA = " ",
  knitr.table.format = "html"
)
```

# Price and Income Elasticitiy: ITT Approach

```{r }
library(xfun)
xfun::pkg_attach2(c("tidyverse", "rlist"))
xfun::pkg_attach2(c("plm", "lmtest", "fixest", "sandwich", "lfe", "Formula"))
xfun::pkg_attach2("kableExtra")

invisible(lapply(Sys.glob(file.path("script/R/functions", "*.r")), source))
```

```{r }
df <- readr::read_csv(
  "data/shaped2.csv",
  col_types = cols(
    ext_credit_giving = col_double(),
    krw_credit_giving = col_double(),
    trust_politician = col_double(),
    political_pref = col_double(),
    addtax = col_double(),
    avg_welfare_tax = col_double(),
    opt_welfare_tax = col_double(),
    now_balance = col_double(),
    ideal_balance = col_double()
  )
)
```

```{asis, echo = doctype == "draft"}
In this section, as a benchmark, we first report the price effect on donations, using the ITT approach.
Reducing the relative price of giving through a tax deduction includes self-selection.
The ITT approach sees respondents who did not apply for a tax deduction in a specific year as those who applied for it.
In our main results, we report estimation results of price effect, using the first price method.
As robustness, we report the last price effect using the first price as an instrumental variable,
the first price effect with short-period panel to focus on the 2014 tax reform more precisely,
and the $k$-th difference model to avoid the problem that income affects the giving price.
```

## Results

```{r }
xlist <- list(
  reg1 = ~ log_price + log_pinc_all,
  reg2 = ~ log_price + log_pinc_all + age + sqage,
  reg3 = ~ log_price + log_pinc_all + age + sqage + factor(year):factor(educ),
  reg4 = ~ log_price + log_pinc_all + age + sqage + factor(year):factor(educ) +
    factor(year):factor(gender),
  reg5 = ~ log_price + log_pinc_all + age + sqage + factor(year):factor(educ) +
    factor(year):factor(gender) + factor(year):factor(living_area)
)

xlist_tab <- tribble(
  ~vars, ~stat, ~reg1, ~reg2, ~reg3, ~reg4, ~reg5,
  "Individual FE", "vars", "Y", "Y", "Y", "Y", "Y",
  "Time FE", "vars", "Y", "Y", "Y", "Y", "Y",
  "Age", "vars", "N", "Y", "Y", "Y", "Y",
  "Year x Education", "vars", "N", "N", "Y", "Y", "Y",
  "Year x Gender", "vars", "N", "N", "N", "Y", "Y",
  "Year x Resident Area", "vars", "N", "N", "N", "N", "Y"
)
```


```{asis, echo = doctype == "slide"}
We found the **price effect** of giving (1\% price increase leads to about 1.1\% giving decrease),
and the **income effect** of giving(1\% income increase leads to about 5\% giving increase).
```

```{asis, echo = doctype == "draft"}
Before the estimation of giving price elasticities for intensive and extensive margin,
we estimate the elasticity without distinguishing them. 
We call this elasticity overall elasticity.
Table \@ref(tab:MainOverall) shows estimation results of overall elasticity.
Column (1) is the baseline estimation, which includes individual and time fixed effects.
The price elasticity is roughly -1, which is statistically significantly different from zero.
This implies that a 1\% increase of giving price raises charitable giving by 1\%.
This result is in line with previous researches which focuses on Western countries.
The income elasticity is about 5.3, which is statistically significantly different from zero.
This implies that a 1\% increase of annual income raises charitable giving by 5.3\%.
The remaining four columns control for events that affect subjects with specific characteristics at the same time.
As a result, the price elasticity is more elastic than the baseline result.
The price elasticity lies between -1.3 and -1.1.
On the other hand, the income elasticity is less elastic than the baseline result.
The income elasticity lies between -5.1 and -4.9.
```

```{r MainOverall}
overall <- xlist %>%
  purrr::map(~ fit_fixest(
    y = log_total_g ~ ., x = .,
    fixef = ~ year + pid, cluster = ~pid,
    data = df
  ))

overall %>%
  regtab_fixest(
    keep_coef = c("log_price", "log_pinc_all"),
    label_coef = list(
      "log_price" = "ln(giving price)",
      "log_pinc_all" = "ln(annual taxable income)"
    )
  ) %>%
  regtab_addline(list(xlist_tab)) %>%
  mutate(vars = if_else(stat == "se", "", vars)) %>%
  dplyr::select(-stat) %>%
  kable(
    caption = "Overall Elasticity of First Price",
    col.names = c("", sprintf("(%1d)", seq_len(length(xlist)))),
    align = "lccccc",
    booktabs = TRUE, escape = TRUE, linesep = ""
  ) %>%
  kable_styling(font_size = 7) %>%
  footnote(
    general_title = "",
    general = "Notes: $^{*}$ $p < 0.1$, $^{**}$ $p < 0.05$, $^{***}$ $p < 0.01$. Standard errors are clustered at individual level. When controlling age, we alson include its squared term.",
    threeparttable = TRUE,
    escape = FALSE
  )
```

```{asis, echo = doctype == "slide"}
## Intensive and Extensive Margin: Estimation Results

The intensive-margin price elasticity is -0.5 ~ -1\%. 
```

```{asis, echo = doctype == "draft"}
Table \@ref(tab:MainIntensive) shows the intensive-margin elasticities.
Compared to the overall elasticity, the price and income elasticities are less elastic.
Controlling individual and time fixed effects, 
the price and income elasticity are about -0.6 and about 2, respectively,
which are statistically significantly different from zero (See column (1)).
Moreover, when we include the interaction term between individual characteristics and year dummies,
these values vary.
The price elasticity lies between -1.1 and -0.8,
and the income elasticity lies between 1.4 and 1.6.
Anyway, we conclude that the amount of donations is insensitive to the giving price among donors.
```

```{r MainIntensive}
intensive <- xlist %>%
  purrr::map(~ fit_fixest(
    y = log_total_g ~ ., x = .,
    fixef = ~ year + pid, cluster = ~pid,
    data = subset(df, i_ext_giving == 1)
  ))

intensive %>%
  regtab_fixest(
    keep_coef = c("log_price", "log_pinc_all"),
    label_coef = list(
      "log_price" = "ln(giving price)",
      "log_pinc_all" = "ln(annual taxable income)"
    )
  ) %>%
  regtab_addline(list(xlist_tab)) %>%
  mutate(vars = if_else(stat == "se", "", vars)) %>%
  dplyr::select(-stat) %>%
  kable(
    caption = "Intensive-Margin Elasticity of First Price",
    col.names = c("", sprintf("(%1d)", seq_len(length(xlist)))),
    align = "lccccc",
    booktabs = TRUE, escape = TRUE, linesep = ""
  ) %>%
  kable_styling(font_size = 7) %>%
  footnote(
    general_title = "",
    general = "Notes: $^{*}$ $p < 0.1$, $^{**}$ $p < 0.05$, $^{***}$ $p < 0.01$. Standard errors are clustered at individual level. When controlling age, we alson include its squared term.",
    threeparttable = TRUE,
    escape = FALSE
  )
```

```{asis, echo = doctype == "slide"}
## Intensive and Extensive Margin: Estimation Results

The extensive-margin price elasticity is -1.2 ~ -1.4\%. 
```

```{asis, echo = doctype == "draft"}
Table \@ref(tab:MainExtensive) shows the extensive-margin elasticities.
As a result of overall elasticities and the intensive-margin elasticities,
we expect that the extensive-margin price and income elasticity is more elastic than the overall elasticities.
In column (1), the coefficient of logged giving price and logged annual income are -0.257 and 1.175 respectively,
which are statistically significantly different from zero.
Due to the linear probability model,
the coefficient of logged giving price and logged income represents the lower bound of price and income elasticity, respectively.
When we evaluate the price elasticity at the sample mean of $D_{it}$,
the implied price elasticity is -1.264, which is slightly more elastic than the overall one.
Also, we evaluate the income elasticity at the sample mean of the outcome.
The implied income elasticity is 5.778, which is slightly more elastic than the overall one.
Although the implied price and income elasticity vary with covariates,
the results are in line with our expectations.
Thus, the decision of donations is sensitive to the giving price and annual income.

In summary, our first conclusion is that 
the decision of donations is sensitive to the giving price, 
and the amount of donations is insensitive to the giving price once they decide to donate.
In the next subsection, we check the robustness of our first conclusion, using three methods.
```

```{r MainExtensive}
extensive <- xlist %>%
  purrr::map(~ fit_fixest(
    y = i_ext_giving ~ ., x = .,
    fixef = ~ year + pid, cluster = ~pid,
    data = df
  ))

ext_wald <- extensive %>%
  purrr::map(~ tibble(
    vars = c("Implied price elasticity", "Implied income elasticity"),
    coef = coef(.)[c("log_price", "log_pinc_all")],
    se = fixest::se(.)[c("log_price", "log_pinc_all")],
    invmu = mean(model.matrix(., type = "lhs")),
    p = fixest::pvalue(.)[c("log_price", "log_pinc_all")]
  )) %>%
  purrr::map(function(x)
    x %>%
      mutate(
        coef = case_when(
          p <= .01 ~ sprintf("%1.3f***", coef / invmu),
          p <= .05 ~ sprintf("%1.3f**", coef / invmu),
          p <= .1 ~ sprintf("%1.3f*", coef / invmu),
          TRUE ~ sprintf("%1.3f", coef / invmu)
        ),
        se = sprintf("(%1.3f)", se / invmu)
      ) %>%
      dplyr::select(-p, -invmu) %>%
      pivot_longer(-vars, names_to = "stat", values_to = "val")
  ) %>%
  reduce(full_join, by = c("vars", "stat")) %>%
  setNames(c("vars", "stat", paste0("reg", seq_len(length(extensive)))))

margin <- rep("", ncol(ext_wald))
names(margin) <- c("vars", "stat", paste0("reg", seq_len(length(extensive))))

extensive %>%
  regtab_fixest(
    keep_coef = c("log_price", "log_pinc_all"),
    label_coef = list(
      "log_price" = "ln(giving price)",
      "log_pinc_all" = "ln(annual taxable income)"
    )
  ) %>%
  regtab_addline(list(bind_rows(margin, ext_wald), xlist_tab)) %>%
  mutate(vars = if_else(stat == "se", "", vars)) %>%
  dplyr::select(-stat) %>%
  kable(
    caption = "Extensive-Margin Elasticity of First Price",
    col.names = c("", sprintf("(%1d)", seq_len(length(xlist)))),
    align = "lccccc",
    booktabs = TRUE, escape = TRUE, linesep = ""
  ) %>%
  kable_styling(font_size = 7) %>%
  footnote(
    general_title = "",
    general = "Notes: $^{*}$ $p < 0.1$, $^{**}$ $p < 0.05$, $^{***}$ $p < 0.01$. Standard errors are clustered at individual level. When controlling age, we alson include its squared term. The implied extensive-marign price elasticity is evaluated at the sample mean of $D_{ijt}$.",
    threeparttable = TRUE,
    escape = FALSE
  )
```


## Robustness Check

```{asis, echo = doctype == "slide"}
First potential concern: last price elasticity

- Our baseline results show the **first** price elasticity to avoid the endogeneity of giving price.
- We estimated the **last** price elasticity, using the Panel IV method.
    - The instrument is the first giving price.
    - Note that the last giving price is equal to the first giving price under the tax credit system.

## Robustness Check 1: Result

Overall last price elasticity increases twofold.
```

```{r LastOverall}
overall_iv <- xlist %>%
  purrr::map(~ fit_fixest(
    y = log_total_g ~ .,
    x = update(., ~ . - log_price),
    z = log_lprice ~ log_price,
    fixef = ~ year + pid, cluster = ~ pid,
    data = df
  ))

overall_iv %>%
  regtab_fixest(
    keep_coef = c("log_lprice", "log_pinc_all"),
    label_coef = list(
      "fit_log_lprice" = "ln(last giving price)",
      "log_pinc_all" = "ln(annual taxable income)"
    )
  ) %>%
  regtab_addline(list(xlist_tab)) %>%
  mutate(vars = if_else(stat == "se", "", vars)) %>%
  dplyr::select(-stat) %>%
  kable(
    caption = "Overall Elasticity of Last Price",
    col.names = c("", sprintf("(%1d)", seq_len(length(xlist)))),
    align = "lccccc",
    booktabs = TRUE, escape = TRUE, linesep = ""
  ) %>%
  kable_styling(font_size = 7) %>%
  footnote(
    general_title = "",
    general = "Notes: $^{*}$ $p < 0.1$, $^{**}$ $p < 0.05$, $^{***}$ $p < 0.01$. Standard errors are clustered at individual level. The instumental variable is the first giving price in year $t$. When controlling age, we alson include its squared term.",
    threeparttable = TRUE,
    escape = FALSE
  )
```

```{asis, echo = doctype == "slide"}
## Robustness Check 1: Intensive Margin

The intensive-margin last price elasticity lies within the range of the first price elasticity.
```

```{r LastIntensive}
intensive_iv <- xlist %>%
  purrr::map(~ fit_fixest(
    y = log_total_g ~ .,
    x = update(., ~ . - log_price),
    z = log_lprice ~ log_price,
    fixef = ~ year + pid, cluster = ~pid,
    data = subset(df, i_ext_giving == 1)
  ))

intensive_iv %>%
  regtab_fixest(
    keep_coef = c("log_lprice", "log_pinc_all"),
    label_coef = list(
      "fit_log_lprice" = "ln(last giving price)",
      "log_pinc_all" = "ln(annual taxable income)"
    )
  ) %>%
  regtab_addline(list(xlist_tab)) %>%
  mutate(vars = if_else(stat == "se", "", vars)) %>%
  dplyr::select(-stat) %>%
  kable(
    caption = "Intensive-Margin Elasticity of Last Price",
    col.names = c("", sprintf("(%1d)", seq_len(length(xlist)))),
    align = "lccccc",
    booktabs = TRUE, escape = TRUE, linesep = ""
  ) %>%
  kable_styling(font_size = 7) %>%
  footnote(
    general_title = "",
    general = "Notes: $^{*}$ $p < 0.1$, $^{**}$ $p < 0.05$, $^{***}$ $p < 0.01$. Standard errors are clustered at individual level. The instumental variable is the first giving price in year $t$. When controlling age, we alson include its squared term.",
    threeparttable = TRUE,
    escape = FALSE
  )
```

```{asis, echo = doctype == "slide"}
## Robustness Check 1: Extensive Margin

The extensive-margin last price elasticity at sample mean is roughly -3\%.
```

```{r LastExtensive}
extensive_iv <- xlist %>%
  purrr::map(~ fit_fixest(
    y = i_ext_giving ~ .,
    x = update(., ~ . - log_price),
    z = log_lprice ~ log_price,
    fixef = ~ year + pid, cluster = ~pid,
    data = df
  ))

extiv_wald <- extensive_iv %>%
  purrr::map(~ tibble(
    vars = c("Implied price elasticity", "Implied income elasticity"),
    coef = coef(.)[c("fit_log_lprice", "log_pinc_all")],
    se = fixest::se(.)[c("fit_log_lprice", "log_pinc_all")],
    invmu = mean(model.matrix(., type = "lhs")),
    p = fixest::pvalue(.)[c("fit_log_lprice", "log_pinc_all")]
  )) %>%
  purrr::map(function(x)
    x %>%
      mutate(
        coef = case_when(
          p <= .01 ~ sprintf("%1.3f***", coef / invmu),
          p <= .05 ~ sprintf("%1.3f**", coef / invmu),
          p <= .1 ~ sprintf("%1.3f*", coef / invmu),
          TRUE ~ sprintf("%1.3f", coef / invmu)
        ),
        se = sprintf("(%1.3f)", se / invmu)
      ) %>%
      dplyr::select(-p, -invmu) %>%
      pivot_longer(-vars, names_to = "stat", values_to = "val")
  ) %>%
  reduce(full_join, by = c("vars", "stat")) %>%
  setNames(c("vars", "stat", paste0("reg", seq_len(length(extensive)))))

margin <- rep("", ncol(extiv_wald))
names(margin) <- c("vars", "stat", paste0("reg", seq_len(length(extensive))))

extensive_iv %>%
  regtab_fixest(
    keep_coef = c("log_lprice", "log_pinc_all"),
    label_coef = list(
      "fit_log_lprice" = "ln(last giving price)",
      "log_pinc_all" = "ln(annual taxable income)"
    )
  ) %>%
  regtab_addline(list(bind_rows(margin, extiv_wald), xlist_tab)) %>%
  mutate(vars = if_else(stat == "se", "", vars)) %>%
  dplyr::select(-stat) %>%
  kable(
    caption = "Extensive-Margin Elasticity of Last Price",
    col.names = c("", sprintf("(%1d)", seq_len(length(xlist)))),
    align = "lccccc",
    booktabs = TRUE, escape = TRUE, linesep = ""
  ) %>%
  kable_styling(font_size = 7) %>%
  footnote(
    general_title = "",
    general = "Notes: $^{*}$ $p < 0.1$, $^{**}$ $p < 0.05$, $^{***}$ $p < 0.01$. Standard errors are clustered at individual level. The instumental variable is the first giving price in year $t$. When controlling age, we alson include its squared term. The implied extensive-marign price elasticity is evaluated at the sample mean of $D_{ijt}$.",
    threeparttable = TRUE,
    escape = FALSE
  )
```

```{r}
iv1coef <- list(overall_iv, intensive_iv, extensive_iv) %>%
  purrr::map_depth(2, ~.$iv_first_stage$log_lprice$coeftable["log_price",1]) %>%
  purrr::map(~as_vector(.)) %>%
  as_vector() %>%
  min()

iv1wald <- list(overall_iv, intensive_iv, extensive_iv) %>%
  purrr::map_depth(2, ~fitstat(., ~ ivwald)$ivwald1$stat) %>%
  purrr::map(~as_vector(.)) %>%
  as_vector() %>%
  min()
```

```{asis, echo = doctype == "draft"}
*Last Price Elasticity.*
The first robustness check estimates the last price elasticity using the first price of giving as an instrument.
Our main results show that first price elasticity to avoid the problem that giving price depends on an amount of giving.
However, the first price elasticity is not realistic because people face the last marginal price when deciding on an amount of donation.
Thus, we estimate the last price elasticity, using the first price as an instrumental variable.
The last giving price is strongly correlated with the first one because
major observation units are observed when the tax credit system is implemented,
and the last price is equivalent to the first one in the case of the tax credit system.
In fact, in any specifications, the coefficient of the first price is greater than 0.952, <!-- check iv1coef -->
and its F-statistics is greater than 6425.96. <!-- check iv1wald -->
Our estimates of the last price effect are not caused by a weak instrument problem.
As a result, the intensive-margin elasticity of the last price takes a similar value to the case of the first price, while
the overall elasticity and extensive-margin elasticity of the last price are more elastic than the case of the first price.
Table \@ref(tab:LastOverall) shows the overall last price elasticity.
Compared to the main results, the last price elasticity is more elastic.
The absolute value of the estimated coefficient is larger than 2.4,
which is statistically significantly different from zero.
This implies that a 1\% increase of last price decreases charitable contributions by 2.4\% or more.
Table \@ref(tab:LastIntensive) and \@ref(tab:LastExtensive) shows
the intensive-margin and extensive-margin last price elasticity.
the intensive-margin last price elasticity is a similar value to the main results.
Its absolute value lies between 0.89 and 1.2.
These results are statistically different from zero.
About the extensive-margin elasticities,
the coefficient of logged last price, which represents the lower bound of last price elasticity,
lies between -0.63 and -0.59.
The implied last price elasticity evaluated at the sample mean of $D_{it}$ is roughly -3.
These results are statistically significantly different from zero, and more elastic than the first price elasticity.
```

```{asis, echo = doctype == "slide"}
## Robust Check 2

Second potential concern: Price change due to the change of income
    
- Since the giving price under the tax deduction depends on the change of income, the *within* variation of giving price may be endogenous.
- To resolve this concern, we used the data (i) from 2013 to 2018 or (ii) from 2013 to 2014, and estimated the fixed effect model.
    - By this restriction, the *within* price variation of giving price is completely exgonenous.
```

```{r }
xlist2 <- list(
  ~ log_price + log_pinc_all,
  ~ log_price + log_pinc_all + age + sqage + factor(year):factor(educ) +
    factor(year):factor(gender) + factor(year):factor(living_area)
)

xlist2_tab <- tribble(
  ~vars, ~stat, ~reg1, ~reg2,
  "Individual FE", "vars", "Y", "Y",
  "Time FE", "vars", "Y", "Y",
  "Other Controls", "vars", "N", "Y",
)

xlist2_duptab <- xlist2_tab %>%
  full_join(xlist2_tab, by = c("vars", "stat")) %>%
  setNames(c("vars", "stat", paste0("reg", seq_len(4))))
```

```{asis, echo = doctype == "slide"}
## Robustness Check 2: Result

Overall price elasticity is -1 ~ -1.7\%.
```

```{r ShortOverall}
overall_s1 <- xlist2 %>%
  purrr::map(~ fit_fixest(
    y = log_total_g ~ ., x = .,
    fixef = ~ year + pid, cluster = ~ pid,
    data = subset(df, year >= 2013)
  ))

overall_s2 <- xlist2 %>%
  purrr::map(~ fit_fixest(
    y = log_total_g ~ ., x = .,
    fixef = ~ year + pid, cluster = ~ pid,
    data = subset(df, year == 2013 | year == 2014)
  ))

list(overall_s1, overall_s2) %>%
  flatten() %>%
  regtab_fixest(
    keep_coef = c("log_price", "log_pinc_all"),
    label_coef = list(
      "log_price" = "ln(giving price)",
      "log_pinc_all" = "ln(annual taxable income)"
    )
  ) %>%
  regtab_addline(list(xlist2_duptab)) %>%
  mutate(vars = if_else(stat == "se", "", vars)) %>%
  dplyr::select(-stat) %>%
  kable(
    caption = "Overall Elasticity with Short-Period Panel",
    col.names = c("", sprintf("(%1d)", seq_len(length(xlist2) * 2))),
    align = "lcccc",
    booktabs = TRUE, escape = TRUE, linesep = ""
  ) %>%
  kable_styling(font_size = 7) %>%
	add_header_above(
    c(" " = 1, "After 2012" = 2, "2013 and 2014" = 2),
    escape = FALSE
  ) %>%
  footnote(
    general_title = "",
    general = "Notes: $^{*}$ $p < 0.1$, $^{**}$ $p < 0.05$, $^{***}$ $p < 0.01$. Standard errors are clustered at individual level. Other controls are age (its squared value), the interaction between year dummies and education dummies, the interaction between year dummies and gender dummies, and the interaction between year dummies and resident area.",
    threeparttable = TRUE,
    escape = FALSE
  )
```

```{asis, echo = doctype == "slide"}
## Robustness Check 2: Intensive Marign

The intensive-margin price elasticity is -0.6 ~ -1\%.
In column (3), the price elasticity is statistically insignificant.
```

```{r ShortIntensive}
intensive_s1 <- xlist2 %>%
  purrr::map(~ fit_fixest(
    y = log_total_g ~ ., x = .,
    fixef = ~ year + pid, cluster = ~ pid,
    data = subset(df, year >= 2013 & i_ext_giving == 1)
  ))

intensive_s2 <- xlist2 %>%
  purrr::map(~ fit_fixest(
    y = log_total_g ~ ., x = .,
    fixef = ~ year + pid, cluster = ~ pid,
    data = subset(df, (year == 2013 | year == 2014) & i_ext_giving == 1)
  ))

list(intensive_s1, intensive_s2) %>%
  flatten() %>%
  regtab_fixest(
    keep_coef = c("log_price", "log_pinc_all"),
    label_coef = list(
      "log_price" = "ln(giving price)",
      "log_pinc_all" = "ln(annual taxable income)"
    )
  ) %>%
  regtab_addline(list(xlist2_duptab)) %>%
  mutate(vars = if_else(stat == "se", "", vars)) %>%
  dplyr::select(-stat) %>%
  kable(
    caption = "Intensive-Margin Elasticity with Short-Period Panel",
    col.names = c("", sprintf("(%1d)", seq_len(length(xlist2) * 2))),
    align = "lcccc",
    booktabs = TRUE, escape = TRUE, linesep = ""
  ) %>%
  kable_styling(font_size = 7) %>%
	add_header_above(
    c(" " = 1, "After 2012" = 2, "2013 and 2014" = 2),
    escape = FALSE
  ) %>%
  footnote(
    general_title = "",
    general = "Notes: $^{*}$ $p < 0.1$, $^{**}$ $p < 0.05$, $^{***}$ $p < 0.01$. Standard errors are clustered at individual level. Other controls are age (its squared value), the interaction between year dummies and education dummies, the interaction between year dummies and gender dummies, and the interaction between year dummies and resident area.",
    threeparttable = TRUE,
    escape = FALSE
  )
```

```{asis, echo = doctype == "slide"}
## Robustness Check 2: Extensive Marign

The extensive-margin price elasticity at sample mean is -1 ~ -2\%.
```

```{r ShortExtensive}
extensive_s1 <- xlist2 %>%
  purrr::map(~ fit_fixest(
    y = i_ext_giving ~ ., x = .,
    fixef = ~ year + pid, cluster = ~pid,
    data = subset(df, year >= 2013)
  ))

extensive_s2 <- xlist2 %>%
  purrr::map(~ fit_fixest(
    y = i_ext_giving ~ ., x = .,
    fixef = ~ year + pid, cluster = ~pid,
    data = subset(df, year == 2013 | year == 2014)
  ))

exts_wald <- list(extensive_s1, extensive_s2) %>%
  flatten() %>%
  purrr::map(~ tibble(
    vars = c("Implied price elasticity", "Implied income elasticity"),
    coef = coef(.)[c("log_price", "log_pinc_all")],
    se = fixest::se(.)[c("log_price", "log_pinc_all")],
    invmu = mean(model.matrix(., type = "lhs")),
    p = fixest::pvalue(.)[c("log_price", "log_pinc_all")]
  )) %>%
  purrr::map(function(x)
    x %>%
      mutate(
        coef = case_when(
          p <= .01 ~ sprintf("%1.3f***", coef / invmu),
          p <= .05 ~ sprintf("%1.3f**", coef / invmu),
          p <= .1 ~ sprintf("%1.3f*", coef / invmu),
          TRUE ~ sprintf("%1.3f", coef / invmu)
        ),
        se = sprintf("(%1.3f)", se / invmu)
      ) %>%
      dplyr::select(-p, -invmu) %>%
      pivot_longer(-vars, names_to = "stat", values_to = "val")
  ) %>%
  reduce(full_join, by = c("vars", "stat")) %>%
  setNames(c("vars", "stat", paste0("reg", seq_len(length(extensive)))))

margin <- rep("", ncol(exts_wald))
names(margin) <- c("vars", "stat", paste0("reg", seq_len(length(xlist2) * 2)))

list(extensive_s1, extensive_s2) %>%
  flatten() %>%
  regtab_fixest(
    keep_coef = c("log_price", "log_pinc_all"),
    label_coef = list(
      "log_price" = "ln(giving price)",
      "log_pinc_all" = "ln(annual taxable income)"
    )
  ) %>%
  regtab_addline(list(bind_rows(margin, exts_wald), xlist2_duptab)) %>%
  mutate(vars = if_else(stat == "se", "", vars)) %>%
  dplyr::select(-stat) %>%
  kable(
    caption = "Extensive-Margin Elasticity with Short-Period Panel",
    col.names = c("", sprintf("(%1d)", seq_len(length(xlist2) * 2))),
    align = "lcccc",
    booktabs = TRUE, escape = TRUE, linesep = ""
  ) %>%
  kable_styling(font_size = 7) %>%
	add_header_above(
    c(" " = 1, "After 2012" = 2, "2013 and 2014" = 2),
    escape = FALSE
  ) %>%
  footnote(
    general_title = "",
    general = "Notes: $^{*}$ $p < 0.1$, $^{**}$ $p < 0.05$, $^{***}$ $p < 0.01$. Standard errors are clustered at individual level. Other controls are age (its squared value), the interaction between year dummies and education dummies, the interaction between year dummies and gender dummies, and the interaction between year dummies and resident area. The implied extensive-marign price elasticity is evaluated at the sample mean of $D_{ijt}$.",
    threeparttable = TRUE,
    escape = FALSE
  )
```

```{asis, echo = doctype == "draft"}
<!---
<要修正ポイント>：この点ですが、普通はむしろTime spanを長くして、TransitonaryなEffectとPersistentなEffectを分けて議論するのが普通だと思います。原稿のバージョンでは意図をくんでごまかして書いています。
--->

*Short-Period Panel.*
The second robustness check try to control the manipulation of giving price by adjusting income level,
using two datasets whose ranges are (i) from 2013 to 2018 and (ii) from 2013 to 2014.
Under the tax deduction system,
the giving price can be manipulated by income level,
though it cannot be under the tax credit system.
Therefore, if we use the dataset which contains data under the tax deduction system,
the estimator may capture the effect of price change
which is caused not by tax reform but by price manipulation by income adjustment.
To address this issue,
we use a dataset in which the time range under the tax deduction system is shorter than the baseline analysis.
By doing this exercise, we try to suppress the effect which comes from the price change due to the change of income.
Table \@ref(tab:ShortOverall) shows the overall first giving price elasticity.
When we use data from 2013 to 2018, the estimated price elasticity is a similar value to the main results.
On the other hand,
when we use data from 2013 to 2014, the estimated price elasticity is more elastic than the main results.
The estimated absolute value is roughly -1.7 when we control covariates and their interaction with year dummies.
This value is statistically significantly different from zero.
Table \@ref(tab:ShortIntensive) and \@ref(tab:ShortExtensive) shows
the intensive-margin and the extensive-margin first price elasticity.
When we use data from 2012 to 2018, the intensive-margin price elasticity is similar to the main results,
which is statistically significant from zero.
However, when we use data from 2013 to 2014 and include only individual and time fixed effects,
the estimated coefficient is statistically insignificantly different from zero.
By controlling covariates and their interaction with year dummies,
the intensive-margin price elasticity is -0.712, which is statistically significant.
About the extensive-margin price effect,
when we use data from 2012 to 2018, the extensive-margin price elasticity is similar to the main results,
which is statistically significant.
When we use data from 2013 to 2014, the extensive-margin price elasticity is more elastic than the main results.
Its absolute value is roughly -2, which is statistically significant.
```

```{asis, echo = doctype == "slide"}
## Robustness Check 3

Second potential concerns: the change of price due to the change of income

- To exclude this potential concerns, previous identification strategy uses the 2014 tax reform.
- We can also rule out this problem, using the change in the first giving price.
    - The change in the first giving price is $\ln(p_{it}(y_{it-k} - g_{it-k})/p_{it-k}(y_{it-k} - g_{it-k}))$ where $g_{it-k} = 0$.
    - Since we fix the income $y_{it-k}$, this variation comes from the tax reform.

## Robustness Check 3 (Cont'd)

Our estimation equation is 
$$\Delta^k \ln g_{it} = \delta \Delta^k \ln p_{it} + \gamma \Delta^k \ln y_{it} + \Delta^k X_{it} \beta + \mu_i + \iota_t + v_{it},$$
where $\Delta^k Y_{it} = Y_{it} - Y_{it-k}$.

- Note that we cannot estimation the extensive-margin elasticity since it is hard to interapt this estimation equation when we use $\Delta^k D_{it}$ as an outcome.
- We estimate this model for $k = 1, 2, 3$.
```

```{r }
kdiff <- list(
  lag1 = list(
    y = log_diff1g ~ .,
    x = ~ log_iv1price + log_diff1I + diff1_age + diff1_sqage
  ),
  lag2 = list(
    y = log_diff2g ~ .,
    x = ~ log_iv2price + log_diff2I + diff2_age + diff2_sqage
  ),
  lag3 = list(
    y = log_diff3g ~ .,
    x = ~ log_iv3price + log_diff3I + diff3_age + diff3_sqage
  )
)

kdiff_tab <- tibble(
  vars = c("Individual FE", "Time FE", "Other controls"),
  stat = rep("vars", 3),
  reg1 = rep("Y", 3), reg2 = rep("Y", 3), reg3 = rep("Y", 3)
)
```


```{asis, echo = doctype == "slide"}
## Robustness Check 3: Overall Elasticity

Overall price elasticity is rougnly -2\%.
```

```{r kdiffOverall}
overall_kdiff <- kdiff %>%
  purrr::map(~ fit_fixest(
    y = .$y,
    x = update(
      .$x,
      ~ . + factor(year):factor(educ) + factor(year):factor(gender) +
        factor(year):factor(living_area)
    ),
    fixef = ~ pid + year, cluster = ~ pid,
    data = df
  ))

overall_kdiff %>%
  regtab_fixest(
    keep_coef = c("log_iv", "log_diff"),
    label_coef = list(
      "log_iv1price" = "1-year lagged difference of first price (log)",
      "log_iv2price" = "2-year lagged difference of first price (log)",
      "log_iv3price" = "3-year lagged difference of first price (log)",
      "log_diff1I" = "1-year lagged difference of annual income (log)",
      "log_diff2I" = "2-year lagged difference of annual income (log)",
      "log_diff3I" = "3-year lagged difference of annual income (log)"
    )
  ) %>%
  regtab_addline(list(kdiff_tab)) %>%
  mutate(vars = if_else(stat == "se", "", vars)) %>%
  dplyr::select(-stat) %>%
  kable(
    caption = "Estimation of Overall Elasticity with $k$-th Difference Model",
    col.names = c("", sprintf("(%1d)", seq_len(length(kdiff)))),
    align = "lccc",
    booktabs = TRUE, escape = TRUE, linesep = ""
  ) %>%
  kable_styling(font_size = 7) %>%
	footnote(
    general_title = "",
    general = "Notes: $^{*}$ $p < 0.1$, $^{**}$ $p < 0.05$, $^{***}$ $p < 0.01$. Standard errors are clustered at individual level. The lagged difference of first price (log) is $\\\\ln(\\\\text{Price}^k_{ijt}) - \\\\ln(\\\\text{Price}_{ij(t-k)})$, where $\\\\text{Price}^k_{ijt}$ calculates the giving price under the tax system in year $t$, using annual taxable income in year $t-k$, $\\\\text{Income}_{ij(t-k)}$. The lagged of annual income (log) is $\\\\ln(\\\\text{Income}_{ijt}) - \\\\ln(\\\\text{Income}_{ij(t-k)})$. Other controls are lagged difference of age, lagged difference of squared age, the interaction between year dummies and education dummies, the interaction between year dummies and gender dummies, and the interaction between year dummies and resident area.",
    threeparttable = TRUE,
    escape = FALSE
  )
```

```{asis, echo = doctype == "slide"}
## Robustness Check 3: Intensive-Margin Elasticity

The intensive-margin price elasticity is rougnly -2\%.
```

```{r kdiffIntensive}
intensive_kdiff <- kdiff %>%
  purrr::map(~ fit_fixest(
    y = .$y,
    x = update(
      .$x,
      ~ . + factor(year):factor(educ) + factor(year):factor(gender) +
        factor(year):factor(living_area)
    ),
    fixef = ~ pid + year, cluster = ~pid,
    data = subset(df, i_ext_giving == 1)
  ))

intensive_kdiff %>%
  regtab_fixest(
    keep_coef = c("log_iv", "log_diff"),
    label_coef = list(
      "log_iv1price" = "1-year lagged difference of first price (log)",
      "log_iv2price" = "2-year lagged difference of first price (log)",
      "log_iv3price" = "3-year lagged difference of first price (log)",
      "log_diff1I" = "1-year lagged difference of annual income (log)",
      "log_diff2I" = "2-year lagged difference of annual income (log)",
      "log_diff3I" = "3-year lagged difference of annual income (log)"
    )
  ) %>%
  regtab_addline(list(kdiff_tab)) %>%
  mutate(vars = if_else(stat == "se", "", vars)) %>%
  dplyr::select(-stat) %>%
  kable(
    caption =
      "Estimation of Intensitve-Margin Elasticity with $k$th Difference Model",
    col.names = c("", sprintf("(%1d)", seq_len(length(kdiff)))),
    align = "lccc",
    booktabs = TRUE, escape = TRUE, linesep = ""
  ) %>%
  kable_styling(font_size = 7) %>%
	footnote(
    general_title = "",
    general = "Notes: $^{*}$ $p < 0.1$, $^{**}$ $p < 0.05$, $^{***}$ $p < 0.01$. Standard errors are clustered at individual level. The lagged difference of first price (log) is $\\\\ln(\\\\text{Price}^k_{ijt}) - \\\\ln(\\\\text{Price}_{ij(t-k)})$, where $\\\\text{Price}^k_{ijt}$ calculates the giving price under the tax system in year $t$, using annual taxable income in year $t-k$, $\\\\text{Income}_{ij(t-k)}$. The lagged of annual income (log) is $\\\\ln(\\\\text{Income}_{ijt}) - \\\\ln(\\\\text{Income}_{ij(t-k)})$. Other controls are lagged difference of age, lagged difference of squared age, the interaction between year dummies and education dummies, the interaction between year dummies and gender dummies, and the interaction between year dummies and resident area.",
    threeparttable = TRUE,
    escape = FALSE
  )
```

```{asis, echo = doctype == "draft"}
*$k$-th difference model.*
The third robustness check is to estimate the $k$-th difference model.
As explained in section \@ref(empirical-strategy), the giving price depends on income.
Thus, there are two paths that income affects charitable giving: (i) income effect; (ii) giving price via manipulation.
To tackel with this endogeneity problem, we employ lagged value of giving price fixing income at year $t-k$,
that is, $\Delta^k \ln p_{it} = ln p_{it}(y_{it-k}) - \ln p_{it-k}(y_{it-k})$.[^DeltaCredit]
By fixing income, the variation of this lagged variable completely depends on tax reform.
Using this variable,
we estimate the $k$-th difference model \@ref(eq:kdiff) shown in the section \@ref(empirical-strategy). 
Table \@ref(tab:kdiffOverall) and \@ref(tab:kdiffIntensive) shows results of $k$-th difference model.
About the overall elasticity,
when we take the one-year lag ($k = 1$), the overall price elasticity is roughly -1.9,
which is statistically significant.
This elasticity slightly varies when we take the two or more year lag ($k > 1$).
The overall price elasticity lies between -2.1 and -1.7, which is statistically significant.
This implies that the overall price elasticity obtained by this model is more elastic than the main results.
About the intensive-margin elasticity,
when we take the one-year lag ($k = 1$), the intensive-margin price elasticity is roughly -1.8,
which is statistically significant.
The absolute value of the price elasticity is more than 2
when we take two or more years lag ($k > 1$).
Thus, contrary to our first conclusion,
this model implies that the amount of donations is sensitive to the giving price once we decide to donate.

[^DeltaCredit]: Under the tax credit system, the giving price does not depend on income $y_{it-k}$. If the tax credit system is implemented in year $t$ and $t-k$, then the value of $\Delta^k p_{it}$ takes zero.

<!--
In summary, the result shows that the size of estimated elasticity may vary depending on the estimation methods. This may be because the sample size is small compared to the extant research. However, our three robustness checks are in line with the baseline result, which shows that the price elasticity of intensive margin is less elastic than one of extensive margin. Thus, the obtained results suggest that the decision to donate is sensitive to the giving price, though the amount of donations is insensitive to the giving price once they decide to donate. 
--->
```