# Governement Efficient and Price Elasticity


```{r }
library(xfun)
xfun::pkg_attach2(c("tidyverse", "rlist"))
xfun::pkg_attach2(c("plm", "lmtest", "sandwich", "lfe", "Formula"))
xfun::pkg_attach2("kableExtra")

lapply(Sys.glob(file.path("script/R/functions", "*.r")), source)

```
```{r }
df <- readr::read_csv(
  "data/shaped2.csv",
  col_types = cols(
    ext_credit_giving = col_double(),
    krw_credit_giving = col_double(),
    trust_politician = col_double(),
    political_pref = col_double(),
    addtax = col_double(),
    avg_welfare_tax = col_double(),
    opt_welfare_tax = col_double(),
    now_balance = col_double(),
    ideal_balance = col_double()
  )
)

balance_dt <- read.dta13("data/shape/balanceid.dta") %>%
  data.frame()

mergedf <- left_join(df, balance_dt, by = "pid") %>%
  mutate(balance3 = ntile(balanceid, 3)) %>%
  mutate(
    log_price_int2 = log_price * (balance3 == 2),
    log_price_int3 = log_price * (balance3 == 3),
  )
```

## Construct Efficiency Index

```{asis, echo = doctype == "slide"}
From the 2015 survey, NaSTaB asks the current and ideal balance between tax burden and welfare level.
See the following table.
```

```{r efficientQ, include=TRUE}
data.frame(
	col1 = c("High", "Middle", "Low"),
	col2 = c("2", "1", "0"),
	col3 = c("1", "0", "-1"),
	col4 = c("0", "-1", "-2")
) %>% 
knitr::kable(
	format = "latex",
	caption = "The assigned number for each pair of welfare/tax burden answers",
	col.names = c("Welfare/Tax burden", "Low", "Middle", "High"),
	row.names = FALSE,
	align = "l|ccc", 
	booktabs = TRUE, escape = TRUE, linesep = ""
) %>% 
kable_styling(font_size = 8) %>% 
footnote(general_title = "", general = "Notes: The number shows the corresponding efficiency index for each pair of tax burden and welfare level.", threeparttable = TRUE, escape = FALSE)
```

```{asis, echo = doctype == "slide"}
## Construct Efficient Index (Cont'd)

- The pair of answers reflect the individual's perception about the efficiency of government because the government with low tax burden and high welfare level is clearly more efficient than one with high tax and low welfare.
- Based on the pair about current perception, we construct an index called efficiency index by the following steps.
	1. We assign the number from -2 to 2 for each pair of answers depending on the contents of answers, where -2 is the most inefficient and 2 is the most efficient.
	2. To construct the individual's persistent perception toward the government, we regress the assigned number on year fixed effect, the interaction between region and year fixed effect, and individual fixed effect.
	3. use the obtained fixed effect as the efficiency index
```

```{asis, echo = doctype == "draft"}
From the 2015 survey, NaSTaB asks the current and ideal balance between tax burden and welfare level. 
For current balance, the subjects answer the degree of their current perception about tax burden and welfare level, 
both of them are scaled by three: high, middle, and low. 
For ideal balance, the choice set of answer is the same as the current balance, but the subjects answers their ideal tax burden and welfare level.
Thus, we can derive the two pair of answers about tax burden and welfare level for each subject, i.e. the pair about current balance and one about ideal balance.

We can consider that the pair of answers about current balance reflect the individual's perception about the efficiency of government 
because the government with low tax burden and high welfare level is clearly more efficient than one with high tax and low welfare. 
Based on the pair about current perception, we construct an index called efficiency index by the following steps. 
Firstly, according to Table \@ref(tab:efficientQ), 
we assign the number from -2 to 2 for each pair of answers depending on the contents of answers, 
where -2 is the most inefficient and 2 is the most efficient. 
Secondly, to construct the individual's persistent perception toward the government, 
we regress the assigned number on year fixed effect, the interaction between region and year fixed effect, and individual fixed effect. 
Then, we use the obtained fixed effect as the efficiency index.
We consider that the efficiency index shows the individual's perception toward government for its efficiency. 

In Figure \@ref(fig:showDensityEfficientIndex), the solid line shows the density of efficient index.
As the efficient index is higher, 
individuals are more likely to perceive that the government can provide the public goods efficiency.
There are two features about the distribution of efficient index.
First, the efficient index is concentrated around zero.
This implies that many people thinks the efficiency of government is neutral.
Second, the density of those whose the efficient index is less than zero is larger than of 
those whose the efficient index is greater than zero.
This implies that the number of people thinking the government is inefficient is 
less than people who think the government is efficient.
```

```{asis, echo = doctype == "slide"}
## Histrogram of Efficient Index
```

```{r eval = FALSE}
mergedf %>%
  dplyr::select(pid, balanceid) %>%
  distinct(.keep_all = TRUE) %>%
  ggplot(aes(x = balanceid)) +
  geom_histogram(aes(y = ..count..), fill = "grey80", color = "black") +
  labs(x = "Efficient index") +
  ggtemp()
```

```{r out.width="90%", fig.cap="Density of Efficient Index"}
mergedf %>%
  dplyr::select(pid, balanceid, ideal_balanceid) %>%
  distinct(.keep_all = TRUE) %>%
  ggplot(aes(x = balanceid)) +
  stat_density(
    aes(linetype = "Full sample"),
    geom = "line", position = "identity"
  ) +
  stat_density(
    data = ~subset(.x, ideal_balanceid > 0),
    aes(linetype = "Ideal efficient index > 0"),
    geom = "line", position = "identity"
  ) +
  labs(x = "Efficient index", linetype = "") +
  ggtemp()
```


```{asis, echo = doctype == "slide"}
## Two Potential Concerns

1. There is a room for subjects to interpret the questions of tax/welfare balance as questions about the expenditure policy of the government.
	- To address this issue, we use the question for ideal balance between tax burden and welfare level to rule out the subjects who consider that the higher welfare level than the tax burden is unfavorable.
2. Efficiency indexの構成方法にかかわる問題をここに書こうかと思います。上記では固定効果をとっている理由をPersistentな政府へのperceptionを見たいからとしていますが、別にそれぞれの時点でのperceptionをとっても構わないだろうとツッコミが来ると思うので、なぜ固定効果をとっているのかなどを書いてもらえればと思います。
```

```{asis, echo = doctype == "draft"}
There are two potential concerns about the efficient index.
The first concern is related with a interpretation of question.
Considering the contents of the questions about tax/welfare balance 
there is a room for subjects to interpret these questions
not as questions about the efficiency of the government 
but as questions about the expenditure policy of the government. 
If the latter is true, 
some subjects consider that the government with low tax burden and high welfare level is inefficient because 
it conducts debt financing. 

To address this issue, 
we use the question for ideal balance between tax burden and welfare level 
to rule out the subjects who consider that the higher welfare level than the tax burden is unfavorable. 
In other words, in the robustness check, 
we rule out the subjects whose efficiency index for the ideal balance question is less than 0. 
We check that this refinement enable us to get a clearer result. 
In Figure \@ref(fig:showDensityEfficientIndex),
the dashed line shows the density of efficient index
using those whose the *ideal* efficient index is greater than zero.
Its distribution is similar to the distribution using full sample.

The second concern is related with the construction of efficient index.
The perceived governement efficiency is formed by time-specific events such as governement policies.
Thus, instead of the individual fixed effect,
we should use the raw answer of the quetion as the efficient index.
However, since the tax credit system has been implemented since 2014,
there is no variation of giving price from 2015 to 2018.
Thus, we cannot estimate the price elasticity.

To overcome this problem, we use the individual fixed effect as the efficient index.
This index does not depend on government policies implemented in a specific year and preference for president.
Thus, the efficient index represents persistent perception toward governement efficiency,
which is formed by individual education and continuous policies.
```

## Heterogeneous Price Elasticity in Governement Efficiency

```{asis, echo = doctype == "slide"}
To see the heterogenous price elasticity by efficient index,
we utilize the interaction between the efficiency index and the giving price.

Bothe ways of the analyses use the sepcifications based on the Equation (XX) and (XX) for intensive and extensive margins,
respectively.

We control individual and time fixed effect,
and other covariates.
```

```{asis, echo = doctype == "draft"}
To estimate the heterogenous price elasticity in the efficient index, 
we include interaction terms between the efficient index and the giving price
into the model Eq. (\@ref(eq:intensive)) and (\@ref(eq:extensive)) for intensive and extensive margins, respectively. 
To construct interaction terms, we partition respondents into three groups based on three quantile of efficient index,
and create corresponding two dummy variables.
```

```{r }
xlist3 <- ~ log_price + log_price_int2 + log_price_int3 + log_pinc_all +
  age + sqage + factor(year):factor(educ) + factor(year):factor(gender) +
  factor(year):factor(living_area)

xlist3_tab <- tibble(
  vars = c("Individual FE", "Time FE", "Other controls"),
  stat = "vars",
  reg1 = "Y"
)
```


```{asis, echo = doctype == "draft"}
Table \@ref(tab:kableHeteroElasticity) shows the heterogenous price effect in the efficient index
when we use full sample.
Column (1) shows the overall elasticities.
By calculating implied price elasticitiy for each quantile group,
we find that the absolute value of overall price elasiticity is decreasing in the efficient index.
This implies that the price elasticitiy becomes more elastic 
as people think the governement's provision of public goods is inefficient.
However, 
the difference of implied price elasiticity is not statistically significant
since two interaction terms between giving price and the quantile group of efficient index are statistically insignificant.
Column (2) shows the extensive-margin elasticities.
By the implied price elasticity for each group,
we find the extensive-margin price elasticity is convex in the efficient index.
In other words, those who is the most sensitive to the giving price think that 
governement efficiency is neutral.
However, the difference of implied extensive-margin price elasticity is not statistically significant
because coefficients of two interaction terms are not statistically significant.
Column (3) shows the intensive-margin elasticities.
The implied intensive-margin price elasiticity is concave in the efficient index.
This implies those whose the amount of donations is the most sensitive preceive that 
the government effciency is inefficient or efficient.
As overall and extensive-margin elasticities,
the difference of implied intensive-margin price elasticity is statistically insignificant.
```

```{r }
wald_hetero1 <- list(
  "Implied price elasticity (1Q efficient group)" =
    "1*log_price",
  "Implied price elasticity (2Q efficient group)" =
    "1*log_price + 1*log_price_int2",
  "Implied price elasticity (3Q efficient group)" =
    "1*log_price + 1*log_price_int3",
  "Implied income elasticity" = "1*log_pinc_all"
)

overall_hetero <- est_felm(
  y = log_total_g ~ ., x = xlist3,
  fixef = ~ pid + year, cluster = ~ pid,
  data = mergedf
)

overallh_wald <- felm_wald(overall_hetero, wald_hetero1)

intensive_hetero <- est_felm(
  y = log_total_g ~ ., x = xlist3,
  fixef = ~ pid + year, cluster = ~pid,
  data = subset(mergedf, i_ext_giving == 1)
)

intensiveh_wald <- felm_wald(intensive_hetero, wald_hetero1)

wald_hetero2 <- list(
  "Implied price elasticity (1Q efficient group)" =
    "imp*log_price",
  "Implied price elasticity (2Q efficient group)" =
    "imp*log_price + imp*log_price_int2",
  "Implied price elasticity (3Q efficient group)" =
    "imp*log_price + imp*log_price_int3",
  "Implied income elasticity" = "imp*log_pinc_all"
)

extensive_hetero <- est_felm(
  y = i_ext_giving ~ ., x = xlist3,
  fixef = ~ pid + year, cluster = ~ pid,
  data = mergedf
)

extensiveh_wald <- felm_wald(
  extensive_hetero,
  hypo = wald_hetero2,
  args = list(imp = 1 / mean(extensive_hetero$response))
)

waldtab <- list(overallh_wald, extensiveh_wald, intensiveh_wald) %>%
  reduce(full_join, by = c("vars", "stat")) %>%
  setNames(c("vars", "stat", paste0("reg", seq_len(3))))

xlist3_duptab <- list(xlist3_tab, xlist3_tab, xlist3_tab) %>%
  reduce(full_join, by = c("vars", "stat")) %>%
  setNames(c("vars", "stat", paste0("reg", seq_len(3))))

list(overall_hetero, extensive_hetero, intensive_hetero) %>%
  felm_regtab(
    keep_coef = c("log_price", "log_pinc_all"),
    label_coef = list(
      "log_price" = "ln(giving price)",
      "log_price_int2" = "ln(giving price) x 2Q efficient group",
      "log_price_int3" = "ln(giving price) x 3Q efficient group",
      "log_pinc_all" = "ln(annual taxable income)"
    )
  ) %>%
  regtab_addline(list(waldtab, xlist3_duptab)) %>%
  mutate(vars = if_else(stat == "se", "", vars)) %>%
  dplyr::select(-stat) %>%
  kable(
    col.names = c("", sprintf("(%1d)", seq_len(3))),
    align = "lccc"
  ) %>%
  kable_styling()
```


```{asis, echo = doctype == "draft"}
Previous results show that there is no heterogenous price elasticity in the efficient index.
This may be caused by existence of respondents 
interpreting the survey questions as the questions about the expenditure policy of the government.
We expect that their decision of donations is sensitive to the giving price 
if the real governement efficiency is high.
They donate if the giving price is low to substitute for the governement expenditure.
To rule out this problem, we eliminate those whose the ideal efficient index is less than zero,
and estimate the same model in Table \@ref(tab:kableHeteroElasticity).
```

```{r }
overall_hetero2 <- est_felm(
  y = log_total_g ~ ., x = xlist3,
  fixef = ~ pid + year, cluster = ~pid,
  data = subset(mergedf, ideal_balanceid > 0)
)

overallh2_wald <- felm_wald(overall_hetero2, wald_hetero1)

intensive_hetero2 <- est_felm(
  y = log_total_g ~ ., x = xlist3,
  fixef = ~ pid + year, cluster = ~pid,
  data = subset(mergedf, i_ext_giving == 1 & ideal_balanceid > 0)
)

intensiveh2_wald <- felm_wald(intensive_hetero2, wald_hetero1)

extensive_hetero2 <- est_felm(
  y = i_ext_giving ~ ., x = xlist3,
  fixef = ~ pid + year, cluster = ~pid,
  data = subset(mergedf, ideal_balanceid > 0)
)

extensiveh2_wald <- felm_wald(
  extensive_hetero2,
  hypo = wald_hetero2,
  args = list(imp = 1 / mean(extensive_hetero2$response))
)

waldtab2 <- list(overallh2_wald, extensiveh2_wald, intensiveh2_wald) %>%
  reduce(full_join, by = c("vars", "stat")) %>%
  setNames(c("vars", "stat", paste0("reg", seq_len(3))))

list(overall_hetero2, extensive_hetero2, intensive_hetero2) %>%
  felm_regtab(
    keep_coef = c("log_price", "log_pinc_all"),
    label_coef = list(
      "log_price" = "ln(giving price)",
      "log_price_int2" = "ln(giving price) x 2Q efficient group",
      "log_price_int3" = "ln(giving price) x 3Q efficient group",
      "log_pinc_all" = "ln(annual taxable income)"
    )
  ) %>%
  regtab_addline(list(waldtab2, xlist3_duptab)) %>%
  mutate(vars = if_else(stat == "se", "", vars)) %>%
  dplyr::select(-stat) %>%
  kable(
    col.names = c("", sprintf("(%1d)", seq_len(3))),
    align = "lccc"
  ) %>%
  kable_styling()
```

```{asis, echo = doctype == "draft"}

Table \@ref(tab:kableSubsetHeteroElasticity) shows the heterogenous price elasticity in the efficient index
when we use those whose the ideal efficient index is greater than zero.
As a result, we found heterogeneity of the overall and extensive-margin price elasticitiy 
in governement efficiency (column (1) and (2)). 
In the column (1), the interaction term between the giving price and third quantile efficient group 
is positive, which is statistically significant.
This implies that, compared to those whose the efficient index is low,
those whose the efficient index is high are less sensitive to the giving price.
In fact, the implied price elasticitiy of the first quantile efficient group is about -1.8,
which is statistically significant.
On the other hand, the implied price elasticiity of the third quantile efficient group is roughly -0.5,
which is not statistically significant.
The extensive-margin price elasticitiy takes same pattern in the column (2).
The implied price elasticitiy of the first quantile efficient group is about -1.5,
which is statistically significant.
On the other hand, the implied price elasticiity of the third quantile efficient group is roughly -0.4,
which is not statistically significant.
Column (3) shows the intensive-margin elasticities.
we found there is no heterogenous price effect on the amount of donations among donors.
```