```{r eval = FALSE}
# if you want to preview this file,
# 1. specify doctype: "draft" or "slide"
# 2. replace knitr format = "html"
library(here); knitr::opts_knit$set(root.dir = here())
doctype <- "draft"
options(knitr.kable.NA = " ", knitr.table.format = "html")
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo = FALSE,
  cache = FALSE,
  include = TRUE
)
```

```{asis, echo = doctype == "draft"}
# Appendix: Conceptual framework

In this appendix, we use the framework of @Fack2016 and predict the size of gap between the price elasticities on the reported charitable giving and the true charitable giving.

## Setup

There is a continuum of individuals with density $dv(i)$ over $i(\in I)$. $I$ is a set of individuals in this model. An individual earns $z^i$, consumes $c^i$, and donate $g^i$. Individuals' utility is increasing in $c^i$ and $g^i$, and decresing in $z^i$, meaning that labor supply is costly. The positive utility from the contribution $g^i$ reflects the utility from the fact of giving following the warm-glow model. Government levys tax on $z^i$ at rate $t$ to be used for a transfer $R$ and subsidy for charitable giving $\tau$. 

Government also impose some requirements for the giving declaration. We simply show the requirements as a policy parameter $p$ and $p$ generates the declaration cost for individuals\footnote{We assume that this cost directly affect the utility in this model.}. Because of the declaration costs, the reported amount of charitable giving $g^r^i$ and true amount of charitable giving $g^i$ will have a difference, i.e. $g^m^i=g^i-g^r^i$. 

The individual's optimization can be shown as
\begin{align}
\max_{c^i,z^i,g^i,g^m^i}& U^i=u^i(c^i,z^i,g^i,g^m^i,G,p)\notag\\
\text{s.t.}& c+(1-\tau)g\le R+(1-t)z-\tau g^m\notag
\end{align}
where $\tau$ is the subsidy rate on contributions and $t$ is the (linear) tax rate on earnings. 

## Optimization

This problem derives the indirect utility function $v^i(1-t, 1-\tau, G, R, p)$, demand functions $z^i(1-t,1-\tau, G,R,p)$ for earnings, $g^i(1-t,1-\tau,G,R,p)$ for true contribution and $g^m^i(1-t,1-\tau, G,R,p)$ for unreported contribution. Using the Roy's identity we can derive the welfare effect of $t$ and $\tau$ as
\begin{align}
\begin{cases}
v_{1-t}^i&=z^iv_R^i\\
v_{1-\tau}^i&=-(g-g^m)v_R^i.
\end{cases}
\end{align}

The government's problem is
\begin{align}
\max_{t,\tau,p}&W=\int\mu^iv^i(1-t,1-\tau,G,p,R)\notag\\
\text{s.t }&t\bar{Z}\ge R+\tau\underbrace{(\bar{G}+\bar{G}^m)}_{\bar{G}^r}+C(p)\notag,
\end{align}
where $\mu^i$ is the social weight associated with individual $i$ in the social welfare function. $C(p)$ is the administrative cost of enforcement, which we assume $C'(p)>0$. $\bar{G}=\bar{G}(1-t,1-\tau,G,p,R)$, $\bar{G}^m=\bar{G}^m(1-t,1-\tau,G,p,R)$, $\bar{G}^r=\bar{G}^r(1-t,1-\tau,G,p,R)$, and $\bar{Z}=\bar{Z}(1-t,1-\tau,G,p,R)$ are respectively average true contribution, average unreported contribution, average reported contribution, and average earning for a given level of the policy parameters.

We denote the Lagrange multiplier for the government budget constraint as $\lambda$, which is equivalent to the marginal value of public fund. The first-order conditions of the government problems for $\tau$ and $p$ are
\begin{align}
		&-\int \mu^i[v_{1-\tau}^i+v_G^i\bar{G}_{1-\tau}]d\nu_i+\lambda[t\bar{Z}_{1-\tau}+\bar{G}^r-\tau\bar{G}^r_{1-\tau}]=0\label{tau}\\
		&\int \mu^i[v_{p}^i+v_G^i\bar{G}_{p}]d\nu_i+\lambda[t\bar{Z}_p-\tau\bar{G}^r_{p}-C'(p)]=0\label{p},
\end{align}
where for all variables $X$ and $y$, $X_y$ denotes the partial derivative of $X$ with respect to $y$.

Firstly, we examine the effect of requirements $p$ on $\bar{G}^p$. Since we can derive
\begin{align}
\tau\bar{G}^r=\int_0^{\tau}(\tau\frac{\partial \bar{G}^r}{\partial \tau}+\bar{G}^r)d\tau=\int_0^{\tau}\bar{G}^r(1-\frac{\tau}{1-\tau}\varepsilon_{G^r})d\tau\notag\forall \tau
\end{align}
where $\varepsilon_{G^r}$ is the elastivity of reported contributions with respect to the subsidy $1-\tau$, the partial derivative by $p$ will be
\begin{align}
\tau\bar{G}_p^r=\int_0^{\tau}[\bar{G}_p^r(1-\frac{\tau}{1-\tau}\varepsilon_{G^r})-\bar{G}^r\frac{\tau}{1-\tau}\frac{\partial\varepsilon_{G^r}}{\partial p}]d\tau\notag.
\end{align}

This equation shows that the enforcement of requirement $p$ affect on the reported contribution $\bar{G}^r$ via two channels. The first channel is a direct effect of the changing $p$ on $\bar{G}^r$. In the second channel, $p$ have an effect on the elasticity of $\bar{G}^r$. @Fack2016 points out that this effect stems from the fact that $p$ can control the elasticity of reported contributions $\frac{\partial \epsilon_{G^r}}{\partial p}\neq0$.

## Implications for the price elasticity
Since our interest is to derive the implication about the price elastisity of giving, we follow @Saez2004 and show the relationship between the elastisities of true contribution and reported contribution.

Define individual i's marginal value of consumption evaluated by the marginal value of public funds as $\beta^i=\mu^iv_R^i/\lambda$. The average $\beta^i$ is $\beta(R)\equiv\int\beta^idv(i)$, which means the average marginal value of transfer $R$ evaluated by a marginal value of public fund. Similarly, define $\beta(\bar{G}^r)\equiv \int(g-g^m)\beta^idv(i)/\bar{G}^r$. This means the average marginal value of subsidy for contribution $1-\tau$ since $v_{1-t}^i=-g^iv_R^i$ and $\beta^i=\mu^iv_R^i/\lambda$ here.

Assume that the government now can directly provide the public good $G^d$ and transfer $R$ does not have an effect on earning $z$, i.e. $\partial z/\partial R=0$. When the public good level is optimal, $dG+dG^d=0$ holds and the effect of the change of $\tau$ on the social welfare must be 0. Utilizing this fact, we can consider four channels of $\tau$'s effect on the welfare and the sum of these effects will be 0.

1. Marginal increase of $\tau$ leads to the increase of reported contribution (and decrease the same amount of direct provision of public good) $A=-G^rd\tau=-(G-G^m)d\tau$
2. Marginal increase of $\tau$ leads to the increase of welfare via the increment of contribution, which can be attributed to the individual's warm-glow. The individual's increase of welfare here is 
\begin{align}
-v_{1-\tau}^id\tau=(g-g^m)v_R^id\tau\notag.
\end{align}
Evaluated by the marginal value of public fund, this average value will be
\begin{align}
\beta(G^r)=\frac{\int(g-g^m)\beta^idv(i)}{\bar{G}^r}\notag.
\end{align}
Considering that this effect works for each increament of contribution, the second effect is $B=\beta(G^r)\bar{G}^rd\tau$.
3. Marginal increase of $\tau$ leads to the reduction of budget of government via the change of public good provision. Therefore, $C=-\taud\bar{G}^r=-\tau(d\bar{G}-d\bar{G}^m)$. Using $d\bar{G}+dG^d=0$, this can be rewritten as $C=\tau(\frac{-\bar{G}}{1+G_{G^d}}d\tau-\bar{G}^m_{1-\tau}d\tau)$.
4. Finally, the government adjusts the direct contribution to optimal level. $D=-dG^d=dG=-\frac{G_{1-\tau}}{1+G_{G^d}}d\tau$.

For each effect, please see @Saez2004 for detail. The sum of four channels' effects are zero. 
\begin{align}
A+B+C+D=-(G-G^m)d\tau+\beta(G^r)\bar{G}^rd\tau+\tau(\frac{-\bar{G}}{1+G_{G^d}}d\tau-\bar{G}^m_{1-\tau}d\tau)-\frac{G_{1-\tau}}{1+G_{G^d}}d\tau=0\label{sum}
\end{align}

Defining $\alpha=\frac{G}{G^r}, \epsilon_G=\frac{1-\tau}{G}\frac{\partial G}{\partial 1-\tau}, \epsilon_{G^r}=\frac{1-\tau}{G^r}\frac{\partial G^r}{\partial 1-\tau}$, and $\epsilon_{G^m}=\frac{1-\tau}{G^m}\frac{\partial G^m}{\partial 1-\tau}$, (\ref{sum}) will be
\begin{align}
(1-\alpha)\frac{\tau}{1-\tau}\epsilon_{G^m}-\alpha\epsilon_G\frac{1}{1+G_{G^d}}=1-\beta(G^r)\notag.
\end{align}
When crowding out is zero, i.e. $G_{G^d}=0$, this will be
\begin{align}
\epsilon_G=-\frac1{\alpha}(1-\beta(G^r))-\frac{1-\alpha}{\alpha}\frac{\tau}{1-\tau}\epsilon_{G^m}.\label{opt}
\end{align}
If the true contribution and reported contribution are coincide, i.e. $G=G^r$, $\epsilon_G$ will be
\begin{align}
\epsilon_G=-1+\beta(G^r)\notag.
\end{align}
Therefore, if the marginal value of subsidy is ignored, $\beta(G^r)=0$ holds and $\epsilon_G=1$ holds as the extant research have shown.

Using $G=G^r+G^m$ and $\frac{\partial G}{\partial 1-\tau}=\frac{\partial G^r}{\partial 1-\tau}+\frac{\partial G^m}{\partial 1-\tau}$, we can derive
	\begin{align}
	\epsilon_G&=\frac{1-\tau}{G}\frac{\partial G^r}{\partial 1-\tau}+\frac{1-\tau}{G}\frac{\partial G^m}{\partial 1-\tau}\notag\\
	&=\frac{1}{\alpha}\epsilon_{G^r}+\frac{\alpha-1}{\alpha}\epsilon_{G^m}\notag.
	\end{align}
Substituting this into (\ref{opt}) leads to
\begin{align}
\epsilon_{G^r}=\frac{1}{\tau}[\alpha\epsilon_G+(1-\beta(G^r))(1-\tau)].
\end{align}
Comparing $\epsilon_{G}$ and $\epsilon_{G^r}$, if $|\epsilon_G|\lessgtr\frac{(1-\beta(G^r))(1-\tau)}{\alpha-\tau}$ holds, $\epsilon_G\lessgtr\epsilon_{G^r}$ can be derived.

Ignore the marginal value of subsidy, i.e. $\beta(G^r)=0$. The giving price in Korea was $\tau\in[0.06,0.38]$ before 2013 and $\tau=0.15$ after 2014. Based on the NaSTab data, $\alpha=\frac{G}{G^r}>1$. Therefore, $\frac{(1-\beta(G^r))(1-\tau)}{\alpha-\tau}=\frac{1-\tau}{\alpha-\tau}<1$ holds. 

```


```{asis, echo = doctype == "slide"}
## 2014 tax reform in South Korea

Our major price variation comes from the 2014 tax reform, which has changed from the tax deduction system to the tax credit system

- Consider allocation problem b/w private consumption ($x_{it}$) and giving ($g_{it}$). 
- The budget constraint is $x_{it} + g_{it} = y_{it} - T(y_{it}, g_{it})$ where $y_{it}$ is pre-tax total income, and $T(y_{it}, g_{it})$ is tax amount.
- Let $R_{it}$ be a dummy of declaration of tax relief, and let $\tau(\cdot)$ be the income tax rate.

## 2014 tax reform in South Korea (Cont'd)

**Tax deduction system (until 2013)** 

$$T(y_{it}, g_{it}) = \tau(y_{it} - R_{it} g_{it}) (y_{it} - R_{it} g_{it})$$

- In 2012 and 2013, the system of $\tau(\cdot)$ is same.
- The logged relative giving price is $R_{it} \ln(1 - \tau(y_{it} - g_{it})) = R_{it} \ln p^d_{it}$.

**Tax credit system (from 2014)**

$$T(y_{it}, g_{it}) = \tau(y_{it}) \cdot y_{it} - R_{it} m g_{it}$$

- $m = 0.15$
- The logged relative giving price is $R_{it} \ln(1 - 0.15) = R_{it} \ln 0.85$.
```

```{asis, echo = doctype == "draft"}
# Institutional background

In this section, we describe the income tax relief for charitable giving in Korea and used dataset.

## Tax relief for charitable giving by tax deduction and tax credit

In the South Korea, the tax policy about charitable giving drastically changed in 2014. Before then, tax relief of charitable giving was provided by tax deduction while, from 2014, tax relief by tax credit was introduced instead of tax deduction. 

The tax deduction and tax credit may have different effects on giving behavior. This subsection summarize the difference of tax deduction and tax credit.
Consider that a household has a choice between private consumption ($x_i$) and charitable giving ($g_i$). Let $y_i$ be pre-tax total income.
Then, the budget constraint is 
\begin{align}
    x_i + g_i = y_i − R_iK - R_iT_i(y_i, g_i) - (1-R_i)T_i(y_i).
\end{align}
$T_i$ is tax amount which depends on the pre-tax income and charitable giving.
$R_i$ is the dummy which takes 1 if $i$ declares the tax relief and 0 otherwise. $K$ is a cost for the declaration of charitable giving, which may not be monetary cost but is converted to pecuniary terms. 

Tax payers declare their charitable giving if its benefit exceeds its cost, which means

\begin{align}
R_i=\begin{cases}
1 \text{ if }T_i(y_i, g_i) - T_i(y_i)>K\\
0 \text{ if }T_i(y_i, g_i) - T_i(y_i)\le K.
\end{cases}
\end{align}

This means that the decision of declaration depends on $y_i$, $g_i$ and $K$, where $g_i$ is considered to be much easier for tax payers to adjust than the others.

On one hand, tax deduction reduces taxable income by giving. The amount of tax is

\begin{align}
    T_i(y_i, g_i) = \tau(y_i - g_i) \cdot (y_i - g_i),
\end{align}
or,
\begin{align}
    T_i(y_i) = \tau(y_i) \cdot (y_i),
\end{align}

where $\tau(\cdot)$ is the income tax rate which is determined by $y_i - g_i$ or $y_i$.[^ATR] The budget constraint will be 

[^ATR]: $\tau(\cdot)$ here is a function which shows the average tax rate, which is determined progressively. Since the price elasticity of giving shows the marginal and additional increment for one unit of price reduction increase, we use not average but marginal tax rate to construct the giving price following the literature. Usage of the function of the average tax rate here is for explanatory simplicity.

\begin{align}
    x_i + [1 - R_i\tau(y_i - g_i)]g_i = [1 - R_i\tau(y_i - g_i)-(1-R_i)\tau(y_i)] y_i− R_iK.
\end{align}

Thus, the giving price compared to the price of private consumption is $p_i^{d} \equiv 1 - R_i\tau(y_i - g_i)$ in tax deduction system. Since the giving price in tax deduction scheme varies depending on (1) the income level, (2) the amount of charitable giving, and (3) declaration of tax relief, it is endogenous to them, i.e. (1), (2), and (3).

On the other hand, tax credit reduces tax amount directly, that is,

$$
    T_i = \tau(y_i)\cdot y_i - R_im g_i ,
$$

where $m \in [0, 1]$ is the tax credit rate. Under the tax credit system, the budget constraint is 

\begin{align}
    x_i + (1 - R_im) g_i = [1 - \tau(y_i)] y_i − R_iK.
\end{align}

Thus, the giving price of tax credit system will be $p_i^c = 1 - R_im$, which is only dependent on the tax credit rate $m$, which is exogenously determined by the government, and declaration $R_i$.
Therefore, the giving price in the tax credit system would not be manipulated by donors except the declaration.

In the literature of giving tax relief, many papers implicitly assume that $K=0$ and all tax payers should enjoy tax relief for charitable giving, i.e. $R_i=1$ for all $i$.\footnote{As an exception, Rehavi and Shack (2013) and Almunia et al. (2020) respectively consider the declaration by using the survey data and the stractural estimation.} As a result, the observed amount of the charitable giving $g_i$ may be different from the realized amount of the charitable giving $g_i$.

To overcome this issue, we use two ways of estimations. In section 5, we assume $R_i=1$ for all $i$ following the extant research and estimate ITT as a baseline result. The difference between this analysis and the extant research is that the observed charitable giving $g_i$ in the former is not limited to declared one, but $g_i$ in the latter is limited to declared one. In section 6, we remove the assumption, that is $R_i=1$, and $R_i$ can be 0 or 1 depending on each $i$, which is the difference from the extant research. 
```

```{r tabTaxRate, include=TRUE, eval = doctype == "draft"}
tab <- data.frame(
    inc = c(
        "(A) ~ 1200", "(B) 1200 ~ 4600", "(C) 4600 ~ 8800", "(D) 8800 ~ 15000",
        "(E) 15000 ~ 30000", "(F) 30000 ~ 50000", "(G) 50000 ~"),
    Y08 = c("8%", "17%", "26%", rep("35%", 4)),
    Y09 = c("6%", "16%", "25%", rep("35%", 4)),
    Y1011 = c("6%", "15%", "24%", rep("35%", 4)),
    Y1213 = c("6%", "15%", "24%", rep("35%", 2), rep("38%", 2)),
    Y1416 = c("6%", "15%", "24%", "35%", rep("38%", 3)),
    Y17 = c("6%", "15%", "24%", rep("35%", 2), "38%", "40%"),
    Y18 = c("6%", "15%", "24%", "35%", "38%", "40%", "42%")
)

knitr::kable(
    tab,
    caption = "Marginal Income Tax Rate",
    col.names = c(
      "Income/Year", "2008", "2009", "2010 ~ 2011",
      "2012 ~ 2013", "2014 ~ 2016", "2017", "2018"
    ),
    row.names = FALSE,
    align = "lccccccc",
    booktabs = TRUE, escape = TRUE, linesep = ""
) %>%
kable_styling(font_size = 9) %>%
collapse_rows(columns = 2:8, valign = "middle", latex_hline = "full") %>%
footnote(general_title = "", general = "Notes: Marginal income tax rates applied from 2008 to 2018 are summarized. The income level is shown in terms of 10,000 KRW, which is approximately 10 United States dollars (USD) at an exchange rate of 1,000 KRW to one USD.", threeparttable = TRUE, escape = FALSE)
```

```{asis, echo = doctype == "draft"}
## Korean tax reform in 2014

Korean tax system offers a tax relief for charitable giving in income tax. All tax payers have to declare their donation and submit the certificate of charitable giving to receive tax relief, while the taxiation method and the way of tax declaration are different for wage earners and self-employed workers. Wage earners pay income tax by withholding tax and declare tax relief for charitable giving via their company. Self-employed workers pay income tax by tax-return and declare tax relief when they submit tax return to the National Tax Service. Therefore, there is a difference of declaration cost of tax relief since self-employed workers have to retain the certificate until they submit tax return although wage earners can submit the certificate at any time.   

In 2014, aiming at the relaxation of regressivity of giving price, the Korean government reformed tax system, where the tax credit was introduced instead of tax deduction. Since then, 15\% of the total amount of charitable giving has been allowed as a tax credit, which means that the giving price from 2014 is 0.85 KRW for each 1 KRW of donation irrelevant to the income level.

Summarizing this, compared to tax credit system, the high income household, whose (average) income tax rate is more than 15\%, get benefit from charitable giving under the tax deduction system. However, middle or low income households would enjoy tax relief in tax credit system more than tax deduction system. We exploit this policy change as an identification strategy.
```
