```{r eval = FALSE}
# if you want to preview this file,
# 1. specify doctype: "draft" or "slide"
# 2. replace knitr format = "html"
library(here); knitr::opts_knit$set(root.dir = here())
doctype <- "draft"
options(knitr.kable.NA = " ", knitr.table.format = "html")
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo = FALSE,
  cache = FALSE,
  include = TRUE
)
```

# Introduction

```{asis, echo = doctype == "slide"}
## Charitable Giving and Taxiation
In many countries, governments set a tax relief for charitable giving.

To evaluate the effect of tax relief, many papers investigate the elasticity of charitable donations with respect to their tax price [@Randolph1995; @Auten2002; @Fack2010; @Bakija2011; @Almunia2020].

Focusing on the tax deduction or tax credit on the charity, they show that the price elasticity of giving is about -1 or more in terms of absolute value.

## Charitable Giving and Taxiation

In addition to the tax price charitable donations, the donations may be affected by people's perception towards the government. 

This is because the works and missions of private charity often mirror or overlap with one of governments, and the charity is not needed if the government adequately satisfies the needs of society.

Thus, the different perception towards the government may make the different behavior for charitable giving.

We investigate the relation between tax price elasticity of charitable donations and the different perception towards the government using the South Korean dataset.


## Summary in short

Our result classifies that:

- the price elasticity of giving in Korea is -1.07 ~ -1.26, which is within the range of the extant research.
- the amount of donation is not different between those who regard government as inefficient and the others.
- the giving price elasticity of those who regard government as inefficient is more elastic than the others. This means that those who think of government as inefficient have more willingness to donate for 1\% reduction of giving price. 

## South Korean tax reform

We can utilize the effect of the 2014 tax reform in the South Korea.

- Before 2014, tax deduction was adopted to subsidize charitable donation behavior.
- After 2014, tax credit have been adopted.

The main difference is that tax credits reduce taxes directly, while tax deductions indirectly lower the tax burden by decreasing the marginal tax rate, which increases with gross income.

In addition, the dataset contains the information about perception towards the government.


## Related Literature

This study mainly relates to the two strands of studies.

 1. Research about tax price elasticity of charitable donations
 2. Research about perception towards the government and donation/tax payment.
  

## Research about tax price elasticity of charitable donations

Papers in this strand examines the price and income elasticity of charitable donations using the tax deduction applied for donation.
The estimated price elasticities vary, but the typical one is said as -1 (Andreoni and Payne, 2013).
  
  - Auten et al.(2002): -0.79~-1.26 (the U.S.)
  - Fack and Landais(2010): -0.15~-0.57 (France)
  - Bakija and Heim (2011): -0.61~-1.1 (the U.S.)
  - Duquette (2016): -2.15~-5.01 (the U.S.)
  - Almunia et al.(2020): -0.24~--1.5 (the U.K.)
  
The study in non-Western country, where the culture of donation may be different, is few.
Thus, we firstly examine the elasticity of giving in Korea.

## Research about perception towards the government and donation/tax payment.

Experimental studies show that the giving behavior may be affected by perception towards the government.

 - Li et al.(2011) suggest that governmental organizations collect less donation than private charities though they have the same mission and work.
 - Sheremeta and Uler(2020) show that individuals provide public good reacting the wasteful spending of government.

This may be because people with distrust in government think that

 1. the direct donation is more efficient than public service provision or
 2. people can directly allocate and control their funds by donation, unlike public service provision. 

Thus, people having the different trust in the government would have different elasticities of giving.
```

```{asis, echo = doctype == "draft"}
In many countries, governments set a tax relief for charitable giving. This is because, if subsidizing charitable giving induces a large increase in donations, it is desirable for public good provision. As @Saez2004 shows, it is known that the price elasticity of charitable donations is a key parameter to evaluate the welfare implication. To evaluate the effect of tax relief, many empirical papers investigate the elasticity of charitable donations with respect to their tax price and find that the price elasticity is around -1 in terms of intensive margin, using the data from tax record [@Randolph1995; @Auten2002; @Fack2010; @Bakija2011; @Almunia2020].

However, as @Almunia2020 point out, the analysis based on tax record only captures the effect for tax payers who declare charitable tax deduction, while charitable donation may also be conducted by those who do not declare it. As @Fack2016 and @Gillitzer2018 suggest that tax payers incur some cost for the declaration of charitable tax deduction such as record-keeping costs and compliance cost, tax payers may not declare their charitable giving if the benefit of the declaration exceeds the cost of it. Therefore, @Rehavi2013 suggest that the estimated tax elasticity will be biased if the data used for the estimation only focuses on tax payers who declare charitable tax deduction.

Considering the issue of the declaration, this paper follows the literature of charitable donation and tax relief, and investigates the price elasticity of giving. To derive the elasticity, this paper utilize the South Korean (Korea hereafter) tax reform in 2014, from when the tax relief on charitable giving was conducted by tax credit, though tax deduction had been used before 2014.

The extant research mainly focuses on the tax reform within the regime of tax deduction [@Randolph1995; @Auten2002; @Bakija2011; @Almunia2020] or tax credit [@Fack2010]. However, there is no research which deal with the giving tax reform between the regime of tax deduction and tax credit as far as we know. Since the extant research focus on the tax reform within the scheme of tax deduction or tax credit, this paper firstly deals with the tax reform from tax deduction system to tax credit system. 

The Korean tax reform in 2014 started to allow 15\% of the total amount of charitable giving as a tax credit for all taxpayers, which means that the giving price for 1 KRW donation is 0.85 KRW\footnote{1 KRW is approximately 0.0001 USD. In other words, 1 USD is about 10,000 KRW.}. Since the giving price was determined according to the marginal tax rate of progressive income tax before 2014, this tax reform reduced the giving price for low income taxpayers while it increased the price for high income tax payers. Since the variation of giving price can be considered to be exogenous for taxpayers, we exploit this reform and conduct the difference-in-difference (DID) analysis following the extant research about the giving price elasticity. 

Moreover, to overcome the issue of tax declaration, we use the Korean survey panel data called the National Survey of Tax and Benefit (NaSTaB) and estimate intention-to-treat (ITT) of tax relief for giving as a baseline analysis. Since NaSTaB data contains the data of charitable giving irrespective of declarations, the baseline analysis examine the ITT of tax relief on the all charitable giving.
As a result, our baseline estimation shows that the price elasticity of charitable giving in Korea is -0.59 ~ -1.01 for intensive margins and -1.17 ~ -1.48 for extensive margins. 

However, the estimation of the ITT implicitly assumes that the donors can automatically enjoy tax relief although tax payers have to declare their charitable giving to receive tax relief. Therefore, as an alternative way, we calculate an "effective" giving price considering whether each tax payer declare tax relief or not. Since whether tax payers declare or not may be endogenous with the amount of charitable giving, to overcome this issue, we focus on the fact that wage earners can easily declare tax relief in their company while self-employed workers have to declare tax relief via tax agency in Korea. By utilizing this difference as an instrument variable (IV), we estimate the price elasticity using the effective giving price, and compare the estimation with the baseline estimation. As a result, we find that the results using the effective price are -0.94 ~ -1.16 in terms of intensive margin and -0.92 ~ -1.46 in terms of extensive margin, which is almost the same for the baseline results. Since the estimated results are in line with the extant research, the result implies that the effect from the declaration cost may not so large. 

This paper contributes the literature about the charitable giving tax system for the following points. Firstly, this paper considers the price elasticity of charitable giving using the effective giving price, although most of papers assume that the giving price applied for the charitable giving is the cheapest "applicable" giving price for each tax payer. As a result, although @Rehavi2013 suggest that the estimations using the effective price and the applicable price should be very different, our results suggest that the bias coming from the difference of the estimations may be small. Moreover, since our robustness checks to control the manipulations for giving price and intertemporal income shifting show more different results from the baseline ones than the results considering the declaration issue, the results implies that the bias from the declaration issue may be considerably small.

Secondly, by using the survey data, which cannot be manipulated, we could consider the sample of low-income household. The research in this literature typically use the tax return data, the main part of which is the data about wealthy people. Since our data is based on survey, which reflects the income distribution of population, we believe that we can estimate the giving price elasticity of population more precisely. Moreover, the usage of survey data is important for the estimation of the price elasticity in terms of the extensive margin since the propensity of donation by low-income households would be be less than high-income households. 

Thirdly, this paper is the first paper to examine the giving price elasticity in a non-Western country. While the giving behavior may be affected by the cultural matter such as the religious belief, the estimated price elasticity in this paper is in line with the result of the extant papers.

This paper consist of seven sections. Section 2 and 3 respectively explain the institutional background and data. Section 4 explains the estimation method. Section 5 deals with the analysis of price elasticity using the applicable giving price and section 6 shows the analysis using the effective giving price. Section 7 concludes.
```

# Institutional background

```{asis, echo = doctype == "slide"}
## Tax relief for charitable giving by tax deduction and tax credit

In the South Korea, the tax policy about charitable giving drastically changed in 2014. Before then, tax relief of charitable giving was provided by tax deduction while, from 2014, tax relief by tax credit was introduced instead of tax deduction. 

The tax deduction and tax credit may have different effects on giving behavior. 
This section summarize the difference of tax deduction and tax credit.

## Budget Set

Consider that a household has a choice between private consumptions ($x_i$) and charitable giving ($g_i$). Let $y_i$ be pre-tax total income.
Then, the budget constraint is 

$$
    x_i + g_i = y_i - T_i(y_i, g_i).
$$
$T_i$ is tax amount which depends on the pre-tax income and charitable giving.

## Tax Deduction

Tax deduction reduces taxable income by giving, that is,

$$
    T_i = \tau(y_i - g_i) \cdot (y_i - g_i),
$$

where $\tau(\cdot)$ is the marginal income tax rate which is determined by $y_i - g_i$. The budget constraint will be 

$$
    x_i + [1 - \tau(y_i - g_i)]g_i = [1 - \tau(y_i - g_i)] y_i.
$$

The relative price of giving is $p_i^{d} \equiv 1 - \tau(y_i - g_i)$.
Since the giving price in tax deduction scheme varies depending on (1) the income level and (2) the amount of charitable giving, it is endogenous to them.

## Tax Credit

Tax credit reduces tax amount directly, that is,

$$
    T_i = \tau(y_i)\cdot y_i - m g_i,
$$

where $m \in [0, 1]$ is the tax credit rate. Under the tax credit system, the budget constraint is 

$$
    x_i + (1 - m) g_i = [1 - \tau(y_i)] y_i.
$$

The relative price of giving is $p_i^c = 1 - m$, 
which is only dependent on the tax credit rate $m$, which is exogenously determined by the government.

## Korean tax reform in 2014

- The tax incentives for charitable giving in Korea stared in 2000 and the market of charitable giving in Korea totaled 10.9 trillion KRW (approximately 1.09 bilion USD, 0.761% of GDP) in 2012 according to the national tax statistics.
- Since the income tax deduction was initially used as a tax incentive and the marginal income tax rate was determined as Table \@ref(tab:tabTaxRate), the minimum giving price before 2014 was 0.62. 

## Marginal income tax rate
```

```{asis, echo = doctype == "draft"}
In this section, we describe the income tax relief for charitable giving in Korea and used dataset.

## Tax relief for charitable giving by tax deduction and tax credit

In the South Korea, the tax policy about charitable giving drastically changed in 2014. Before then, tax relief of charitable giving was provided by tax deduction while, from 2014, tax relief by tax credit was introduced instead of tax deduction. 

The tax deduction and tax credit may have different effects on giving behavior. This subsection summarize the difference of tax deduction and tax credit.
Consider that a household has a choice between private consumption ($x_i$) and charitable giving ($g_i$). Let $y_i$ be pre-tax total income.
Then, the budget constraint is 
$$
    x_i + g_i = y_i − R_iK - R_iT_i(y_i, g_i) - (1-R_i)T_i(y_i).
$$
$T_i$ is tax amount which depends on the pre-tax income and charitable giving.
$R_i$ is the dummy which takes 1 if $i$ declares the tax relief and 0 otherwise. $K$ is a cost for the declaration of charitable giving, which may not be monetary cost but is converted to pecuniary terms. 

Tax payers declare their charitable giving if its benefit exceeds its cost, which means
$$
R_i=\begin{cases}
1 \text{ if }T_i(y_i, g_i) - T_i(y_i)>K\\
0 \text{ if }T_i(y_i, g_i) - T_i(y_i)\le K.
\end{cases}
$$
This means that the decision of declaration depends on $y_i$, $g_i$ and $K$, where $g_i$ is considered to be much easier for tax payers to adjust than the others.

On one hand, tax deduction reduces taxable income by giving. The amount of tax is
$$
    T_i(y_i, g_i) = \tau(y_i - g_i) \cdot (y_i - g_i)\\
    T_i(y_i) = \tau(y_i) \cdot (y_i),
$$

where $\tau(\cdot)$ is the income tax rate which is determined by $y_i - g_i$ or $y_i$.[^ATR] The budget constraint will be 

[^ATR]: $\tau(\cdot)$ here is a function which shows the average tax rate, which is determined progressively. Since the price elasticity of giving shows the marginal and additional increment for one unit of price reduction increase, we use not average but marginal tax rate to construct the giving price following the literature. Usage of the function of the average tax rate here is for explanatory simplicity.

$$
    x_i + [1 - R_i\tau(y_i - g_i)-(1-R_i)\tau(y_i)]g_i = [1 - R_i\tau(y_i - g_i)-(1-R_i)\tau(y_i)] y_i− R_iK.
$$

Thus, the giving price compared to the price of private consumption is $p_i^{d} \equiv 1 - R_i\tau(y_i - g_i)-(1-R_i)\tau(y_i)$ in tax deduction system. Since the giving price in tax deduction scheme varies depending on (1) the income level, (2) the amount of charitable giving, and (3) declaration of tax relief, it is endogenous to them, i.e. (1), (2), and (3).

On the other hand, tax credit reduces tax amount directly, that is,

$$
    T_i = \tau(y_i)\cdot y_i - R_im g_i ,
$$

where $m \in [0, 1]$ is the tax credit rate. Under the tax credit system, the budget constraint is 

$$
    x_i + (1 - D_im) g_i = [1 - \tau(y_i)] y_i − D_iK.
$$

Thus, the giving price of tax credit system will be $p_i^c = 1 - D_im$, which is only dependent on the tax credit rate $m$, which is exogenously determined by the government, and declaration $D_i$.
Therefore, the giving price in the tax credit system would not be manipulated by donors except the declaration.

In the literature of giving tax relief, many papers implicitly assume that $K=0$ and all tax payers should enjoy tax relief for charitable giving, i.e. $R_i=1$ for all $i$\footnote{As an exception, Rehavi and Shack (2013) and Almunia et al. (2020) respectively consider the declaration by using the survey data and the stractural estimation.}. As a result, the observed amount of the charitable giving $g_i$ may be different from the realized amount of the charitable giving $g_i$.

To overcome this issue, we use two ways of estimations. In section 5, we assume $R_i=1$ for all $i$ following the extant research and estimate ITT as a baseline result. The difference between this analysis and the extant research is that the observed charitable giving $g_i$ in the former is not limited to declared one, but $g_i$ in the latter is limited to declared one. In section 6, we remove the assumption, that is $R_i=1$, and $R_i$ can be 0 or 1 depending on each $i$, which is the difference from the extant research. 
```

```{r tabTaxRate, include=TRUE}
tab <- data.frame(
    inc = c(
        "(A) ~ 1200", "(B) 1200 ~ 4600", "(C) 4600 ~ 8800", "(D) 8800 ~ 15000",
        "(E) 15000 ~ 30000", "(F) 30000 ~ 50000", "(G) 50000 ~"),
    Y08 = c("8%", "17%", "26%", rep("35%", 4)),
    Y09 = c("6%", "16%", "25%", rep("35%", 4)),
    Y1011 = c("6%", "15%", "24%", rep("35%", 4)),
    Y1213 = c("6%", "15%", "24%", rep("35%", 2), rep("38%", 2)),
    Y1416 = c("6%", "15%", "24%", "35%", rep("38%", 3)),
    Y17 = c("6%", "15%", "24%", rep("35%", 2), "38%", "40%"),
    Y18 = c("6%", "15%", "24%", "35%", "38%", "40%", "42%")
)

knitr::kable(
    tab,
    caption = "Marginal Income Tax Rate",
    col.names = c(
      "Income/Year", "2008", "2009", "2010 ~ 2011",
      "2012 ~ 2013", "2014 ~ 2016", "2017", "2018"
    ),
    row.names = FALSE,
    align = "lccccccc",
    booktabs = TRUE, escape = TRUE, linesep = ""
) %>%
kable_styling(font_size = 7) %>%
collapse_rows(columns = 2:8, valign = "middle", latex_hline = "full") %>%
footnote(general_title = "", general = "Notes: Marginal income tax rates applied from 2008 to 2018 are summarized. The income level is shown in terms of 10,000 KRW, which is approximately 10 United States dollars (USD) at an exchange rate of 1,000 KRW to one USD.", threeparttable = TRUE, escape = FALSE)
```

```{asis, echo = doctype == "slide"}
## Our Identification Strategy

In 2014, aiming at the relaxation of regressivity of giving price, the Korean government reformed tax system again, where the tax credit was introduced instead of tax deduction. Since then, 15\% of the total amount of charitable giving has been allowed as a tax credit, which means that the giving price from 2014 is 0.85 irrelevant to the income level.

Summarizing this, compared to tax credit system, the high income household, whose (average) income tax rate is more than 15\%, get benefit from charitable giving under the tax deduction system. However, middle or low income households would enjoy tax relief in tax credit system more than tax deduction system. We exploit this policy change as an identification strategy.
```

```{asis, echo = doctype == "draft"}
## Korean tax reform in 2014

Korean tax system offers a tax relief for charitable giving in income tax. All tax payers have to declare their donation and submit the certificate of charitable giving to receive tax relief, while the taxiation method and the way of tax declaration are different for wage earners and self-employed workers. Wage earners pay income tax by withholding tax and declare tax relief for charitable giving via their company. Self-employed workers pay income tax by tax-return and declare tax relief when they submit tax return to the National Tax Service. Therefore, there is a difference of declaration cost of tax relief since self-employed workers have to retain the certificate until they submit tax return although wage earners can submit the certificate at any time.   

In 2014, aiming at the relaxation of regressivity of giving price, the Korean government reformed tax system, where the tax credit was introduced instead of tax deduction. Since then, 15\% of the total amount of charitable giving has been allowed as a tax credit, which means that the giving price from 2014 is 0.85 irrelevant to the income level.

Summarizing this, compared to tax credit system, the high income household, whose (average) income tax rate is more than 15\%, get benefit from charitable giving under the tax deduction system. However, middle or low income households would enjoy tax relief in tax credit system more than tax deduction system. We exploit this policy change as an identification strategy.
```
