name: 'Kanban Automation for analysis'

on: [issues]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - name: Move labeled issues into "issues related analysis"
        if: github.event.action == 'labeled' && github.event.label.name == 'empirics'
        uses: alex-page/github-project-automation-plus@v0.7.1
        with:
          project: My task board
          column: To do (empirics)
          repo-token: ${{ secrets.KANBAN_AUTO_EMPIRICS }}
